### ISSUE TITLE
🐛判断是否进入商店的地方，曜之阁如果开启了图片是不一样的

### ISSUE THREAD

**Issue by wanniwa** [runhey/OnmyojiAutoScript#105]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的

### 描述你的问题

进入商场没反应

### 如何复现

1. 开启每日琐事
2. 程序进入商店不执行

### 预期行为

应该继续点击礼包
是否考虑换一个截图位置

### 截图

![image](https://github.com/runhey/OnmyojiAutoScript/assets/26156945/b4cec762-12bf-4384-aa7c-46162b43a8d7)
![image](https://github.com/runhey/OnmyojiAutoScript/assets/26156945/b7fbc12f-d61d-4f46-91d8-7405a8a05521)

**Comment by runhey** [comment]
![page_check_mall](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/52b14708-56c4-4919-8c69-287bbac340dc)
换呗

**Comment by kingsely666** [comment]
曜之阁开启后，在商店街页面无法识别到的问题还是存在
