### ISSUE TITLE
🐛按名字更换御魂的滑动问题

### ISSUE THREAD

**Issue by TripleEarth** [runhey/OnmyojiAutoScript#112]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的

### 描述你的问题

当队伍预设分组过多时会存在往上滑动不到头的情况

### 如何复现

1. 创建较多队伍预设分组，如20个，不需要创建预设队伍
2. 点击最下面的分组，如分组20
3. 启动带有按名字更换御魂的任务，且目标分组较为靠前
4. 此时代码会尝试找到最上面的分组，但是只划拉一下就不再往上了
5. 看过了代码，是因为滑动间隔设置了6秒，但是第二个while循环后认定分组名字相同从而认为已经到顶

**Comment by runhey** [comment]
同时又发现一个小问题，在使用window_message下，右边的group是无法滑动的，但是左边的team是可以的
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/3ea7acfb-2288-4500-86d8-bc2c2b383578)
