### ISSUE TITLE
收取体力盒子时候取出完毕就不动了

### ISSUE THREAD

**Issue by cleanslatert** [runhey/OnmyojiAutoScript#113]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的

### 描述你的问题

体力盒子取出之后，就一直在这个页面上也不动了

### 如何复现

1. 前往 '体力食盒'
2. 点击 '取出'
4. 取出完之后，出现问题，卡在界面上

### 预期行为

麻烦你解决这个问题

### 截图

![屏幕截图 2023-09-22 092500](https://github.com/runhey/OnmyojiAutoScript/assets/139217324/e2ee3687-0fd3-483f-9d72-0e880b72e29e)

**Comment by runhey** [comment]
我昨天也注意到了
