### ISSUE TITLE
仅有page switch而没有任何click指令

### ISSUE THREAD

**Issue by Serre3264** [runhey/OnmyojiAutoScript#131]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [x] 我使用 OAS 最新版

### 描述你的问题

1.启动之后，oas会仅仅下达page switch的指令，但是没有下达任何click指令，一段时间后会自动跳出
2.譬如：page switch:page main->page mall
              .....
              page switch:page main->page mall
              wait too long
              waiting for set

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

图像识别功能出现了malfunction（

### 相关 Logs

```Text
Page switch:page main->page mall
Page switch:page main->page mall
Page switch:page main->page mall
Page switch:page main->page mall
Page switch:page main->page mall
Page switch:page main->page mall
Wait too long
Waiting for set
```

### 截图

![image](https://github.com/runhey/OnmyojiAutoScript/assets/148740288/2aef7375-c20e-411f-87f6-6caae1c91c80)

### 还有别的吗？

无

**Comment by runhey** [comment]
1. 截图你的整个庭院， 要1280x720 的
2. 尝试手动点击一次商店看看是否可以程序跑下去

**Comment by Serre3264** [comment]
> 1. 截图你的整个庭院， 要1280x720 的
> 2. 尝试手动点击一次商店看看是否可以程序跑下去

![image](https://github.com/runhey/OnmyojiAutoScript/assets/148740288/d29ced48-810f-4ac1-a73e-75f81a22d533)

另外，在进入觉醒副本时也出现了基本相仿的问题，所以基本可以确定我的图像识别出现了一些问题

**Comment by Serre3264** [comment]
> 1. 截图你的整个庭院， 要1280x720 的
> 2. 尝试手动点击一次商店看看是否可以程序跑下去

手动点击商店后程序跑下去了

**Comment by runhey** [comment]
是游戏截图，分辨率1280x720,  记得马赛克你的ID

**Comment by Serre3264** [comment]
> 是游戏截图，分辨率1280x720, 记得马赛克你的ID

![image](https://github.com/runhey/OnmyojiAutoScript/assets/148740288/ff53fd4a-7559-4215-9580-48576164838e)
如图所示。
目前我使用的截图方式为adb，控制方案为adb

**Comment by runhey** [comment]
![hunt](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/9971b9a7-531e-4655-900d-179328c0f077)
这两个招财猫不一样

**Comment by Serre3264** [comment]
> ![hunt](https://user-images.githubusercontent.com/74492025/277332047-9971b9a7-531e-4655-900d-179328c0f077.png) 这两个招财猫不一样

绷 我在打觉醒副本的时候也出现了问题 找不到觉醒副本的按钮
之前用的时候，寮按钮也找不到

**Comment by runhey** [comment]
觉醒切到dev 分支  ，https://github.com/runhey/OnmyojiAutoScript/commit/416cb44b446acdd9bd3b85413c112fd0653d6154

**Comment by runhey** [comment]
等着我们更新，或者是提一个pr

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/95341e45-f5eb-47c5-8842-720e2d92a9ee)
