### ISSUE TITLE
实例无法二次打开

### ISSUE THREAD

**Issue by 1027676096** [runhey/OnmyojiAutoScript#135]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 最新版

### 描述你的问题

在第二次打开左侧添加过的实例时，会出现错误导致无法获取任务。

### 如何复现

1. 前往 左侧实例，添加一个实例并按照说明进行配置
2. 重启oas
3. 再次点击配置过的实例
4. 出现问题，导致无法获取脚本

**Comment by runhey** [comment]
手动打开你的配置文件，修改 `script`/ 'device' / 'screenshot_method'  选一个
```
ADB、ADB_nc、uiautomator2、Droidcast、Droidcast_raw、window_background
```

**Comment by 1027676096** [comment]
您好，请问能说的详细一点吗。
请问是修改这个路径下的文件吗？
C:\Users\10276\Desktop\OnmyojiAutoScript-easy-install\module\device

**Comment by runhey** [comment]
在./config/xxx.json的配置
等价于这个
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/d4305d82-488a-4c5c-b4d4-6724d61e28f6)

**Comment by 1027676096** [comment]
非常感谢
