### ISSUE TITLE
启动oas.exe进行初次安装时出现错误

### ISSUE THREAD

**Issue by Jmaster999** [runhey/OnmyojiAutoScript#149]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 最新版

### 描述你的问题

![1](https://github.com/runhey/OnmyojiAutoScript/assets/84021182/46e44333-bcb2-4b8b-bed3-105498b45157)
我在进行初次安装的时候，无法顺利的完成安装
我不太清楚这个报错是哪里出现了问题，我在翻了所有问题文档和issues，同时确保config/deploy.yaml中的内容不存在问题之后都没有找到解决方案，请帮帮我，谢谢

### 截图

![1](https://github.com/runhey/OnmyojiAutoScript/assets/84021182/33488005-67eb-4512-a264-1017141c7aa0)

**Comment by runhey** [comment]
你安装的时候开启模拟器了吗

**Comment by runhey** [comment]
貌似是装小黄车的时候挂了

**Comment by runhey** [comment]
你可以尝试比较硬核点的启动方式，更目录下有一个`console.abt` 点击进入 输入
```
python server.py
```
或是
```
python gui.py
```
分别对应新旧两个版本的启动

**Comment by runhey** [comment]
console.abt 拼错了 console.bat

**Comment by Jmaster999** [comment]
> 你可以尝试比较硬核点的启动方式，更目录下有一个`console.abt` 点击进入 输入
> 
> ```
> python server.py
> ```
> 
> 或是
> 
> ```
> python gui.py
> ```
> 
> 分别对应新旧两个版本的启动

感谢回复，我在安装时开启了模拟器，使用的是MuMu12
==============================
模拟器内存在小黄车，一个叫ATX的APP，但是我不清楚该如何使用它
![2](https://github.com/runhey/OnmyojiAutoScript/assets/84021182/26dc27ac-5cbe-46ec-8126-1f574f5d354d)
==============================
我尝试了硬核的启动方式
两种命令我都试过，结果如下图
第二种可以打开OAS的图形界面，但是我用OASX去连接时连不上
![1](https://github.com/runhey/OnmyojiAutoScript/assets/84021182/8f9d8b07-89c9-458e-9dce-993070c3a9b3)

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/1e4a67f1-e695-4e87-954a-7ac8fbc0cf53)

**Comment by Jmaster999** [comment]
> ![image](https://private-user-images.githubusercontent.com/74492025/289348613-1e4a67f1-e695-4e87-954a-7ac8fbc0cf53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMDQyMTUsIm5iZiI6MTcwMjIwMzkxNSwicGF0aCI6Ii83NDQ5MjAyNS8yODkzNDg2MTMtMWU0YTY3ZjEtZTY5NS00ZTg3LTk1NGEtN2FjOGZiYzBjZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEwMjUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjNTliOTcwMjBjYzhlMzhkYWUzNTBhZjQyNDU1YjkwMGUzMGRiOGZlM2MyMWRmZGEwNzc0NjZiOGEyN2MwODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PGGLJYB0tG8Y1yNb7K6wqntxkgA9UuXqnsbuqXX1XrU)

感谢，可以正常使用了

**Comment by runhey** [comment]
不客气
