### ISSUE TITLE
强烈建议添加mac版的客户端!

### ISSUE THREAD

**Issue by haodedong** [runhey/OnmyojiAutoScript#150]
### 当前不足

作者您好,首先非常感谢你们开发了这个工具,减少了阴阳师们的肝度,在此表示感谢~.
我这边使用的是mac m1电脑,直接在apple store中下载的阴阳师.(注明：m芯片的电脑无法安装mumu模拟器)
我希望添加mac版的客户端! 深表感谢~

### 解决方案

强烈建议添加mac版的客户端!

**Comment by runhey** [comment]
你是说桌面版吗，不太行。这个是基于模拟器的。你可以尝试找找有什么其他模拟器可以安装上去，再去适配
