### ISSUE TITLE
合区后进入游戏会出现选人界面，不会自动点击进入游戏造成卡画面，希望修复一下

### ISSUE THREAD

**Issue by SwrodKing** [runhey/OnmyojiAutoScript#154]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 最新版

### 描述你的问题

![PixPin_2023-12-23_21-22-14](https://github.com/runhey/OnmyojiAutoScript/assets/53303023/c9775db3-80ce-4700-9bfd-d4eee9e76263)
合区后进入游戏会出现选人界面，这里不会自动点击进入游戏造成卡画面，希望修复一下

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![PixPin_2023-12-23_21-22-14](https://github.com/runhey/OnmyojiAutoScript/assets/53303023/ab4fbcc4-5c9f-4264-8d31-ebdfe0e2756f)

**Comment by runhey** [comment]
更到dev了
