### ISSUE TITLE
OAS最新版本打开闪退

### ISSUE THREAD

**Issue by fushengruomengs** [runhey/OnmyojiAutoScript#159]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 最新版

### 描述你的问题

我下载了最新版本的Windows OAS安装包，解压安装之后直接闪退，目前不知道是环境问题还是我操作的问题，我这边使用了两台电脑都是这种情况，任务管理器也没找到后台OAS运行的痕迹，可否看看是不是安装包有问题,谢谢

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by fushengruomengs** [comment]
点击OAS.exe文件，用管理员方式运行和使用oas_backend.bat可执行文件进行打开，都不可以使用

**Comment by runhey** [comment]
同这个操作吗？https://github.com/runhey/OnmyojiAutoScript/issues/149

**Comment by fushengruomengs** [comment]
> 同这个操作吗？#149

没错，是这个问题，目前按照您这边给出的方案，已经解决了，非常感谢！！！
