### ISSUE TITLE
当前小规划

### ISSUE THREAD

**Issue by runhey** [runhey/OnmyojiAutoScript#16]
# 框架相关
**[并未完全迁移 Alas 框架]**
1. 完善UI逻辑
2. 增加 FIFO 以及 基于priority 的任务调度选择，从 Alas 迁移过来的貌似并不能很好满足
3. 优化异常处理
4. 模拟器适配（优先级不高）
5. ocr文字检测貌似花费较多时间，尝试使用opencv方式实现定位
6.模拟器启停

# 游戏组件复用
1. 通用战斗:  实现启停加成
2. 突发事件检测：协作、网络异常，【庭院】客户端清理（欢迎补充）
3. 选项列表拖动选择【runhey】(building)
4. 游戏启停
5. 通用邀请队友【基于ocr识别队友名】

# 任务
1. 结界寄养：功能需求。结界寄养和结界收卡貌似可以分为两个任务（待讨论），使用过滤器"xx > yy >>zz"来设置寄养的优先级
2. 御魂挖土：【用户选项】，队长还是队员，野队还是固定的，buff打开关闭，邀请队友，建立中任务退出选项（软时间：时间到了就可以退出挖土，或者是固定次数退出）
3. 困28：这我不熟，资源太多不配肝狗粮
4. 器灵：在观望一会？那天策划又改什么
5. sp小路男活动

**Comment by TwilightKHQ** [comment]
补充一点突发事件：登录.用户协议更新、庭院.新服务上线、庭院.新式神上线、服务器.断开连接、服务器.他端登录、御魂.数量上限

**Comment by runhey** [comment]
哇哦，这么多
这些[登录.用户协议更新、庭院.新服务上线、庭院.新式神上线]  貌似是登录的时候才是会出现，可以留给登录模块
他端登录----我总感觉，既然是用户手动的关闭脚本作业，那就不应该让脚本自我纠正，可以不实现等待脚本异常报错。
