### ISSUE TITLE
双开刷御魂时两个号都在反复点击打开御魂加成的那个图标，导致触发GameTooManyClickError异常

### ISSUE THREAD

**Issue by BigQdd** [runhey/OnmyojiAutoScript#164]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 最新版

### 描述你的问题

反复尝试了多种截图方案和控制方案，前一天晚上发现此项目，当天晚上可以双开刷御魂，第二天不知道为什么就不行了，折腾了很久。单号刷也不行，如果选择不开御魂加成的话，leader号会卡在邀请队友的界面（具体情况是打开邀请队友面板，但是在没有点击好友的情况下又会取消面板）

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现

### 预期行为

能正常刷御魂

### 相关 Logs

```Text
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── OROCHI ────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
2024-01-08 00:35:12.190 |     INFO | [u2.Device]                                
Device(atx_agent_url=http://127.0.0.1:2719)                                     
2024-01-08 00:35:12.908 |     INFO | [Screen_size] 1280x720                     
2024-01-08 00:35:12.911 |     INFO | module_path:                               
E:\BrowserDownload\OnmyojiAutoScript-easy-install\tasks\Orochi\script_task.py,  
module_name: script_task                                                        
2024-01-08 00:35:13.771 |     INFO | UI get current page                        
2024-01-08 00:35:13.776 |     INFO | [UI] page_main                             
2024-01-08 00:35:13.778 |     INFO | <<< UI GOTO PAGE_MAIN >>>                  
2024-01-08 00:35:13.784 |     INFO | Page arrive: page_main                     
2024-01-08 00:35:13.786 |     INFO | Open buff                                  
2024-01-08 00:35:14.505 |     INFO | Click ( 368,   71) @ GB_BUFF_1             
2024-01-08 00:35:14.507 |     INFO | <<< MINITOUCH INIT >>>                     
2024-01-08 00:35:14.523 |     INFO | [Device Orientation] 1 (HOME key on the    
right)                                                                          
2024-01-08 00:35:14.526 |     INFO | Reuse forward:                             
ForwardItem(serial='127.0.0.1:16416', local='tcp:20709',                        
remote='localabstract:minitouch')                                               
2024-01-08 00:35:14.531 |     INFO | v 1                                        
2024-01-08 00:35:14.533 |     INFO | ^ 10 720 1280 0                            
2024-01-08 00:35:14.536 |     INFO | $ 3280                                     
2024-01-08 00:35:14.538 |     INFO | minitouch running on port: 20709, pid: 3280
2024-01-08 00:35:14.540 |     INFO | max_contact: 10; max_x: 720; max_y: 1280;  
max_pressure: 0                                                                 
2024-01-08 00:35:16.728 |     INFO | Click ( 381,   63) @ GB_BUFF_1             
2024-01-08 00:35:19.047 |     INFO | Click ( 385,   70) @ GB_BUFF_1             
2024-01-08 00:35:21.066 |     INFO | Click ( 385,   42) @ GB_BUFF_1             
2024-01-08 00:35:23.155 |     INFO | Click ( 375,   55) @ GB_BUFF_1             
2024-01-08 00:35:25.301 |     INFO | Click ( 381,   69) @ GB_BUFF_1             
2024-01-08 00:35:27.438 |     INFO | Click ( 372,   39) @ GB_BUFF_1             
2024-01-08 00:35:29.524 |     INFO | Click ( 379,   45) @ GB_BUFF_1             
2024-01-08 00:35:31.956 |     INFO | Click ( 372,   59) @ GB_BUFF_1             
2024-01-08 00:35:34.585 |     INFO | Click ( 391,   38) @ GB_BUFF_1             
2024-01-08 00:35:36.730 |     INFO | Click ( 370,   35) @ GB_BUFF_1             
2024-01-08 00:35:38.746 |  WARNING | Too many click for a button: GB_BUFF_1     
2024-01-08 00:35:38.749 |  WARNING | History click: ['GB_BUFF_1', 'GB_BUFF_1',  
'GB_BUFF_1', 'GB_BUFF_1', 'GB_BUFF_1', 'GB_BUFF_1', 'GB_BUFF_1', 'GB_BUFF_1',   
'GB_BUFF_1', 'GB_BUFF_1', 'GB_BUFF_1', 'GB_BUFF_1']                             
2024-01-08 00:35:38.753 |    ERROR | GameTooManyClickError: Too many click for a
button: GB_BUFF_1                                                               
2024-01-08 00:35:38.757 |  WARNING | Saving error: ./log/error/1704645338757
```

### 截图

![2024-01-08_00-35-38-745414](https://github.com/runhey/OnmyojiAutoScript/assets/48794466/f694f233-773e-4cc6-9d7a-46f46470f658)

### 还有别的吗？

![无标题](https://github.com/runhey/OnmyojiAutoScript/assets/48794466/1cde29c9-3b16-4f36-8074-5f1813a0c122)
Deploy:
  Git:
    # URL of AzurLaneAutoScript repository
    # [CN user] Use 'https://gitee.com/lmeszinc/azur-lane-auto-script-mirror' for faster and more stable download
    # [Other] Use 'https://github.com/LmeSzinc/AzurLaneAutoScript'
    Repository: https://e.coding.net/onmyojiautoscript/oas/OnmyojiAutoScript.git
    # Branch of Alas
    # [Developer] Use 'dev', 'app', etc, to try new features
    # [Other] Use 'master', the stable branch
    Branch: master
    # Filepath of git executable `git.exe`
    # [Easy installer] Use './toolkit/Git/mingw64/bin/git.exe'
    # [Other] Use you own git
    GitExecutable: ./toolkit/Git/mingw64/bin/git.exe
    # Set git proxy
    # [CN user] Use your local http proxy (http://127.0.0.1:{port}) or socks5 proxy (socks5://127.0.0.1:{port})
    # [Other] Use null
    GitProxy: null
    # Update Alas at startup
    # [In most cases] Use true
    AutoUpdate: true
    # Whether to keep local changes during update
    # User settings, logs and screenshots will be kept, no mather this is true or false
    # [Developer] Use true, if you modified the code
    # [Other] Use false
    KeepLocalChanges: false

  Python:
    # Filepath of python executable `python.exe`
    # [Easy installer] Use './toolkit/python.exe'
    # [Other] Use you own python, and its version should be 3.7.6 64bit
    PythonExecutable: ./toolkit/python.exe
    # URL of pypi mirror
    # [CN user] Use 'https://pypi.tuna.tsinghua.edu.cn/simple' for faster and more stable download
    # [Other] Use null
    PypiMirror: https://pypi.tuna.tsinghua.edu.cn/simple
    # Install dependencies at startup
    # [In most cases] Use true
    InstallDependencies: true
    # Path to requirements.txt
    # [In most cases] Use 'requirements.txt'
    # [In AidLux] Use './deploy/AidLux/{version}/requirements.txt', version is default to 0.92
    RequirementsFile: requirements.txt

  Adb:
    # Filepath of ADB executable `adb.exe`
    # [Easy installer] Use './toolkit/Lib/site-packages/adbutils/binaries/adb.exe'
    # [Other] Use you own latest ADB, but not the ADB in your emulator
    AdbExecutable: ./toolkit/Lib/site-packages/adbutils/binaries/adb.exe
    # Whether to replace ADB
    # Chinese emulators (NoxPlayer, LDPlayer, MemuPlayer, MuMuPlayer) use their own ADB, instead of the latest.
    # Different ADB servers will terminate each other at startup, resulting in disconnection.
    # For compatibility, we have to replace them all.
    # This will do:
    #   1. Terminate current ADB server
    #   2. Rename ADB from all emulators to *.bak and replace them by the AdbExecutable set above
    #   3. Brute-force connect to all available emulator instances
    # [In most cases] Use true
    # [In few cases] Use false, if you have other programs using ADB.
    ReplaceAdb: true
    # Brute-force connect to all available emulator instances
    # [In most cases] Use true
    AutoConnect: true
    # Re-install uiautomator2
    # [In most cases] Use true
    InstallUiautomator2: true

  Ocr:
    # Run Ocr as a service, can reduce memory usage by not import mxnet everytime you start an alas instance

    # Whether to use ocr server
    # [Default] false
    UseOcrServer: false
    # Whether to start ocr server when start GUI
    # [Default] false
    StartOcrServer: false
    # Port of ocr server runs by GUI
    # [Default] 22268
    OcrServerPort: 22268
    # Address of ocr server for alas instance to connect
    # [Default] 127.0.0.1:22268
    OcrClientAddress: 127.0.0.1:22268

  Update:
    # Use auto update and builtin updater feature
    # This may cause problem https://github.com/LmeSzinc/AzurLaneAutoScript/issues/876
    EnableReload: true
    # Check update every X minute
    # [Disable] 0
    # [Default] 5
    CheckUpdateInterval: 5
    # Scheduled restart time
    # If there are updates, Alas will automatically restart and update at this time every day
    # and run all alas instances that running before restarted
    # [Disable] null
    # [Default] 03:50
    AutoRestartTime: 03:50

  Misc:
    # Enable discord rich presence
    DiscordRichPresence: false

  RemoteAccess:
    # Enable remote access (using ssh reverse tunnel serve by https://github.com/wang0618/localshare)
    # ! You need to set Password below to enable remote access since everyone can access to your alas if they have your url.
    # See here (http://app.azurlane.cloud/en.html) for more infomation.
    EnableRemoteAccess: false
    # Username when login into ssh server
    # [Default] null (will generate a random one when startup)
    SSHUser: null
    # Server to connect
    # [Default] null
    # [Format] host:port
    SSHServer: null
    # Filepath of SSH executable `ssh.exe`
    # [Default] ssh (find ssh in system PATH)
    # If you don't have one, install OpenSSH or download it here (https://github.com/PowerShell/Win32-OpenSSH/releases)
    SSHExecutable: ssh

  Webui:
    # --host. Host to listen
    # [Use IPv6] '::'
    # [In most cases] Default to '0.0.0.0'
    WebuiHost: 0.0.0.0
    # --port. Port to listen
    # You will be able to access webui via `http://{host}:{port}`
    # [In most cases] Default to 22267
    WebuiPort: 22288
    # Language to use on web ui
    # 'zh-CN' for Chinese simplified
    # 'en-US' for English
    # 'ja-JP' for Japanese
    # 'zh-TW' for Chinese traditional
    Language: zh-CN
    # Theme of web ui
    # 'default' for light theme
    # 'dark' for dark theme
    Theme: default
    # Follow system DPI scaling
    # [In most cases] true
    # [In few cases] false to make Alas smaller, if you have a low resolution but high DPI scaling.
    DpiScaling: true
    # --key. Password of web ui
    # Useful when expose Alas to the public network
    Password: null
    # --cdn. Use jsdelivr cdn for pywebio static files (css, js).
    # 'true' for jsdelivr cdn
    # 'false' for self host cdn (automatically)
    # 'https://path.to.your/cdn' to use custom cdn
    CDN: false
    # --run. Auto-run specified config when startup
    # 'null' default no specified config
    # '["alas"]' specified "alas" config
    # '["alas","alas2"]' specified "alas" "alas2" configs
    Run: null

**Comment by runhey** [comment]
你，加入了开发群，成为了一名开发者。
至少具备基本的素养是，找到对应的任务，然后debug。
这很显然是图片的识别不到，那大家都能跑通，那你应该考虑自己的电脑问题。
比如说，AMD的显卡锐化，什么什么的渲染的图片，或者你改了模拟器的什么操作，或者你游戏改了什么渲染。

**Comment by BigQdd** [comment]
抱歉，我是干java的不是特别了解python，最近也有点忙没怎么仔细看代码，今天晚上抽了点时间搞了一下，改了一点东西适配我的旧电脑

**Comment by liumc625** [comment]
这个问题我也遇到过,如果是mumu模拟器,解决方法是将模拟器渲染模式从OpenGL切换到Vulkan
