### ISSUE TITLE
斗技会停在主界面不动，报错点是在“分数”那一行。

### ISSUE THREAD

**Issue by youyeyao** [runhey/OnmyojiAutoScript#165]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 最新版

### 描述你的问题

“写在开头，已经试过自己查找解决办法，现有的历史问题也看完啦~”
报错是这样的
![1c679546d65b2e138ac7f5a680a4430](https://github.com/runhey/OnmyojiAutoScript/assets/89380126/58e938fe-1b0e-44bf-8fdf-20c81043722e)
在oas里找到了对应的代码位置（不确定是不是）
![61e1ad1cbe92974ac5031e84f19800b](https://github.com/runhey/OnmyojiAutoScript/assets/89380126/2e3dc785-63dc-413c-bc93-b153f716e4f7)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

希望大佬教教是哪里出现的问题，想知道该怎么改，因为过段时间斗技活动结束可能还要改一次。谢谢大佬~

### 截图

![1c679546d65b2e138ac7f5a680a4430](https://github.com/runhey/OnmyojiAutoScript/assets/89380126/803f74f6-a3ee-44e2-a08b-e18271ca99d7)
![61e1ad1cbe92974ac5031e84f19800b](https://github.com/runhey/OnmyojiAutoScript/assets/89380126/8a60e534-6aee-4e05-82dc-52d66e9a5dea)
![1167cb91c5cae771af7971aeda9ce25](https://github.com/runhey/OnmyojiAutoScript/assets/89380126/929d69b4-51cc-4f02-81a6-bbc63eb122a5)

**Comment by JJYYYE** [comment]
OASX怎么设置开发板呀，要是能设置可以自己改代码，OCR识别出的分数在1200~3000之间就会往下执行
 def check_score(self, target: int) -> int or None:
        """
        检查是否达到目标分数
        :param target: 目标分数
        :return:
        """
        while 1:
            self.screenshot()
            if self.appear(self.I_D_CELEB_STAR) or self.appear(self.I_D_CELEB_HONOR):
                logger.info('You are already a celeb')
                return None
            current_score = self.O_D_SCORE.ocr(self.device.image)
            if current_score < 1200 or current_score > 3000:
                continue
            return current_score if current_score <= target else None

**Comment by youyeyao** [comment]
> OASX怎么设置开发板呀，要是能设置可以自己改代码，OCR识别出的分数在1200~3000之间就会往下执行 def check_score(self, target: int) -> int or None: """ 检查是否达到目标分数 :param target: 目标分数 :return: """ while 1: self.screenshot() if self.appear(self.I_D_CELEB_STAR) or self.appear(self.I_D_CELEB_HONOR): logger.info('You are already a celeb') return None current_score = self.O_D_SCORE.ocr(self.device.image) if current_score < 1200 or current_score > 3000: continue return current_score if current_score <= target else None

大佬，是用这个替换截图里的那一行么？

**Comment by JJYYYE** [comment]
这个OASX改代码后重新启动会覆盖掉，没用的，OCR识别结果为0时，你可以尝试改 if current_score < 1200 or current_score > 3000:  这里，直接让current_score =等于 1200~3000之间

**Comment by runhey** [comment]
崽战斗鸡的，在一个新的分支duel。呱太没管过

**Comment by youyeyao** [comment]
> 崽战斗鸡的，在一个新的分支duel。呱太没管过
好der~蟹蟹大佬
