### ISSUE TITLE
困28无法进入

### ISSUE THREAD

**Issue by Aliaoreo** [runhey/OnmyojiAutoScript#173]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

卡在探索按钮这里进不去。怀疑是ui位置不对：比如我手动进入探索副本，脚本希望退出，但无法点击到取消键，最后自动重启了整个游戏，即不光【探索】点不进去，【返回】也点不到。但模拟器尺寸为提示的1280。
不清楚是否 与所用屏幕分辨率有关：2560*1440（但我使用【结界突破个人】功能又正常）
![image](https://github.com/runhey/OnmyojiAutoScript/assets/126145092/8978cc9e-47bc-4922-a766-88884f5c76a4)

### 如何复现

非常普通地运行就会出现问题。

### 相关 Logs
![image](https://github.com/runhey/OnmyojiAutoScript/assets/126145092/3218dc8a-bc70-4e1e-8898-3381102e25af)

### 截图

![image](https://github.com/runhey/OnmyojiAutoScript/assets/126145092/63413478-69e6-4479-a689-717726107f24)

**Comment by caopan45** [comment]
加1，我也是遇到这个问题

**Comment by PeanTuT** [comment]
把那个次数从all改成7次就能进，但是打完会卡在结算页面动不了

**Comment by fj3224013877** [comment]
同问题，会点击困28然后取消

**Comment by Daimeng2333** [comment]
加1

**Comment by ophappyx** [comment]
+1
