### ISSUE TITLE
🎈自定义庭院图片提供

### ISSUE THREAD

**Issue by Zxieyuan** [runhey/OnmyojiAutoScript#182]
### 描述

**烬夜韶阁**
![烬夜韶阁](https://github.com/runhey/OnmyojiAutoScript/assets/42534719/80685287-205d-4a71-93f0-e1f90a990d7e)

**笔墨山河**
![笔墨山河](https://github.com/runhey/OnmyojiAutoScript/assets/42534719/4961f905-c3d7-4029-9d70-471e36339bf1)

**枫色秋庭**
![枫色秋庭](https://github.com/runhey/OnmyojiAutoScript/assets/42534719/d23e6d6a-4edb-477f-aed2-c80637e20d4f)

**暖池青苑**
![暖池青苑](https://github.com/runhey/OnmyojiAutoScript/assets/42534719/afa9bbc2-e2fc-4a85-bf64-5621f3842bae)

**盛夏幽庭**
![盛夏幽庭](https://github.com/runhey/OnmyojiAutoScript/assets/42534719/ac7f17aa-e342-4bf5-a207-b6ddd394a660)

**远海航船**
![远海航船](https://github.com/runhey/OnmyojiAutoScript/assets/42534719/533e7b24-c4d1-4070-b3ca-3010bafd8101)

挺多的，还有四个庭院没解锁，其中有几个召唤会被小纸人挡住不知道有没有影响。人物都是默认停留位置。您先做一下第一个的吧，其他的您有空在添加上去，谢谢了！

**Comment by runhey** [comment]
‘烬夜韶阁’ 怎么没有悬赏封印

**Comment by Zxieyuan** [comment]
> ‘烬夜韶阁’ 怎么没有悬赏封印

得往右边划一下，默认位置是看不到悬赏封印的

**Comment by runhey** [comment]
> > ‘烬夜韶阁’ 怎么没有悬赏封印
> 
> 得往右边划一下，默认位置是看不到悬赏封印的

悬赏在右边？？不是默认左边吗，但是这样的话就不能执行悬赏任务了呀

**Comment by Zxieyuan** [comment]
> > > ‘烬夜韶阁’ 怎么没有悬赏封印
> > 
> > 
> > 得往右边划一下，默认位置是看不到悬赏封印的
> 
> 悬赏在右边？？不是默认左边吗，但是这样的话就不能执行悬赏任务了呀

对的对的，口误了。用这个庭院的时候悬赏任务能放弃执行吗，在页面里写个说明这个庭院无法执行悬赏

**Comment by huangyinhui520** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/139352112/fd92841d-01b6-4e4d-a3d8-ca2f9edccab1)
 天穹之境

**Comment by runhey** [comment]
> ![image](https://private-user-images.githubusercontent.com/139352112/300324444-fd92841d-01b6-4e4d-a3d8-ca2f9edccab1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NjEwNjQsIm5iZiI6MTcwNjg2MDc2NCwicGF0aCI6Ii8xMzkzNTIxMTIvMzAwMzI0NDQ0LWZkOTI4NDFkLTAxYjYtNGU0ZC1hM2Q4LWNhMmY5ZWRjY2FiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNzU5MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjcxYmE2YWNjNzkzYTM0Mzc4NTRjYmNkZWY3MzgyMjQ0NzliNGE0ZTBhODc0NWRjMGVlNmFhZDhlODE2ODA0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6aY7cgCzzU1XvXag6RzuIfwIu8Ti8yigBwzWXdy1r8U) 天穹之境

大哥你就不能自己开一个issue吗，而且你这图片，要的是1280x720的

**Comment by runhey** [comment]
更好了，我自己用了一段时间还不错。
宠物屋不可用：[暖池青苑]、[枫色秋庭]
哦对了除了远海航船，其他都没有测试条件

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/ebfcf795-ef09-4c1a-966a-2a850efe62c8)

**Comment by runhey** [comment]
给个回音呀

**Comment by Zxieyuan** [comment]
> 给个回音呀

来了来了，主要用的第一个，其他几个跑了一遍。都没发现什么大问题

**Comment by runhey** [comment]
第一个  烬夜韶阁 能跑悬赏吗

**Comment by Zxieyuan** [comment]
> 第一个 烬夜韶阁 能跑悬赏吗

可以的，人物走了一步然后自动点击悬赏了

**Comment by runhey** [comment]
好

**Comment by rwerplus** [comment]
请问下我想自定义庭院皮肤，在哪里可以添加配置

**Comment by Zxieyuan** [comment]
> 请问下我想自定义庭院皮肤，在哪里可以添加配置

#180

**Comment by rwerplus** [comment]
我看了下，目前没有写战斗主题的合并逻辑，不知道需要添加哪些图片
