### ISSUE TITLE
✨ [探索] 组队功能

### ISSUE THREAD

**Issue by JarediKey** [runhey/OnmyojiAutoScript#193]
### 当前不足

目前常驻最常用的玩法例如“御魂”和“觉醒”都有组队功能，希望“探索”也加入该功能。

优点如下：
1. 经验：组队+20%，好友再+10%
2. 方便保姆号给主号上三白蛋。
3. 丰年将至，减少肝度。

可能面临的难点：
1. 自动轮换的候补式神需要手动上以减少代码工作量。

**Comment by runhey** [comment]
https://github.com/runhey/OnmyojiAutoScript/commit/3a45418376a1430ef9805cba3b7d140300994466
