### ISSUE TITLE
安装教程链接失效 打不开

### ISSUE THREAD

**Issue by lookzm** [runhey/OnmyojiAutoScript#198]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

安装教程链接失效 打不开

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by runhey** [comment]
## 安装 Installation 

- 学习提问(https://runhey.github.io/OnmyojiAutoScript-website/docs/user-manual/scientific-question): 最基本的要求，**必看必学必会**
- 用户手册(https://runhey.github.io/OnmyojiAutoScript-website/docs/user-manual/getting-started): 在线手册，不定期更新，包含所有使用说明
- 安装教程(https://runhey.github.io/OnmyojiAutoScript-website/docs/user-manual/installation): 保姆式安装手册,多翻翻有惊喜
- 开发文档(https://runhey.github.io/OnmyojiAutoScript-website/docs/development/preamble): 虽然迭代很多、年久失修，但入门开发必读，具体以源码为准

**Comment by lookzm** [comment]
> Reference in new issu

链接我知道 是打不开了 链接失效了 之前能打开的 是要挂梯子么

**Comment by runhey** [comment]
...
