### ISSUE TITLE
在打开oasx经常性出现网络错误

### ISSUE THREAD

**Issue by gitzqn** [runhey/OnmyojiAutoScript#201]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

我在使用fastgithub后及没使用fastgithub,点击login经常出现网络错误，显示如下：
错误代码: The connection errored: 远程计算机拒绝网络连接。This indicates an error which most likely cannot be solved by the library.| -1。
在打开deploy.yaml文件，将PypiMirror的地址改为其他，并保存和重启OAS，还是没有什么效果。
有时候能进oasx.

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

希望佬能帮帮我，周四能开，周五想挖狂骨打开不了

**Comment by gitzqn** [comment]
oasx点击login

**Comment by runhey** [comment]
oasx只是一个界面

**Comment by runhey** [comment]
我怎么感觉你分不清oas和oasx

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/f3847545-cec9-4573-8110-1d4b583df73c)

**Comment by runhey** [comment]
你是按照这个启动的吗，如果是点一下“服务启动日志”

**Comment by gitzqn** [comment]
可以了，佬，之前我没点edit就点login，现在明白了。谢谢

**Comment by runhey** [comment]
打开这个目录D:\yysomy\OAS\oass, 里面有oas.exe。执行，然后启动oasx，发来报错日志

**Comment by meah-rad** [comment]
OAS working directory:
ShellException(pwd, exitCode 1, workingDirectory: D:\yysomy\OAS\oass)
./toolkit/Lib/site-packages/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/pip/_vendor/requests/sessions.py trust_env already patched
./toolkit/Lib/site-packages/uiautomator2/init.py minicap_urls no need to patch
./toolkit/Lib/site-packages/uiautomator2/init.py appdir already patched
==================== SHOW DEPLOY CONFIG ====================
WebuiPort: 22288
Rest of the configs are the same as default
+---------------------------------------------------+
|                    UPDATE ALAS                    |
+---------------------------------------------------+
==================== GIT INIT ====================
"D:/yysomy/OAS/oass/toolkit/Git/mingw64/bin/git.exe" init
Reinitialized existing Git repository in D:/yysomy/OAS/oass/.git/
[ success ]
==================== SET GIT PROXY ====================
"D:/yysomy/OAS/oass/toolkit/Git/mingw64/bin/git.exe" config --local --unset http.proxy
[ allowed failure ], error_code: 5
"D:/yysomy/OAS/oass/toolkit/Git/mingw64/bin/git.exe" config --local --unset https.proxy
[ allowed failure ], error_code: 5
"D:/yysomy/OAS/oass/toolkit/Git/mingw64/bin/git.exe" config --local http.sslVerify false
[ success ]
==================== SET GIT REPOSITORY ====================
"D:/yysomy/OAS/oass/toolkit/Git/mingw64/bin/git.exe" remote set-url origin https://e.coding.net/onmyojiautoscript/oas/OnmyojiAutoScript.git
[ success ]
==================== FETCH REPOSITORY BRANCH ====================
"D:/yysomy/OAS/oass/toolkit/Git/mingw64/bin/git.exe" fetch origin master
[ success ]
==================== PULL REPOSITORY BRANCH ====================
"D:/yysomy/OAS/oass/toolkit/Git/mingw64/bin/git.exe" reset --hard origin/master
HEAD is now at 4b7d218 Merge pull request #231 from runhey/dev
[ success ]
"D:/yysomy/OAS/oass/toolkit/Git/mingw64/bin/git.exe" pull --ff-only origin master
Already up to date.
[ success ]
==================== SHOW VERSION ====================
"D:/yysomy/OAS/oass/toolkit/Git/mingw64/bin/git.exe" --no-pager log --no-merges -1
commit 6addc66fd5da9f3b04e3a6d033a02da2f3c73406
Author: ryland <2234044577@qq.com>
Date:   Mon Apr 22 22:49:05 2024 +0800
    perf(Hyakkiyakou): Optimize capture data
[ success ]
+----------------------------------------------------------+
|                    KILL EXISTING ALAS                    |
+----------------------------------------------------------+
==================== KILL OAS.EXE ====================
pywin32 not installed, skip
==================== KILL PYTHON.EXE ====================
pywin32 not installed, skip
==================== KILL PYTHONW.EXE ====================
pywin32 not installed, skip
+-----------------------------------------------------------+
|                    UPDATE DEPENDENCIES                    |
+-----------------------------------------------------------+
==================== CHECK PYTHON ====================
"D:/yysomy/OAS/oass/toolkit/python.exe" --version
Python 3.10.11
[ success ]
==================== UPDATE DEPENDENCIES ====================
"D:/yysomy/OAS/oass/toolkit/python.exe" -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn --disable-pip-version-check
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: adbutils==0.11.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 9)) (0.11.0)
Requirement already satisfied: anyio==3.7.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 10)) (3.7.1)
Requirement already satisfied: anytree==2.8.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 11)) (2.8.0)
Requirement already satisfied: apkutils2==1.0.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 12)) (1.0.0)
Requirement already satisfied: cached-property==1.5.2 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 13)) (1.5.2)
Requirement already satisfied: certifi==2023.11.17 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 14)) (2023.11.17)
Requirement already satisfied: cffi==1.16.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 15)) (1.16.0)
Requirement already satisfied: charset-normalizer==3.3.2 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 16)) (3.3.2)
Requirement already satisfied: cigam==0.0.3 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 17)) (0.0.3)
Requirement already satisfied: click==8.1.7 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 18)) (8.1.7)
Requirement already satisfied: colorama==0.4.6 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 19)) (0.4.6)
Requirement already satisfied: coloredlogs==15.0.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 20)) (15.0.1)
Requirement already satisfied: decorator==5.1.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 21)) (5.1.1)
Requirement already satisfied: deprecated==1.2.14 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 22)) (1.2.14)
Requirement already satisfied: deprecation==2.1.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 23)) (2.1.0)
Requirement already satisfied: exceptiongroup==1.2.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 24)) (1.2.0)
Requirement already satisfied: fastapi==0.104.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 25)) (0.104.1)
Requirement already satisfied: filelock==3.13.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 26)) (3.13.1)
Requirement already satisfied: flatbuffers==23.5.26 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 27)) (23.5.26)
Requirement already satisfied: future==0.18.3 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 28)) (0.18.3)
Requirement already satisfied: gevent==23.9.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 29)) (23.9.1)
Requirement already satisfied: greenlet==3.0.3 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 30)) (3.0.3)
Requirement already satisfied: h11==0.14.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 31)) (0.14.0)
Requirement already satisfied: humanfriendly==10.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 32)) (10.0)
Requirement already satisfied: idna==3.6 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 33)) (3.6)
Requirement already satisfied: inflection==0.5.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 34)) (0.5.1)
Requirement already satisfied: logzero==1.7.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 35)) (1.7.0)
Requirement already satisfied: lxml==5.0.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 36)) (5.0.0)
Requirement already satisfied: markdown-it-py==2.2.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 37)) (2.2.0)
Requirement already satisfied: mdurl==0.1.2 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 38)) (0.1.2)
Requirement already satisfied: mpmath==1.3.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 39)) (1.3.0)
Requirement already satisfied: msgpack==1.0.7 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 40)) (1.0.7)
Requirement already satisfied: numpy==1.24.3 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 41)) (1.24.3)
Requirement already satisfied: onepush==1.2.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 42)) (1.2.0)
Requirement already satisfied: onnxruntime==1.16.3 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 43)) (1.16.3)
Requirement already satisfied: opencv-python==4.7.0.72 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 44)) (4.7.0.72)
Requirement already satisfied: packaging==20.9 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 45)) (20.9)
Requirement already satisfied: paho-mqtt==1.6.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 46)) (1.6.1)
Requirement already satisfied: pillow==10.2.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 47)) (10.2.0)
Requirement already satisfied: ppocr-onnx==0.0.3.9 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 48)) (0.0.3.9)
Requirement already satisfied: progress==1.6 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 49)) (1.6)
Requirement already satisfied: protobuf==4.25.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 50)) (4.25.1)
Requirement already satisfied: py==1.11.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 51)) (1.11.0)
Requirement already satisfied: pyclipper==1.3.0.post5 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 52)) (1.3.0.post5)
Requirement already satisfied: pycparser==2.21 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 53)) (2.21)
Requirement already satisfied: pydantic==1.10.7 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 54)) (1.10.7)
Requirement already satisfied: pyelftools==0.30 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 55)) (0.30)
Requirement already satisfied: pygments==2.17.2 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 56)) (2.17.2)
Requirement already satisfied: pyparsing==3.1.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 57)) (3.1.1)
Requirement already satisfied: pyreadline3==3.4.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 58)) (3.4.1)
Requirement already satisfied: pywin32==306 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 59)) (306)
Requirement already satisfied: pyyaml==6.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 60)) (6.0)
Requirement already satisfied: pyzmq==25.1.2 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 61)) (25.1.2)
Requirement already satisfied: requests==2.31.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 62)) (2.31.0)
Requirement already satisfied: retry==0.9.2 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 63)) (0.9.2)
Requirement already satisfied: rich==13.3.5 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 64)) (13.3.5)
Requirement already satisfied: shapely==2.0.2 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 65)) (2.0.2)
Requirement already satisfied: six==1.16.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 66)) (1.16.0)
Requirement already satisfied: sniffio==1.3.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 67)) (1.3.0)
Requirement already satisfied: starlette==0.27.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 68)) (0.27.0)
Requirement already satisfied: sympy==1.12 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 69)) (1.12)
Requirement already satisfied: tqdm==4.65.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 70)) (4.65.0)
Requirement already satisfied: typing-extensions==4.9.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 71)) (4.9.0)
Requirement already satisfied: uiautomator2==2.16.17 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 72)) (2.16.17)
Requirement already satisfied: uiautomator2cache==0.3.0.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 73)) (0.3.0.1)
Requirement already satisfied: urllib3==2.1.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 74)) (2.1.0)
Requirement already satisfied: uvicorn==0.23.2 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 75)) (0.23.2)
Requirement already satisfied: websockets==11.0.3 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 76)) (11.0.3)
Requirement already satisfied: whichcraft==0.6.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 77)) (0.6.1)
Requirement already satisfied: wrapt==1.15.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 78)) (1.15.0)
Requirement already satisfied: xmltodict==0.13.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 79)) (0.13.0)
Requirement already satisfied: zerorpc==0.6.3 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 80)) (0.6.3)
Requirement already satisfied: zope-event==5.0 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 81)) (5.0)
Requirement already satisfied: zope-interface==6.1 in d:\yysomy\oas\oass\toolkit\lib\site-packages (from -r requirements.txt (line 82)) (6.1)
Requirement already satisfied: setuptools in d:\yysomy\oas\oass\toolkit\lib\site-packages (from zope-event==5.0->-r requirements.txt (line 81)) (65.5.0)
[ success ]
+---------------------------------------------------------+
|                    START ADB SERVICE                    |
+---------------------------------------------------------+
==================== REPLACE ADB ====================
Kill all known ADB
taskkill /f /im adb.exe >nul 2>nul
Error occurred when killing task adb.exe, return code 1
taskkill /f /im nox_adb.exe >nul 2>nul
Error occurred when killing task nox_adb.exe, return code 1
taskkill /f /im adb_server.exe >nul 2>nul
Error occurred when killing task adb_server.exe, return code 1
taskkill /f /im HD-Adb.exe >nul 2>nul
Error occurred when killing task HD-Adb.exe, return code 1
D:/yysomy/OAS/oass/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
Devices: []
D:/yysomy/OAS/oass/toolkit/Lib/site-packages/adbutils/binaries/adb.exe devices
Devices: []
==================== UIAUTOMATOR2 INIT ====================
ShellException(python -m deploy.installer, exitCode 1, workingDirectory: D:\yysomy\OAS\oass)
Start OAS
ShellException(taskkill /f /t /im pythonw.exe, exitCode 128, workingDirectory: D:\yysomy\OAS\oass)
═══════════════════════════════════════════════════════════════════════════════
------------------------------------ START ------------------------------------
═══════════════════════════════════════════════════════════════════════════════
INFO     2024-05-17 18:23:15.172 │ <<< LAUNCHER CONFIG >>>                     
INFO     2024-05-17 18:23:15.173 │ [Host] 0.0.0.0                              
INFO     2024-05-17 18:23:15.174 │ [Port] 22288                                
INFO     2024-05-17 18:23:15.175 │ [Reload] False                              
INFO     2024-05-17 18:23:15.509 │ OAS web service startup done                
INFO     2024-05-17 18:23:15.511 │ OAS web service shutdown done               
ShellException(.\toolkit\pythonw.exe server.py, exitCode 1, workingDirectory: D:\yysomy\OAS\oass)
这是在启动日志拿的，操作是按照流程走的。 log文件就是昨天发的那一部分。
我没看明白是哪里有问题，ADB吗？

**Comment by meah-rad** [comment]
> 打开这个目录D:\yysomy\OAS\oass, 里面有oas.exe。执行，然后启动oasx，发来报错日志

操作步骤是按这个来的。

**Comment by runhey** [comment]
### 1.你确定是这个的日志吗？？为什么我看到混着其他东西
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/b2f84c6e-d23f-4756-a8b2-7930be67a592)
### 2.你自己开一个issue很难吗，
### 3.你的模拟器开了吗

**Comment by meah-rad** [comment]
![屏幕截图 2024-05-17 185827](https://github.com/runhey/OnmyojiAutoScript/assets/109396380/27b8b0fe-8c8d-471d-9e96-de6cb6710825)
打开的界面是这样。

**Comment by meah-rad** [comment]
[2024-05-17_server.txt](https://github.com/runhey/OnmyojiAutoScript/files/15348048/2024-05-17_server.txt)
我在OAS目录能找到的log文件；如果有其它的 请告知

**Comment by runhey** [comment]
你这样就可以启动好了oas了

**Comment by meah-rad** [comment]
启动OASX里 oasx.exe ip和port 输入  文件设置的127.0.0.1:22268，报；文件里面IP设置改啥都是此类报警。
![屏幕截图 2024-05-17 190540](https://github.com/runhey/OnmyojiAutoScript/assets/109396380/d18344e7-e105-4cd7-96ac-a56d42a59724)

**Comment by meah-rad** [comment]
![屏幕截图 2024-05-17 190726](https://github.com/runhey/OnmyojiAutoScript/assets/109396380/4a7d144d-295f-4f89-8961-49c7a67f5675)
这两个报警 交替出现。 我本地网络是否有问题？ 环境是否需要配置？

**Comment by runhey** [comment]
你为什么要填22268

**Comment by meah-rad** [comment]
![屏幕截图 2024-05-17 191202](https://github.com/runhey/OnmyojiAutoScript/assets/109396380/d82b65f5-e31d-4a9b-9910-1c6be27e6a31)
she'z设置IP和port  不是这里吗

**Comment by meah-rad** [comment]
好吧 填了127.0.0.1:22288 进去了。 晕倒
