### ISSUE TITLE
当期爬塔（大佬help me）

### ISSUE THREAD

**Issue by nargil1** [runhey/OnmyojiAutoScript#208]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

请大佬帮忙看一下，我当期爬塔无法进入，一直卡在界面，我也依照教程设置了游戏，我试了issues中另一个人当期爬塔的问题解决方案，把branch改成dev，但还是无法进入，其他功能没问题，

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
| 13:45:23.126 | [Screen_size] 1280x720                                
INFO           | 13:45:23.131 | module_path:                                          
         E:\gua\oas\OnmyojiAutoScript-easy-install\OnmyojiAutoScript-easy-instal
         l\tasks\ActivityShikigami\script_task.py, module_name: script_task     
INFO           | 13:45:23.355 | UI get current page                                   
INFO           | 13:45:23.362 | [UI] page_main                                        
INFO           | 13:45:23.363 | <<< UI GOTO PAGE_MAIN >>>                             
INFO           | 13:45:23.366 | Page arrive: page_main                                
─────────────────────────────── ENTER SHIKIGAMI ────────────────────────────────
INFO           | 13:45:23.369 | ENTER SHIKIGAMI                                       
WARNING  | 13:46:23.314 | Wait too long                                         
WARNING  | 13:46:23.316 | Waiting for set()                                     
INFO           | 13:46:23.333 | [u2.Device]                                           
         Device(atx_agent_url=http://127.0.0.1:54610)                           
INFO           | 13:46:23.408 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
ERROR        | 13:46:23.411 | GameStuckError: Wait too long                         
WARNING  | 13:46:23.414 | Saving error: ./log/error/1709876783414               
WARNING  | 13:46:23.700 | Game stuck, com.netease.onmyoji.wyzymnqsd_cps will be 
         restarted in 10 seconds                                                
WARNING  | 13:46:23.702 | If you are playing by hand, please stop Alas          
INFO           | 13:46:23.703 | Notifier: OAS1                                        
INFO           | 13:46:23.704 | Task call: restart                                    
INFO           | 13:46:33.714 | Scheduler: End task `ActivityShikigami`               
INFO           | 13:46:33.721 | Pending tasks: ['Restart', 'ActivityShikigami']       
INFO           | 13:46:33.723 | [Task] Restart (Enable, 0, 2024-03-08 13:46:23)       
INFO           | 13:46:33.725 | Scheduler: Start task `Restart`
```

### 截图

![屏幕截图 2024-03-08 140039](https://github.com/runhey/OnmyojiAutoScript/assets/149282432/c47526af-c4d6-4076-92b4-097c0a3db7a4)

**Comment by nargil1** [comment]
这是没设置branch为dev而是master之前的日志
        | 14:02:06.410 | module_path:                                          
         E:\gua\oas\OnmyojiAutoScript-easy-install\OnmyojiAutoScript-easy-instal
         l\tasks\ActivityShikigami\script_task.py, module_name: script_task     
INFO           | 14:02:06.413 | UI get current page                                   
INFO           | 14:02:06.418 | [UI] page_main                                        
INFO           | 14:02:06.420 | <<< UI GOTO PAGE_MAIN >>>                             
INFO           | 14:02:06.424 | Page arrive: page_main                                
─────────────────────────────── ENTER SHIKIGAMI ────────────────────────────────
INFO           | 14:02:06.426 | ENTER SHIKIGAMI                                       
WARNING  | 14:03:06.301 | Wait too long                                         
WARNING  | 14:03:06.303 | Waiting for set()                                     
INFO           | 14:03:06.407 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
ERROR        | 14:03:06.408 | GameStuckError: Wait too long                         
WARNING  | 14:03:06.412 | Saving error: ./log/error/1709877786412               
WARNING  | 14:03:06.705 | Game stuck, com.netease.onmyoji.wyzymnqsd_cps will be 
         restarted in 10 seconds                                                
WARNING  | 14:03:06.707 | If you are playing by hand, please stop Alas          
INFO           | 14:03:06.709 | Notifier: OAS1                                        
INFO           | 14:03:06.710 | Task call: restart                                    
INFO           | 14:03:16.721 | Scheduler: End task `ActivityShikigami`               
INFO           | 14:03:16.731 | Pending tasks: ['Restart', 'ActivityShikigami']       
INFO           | 14:03:16.733 | [Task] Restart (Enable, 0, 2024-03-08 14:03:06)       
INFO           | 14:03:16.735 | Scheduler: Start task `Restart`

**Comment by nargil1** [comment]
这是相关截图，我没看源程序及相关图片识别原理，所以我觉得是否是活动入口和背景颜色相近冲突了，请大佬帮忙看一下，谢谢了
![2024-03-08_12-40-53-321240](https://github.com/runhey/OnmyojiAutoScript/assets/149282432/3def2034-b6ef-494d-a08d-45687dd40e3d)

**Comment by nargil1** [comment]
我又换了位置，重新配置了一遍，发现还是进不去，可能还是我服务器配置有问题，日志也没看出什么，希望大佬指点迷津

**Comment by runhey** [comment]
省流版：没人更

**Comment by nargil1** [comment]
谢谢大佬
