### ISSUE TITLE
探索任务检测突破卷，并唤起个人突破

### ISSUE THREAD

**Issue by pangpangjiang** [runhey/OnmyojiAutoScript#222]
### 当前不足

想获得阴阳师的勾玉每日比较重要的还是打个人突破，但是使用目前仅有的程序（突破循环后再进行个人突破，任务循环我一般设置一小时）这样的效率实在太低，还要顾及其他任务，一天打不了多少轮，效率有些低下

### 解决方案

建议实时截图查看突破卷，当<9时打开探索刷卷，探索结束之后
![微信图片_20240414212626](https://github.com/runhey/OnmyojiAutoScript/assets/166825505/faed9999-49d7-471d-8a68-6ca7191d7799)这个位置刚好可以看到有多少突破卷，从而进入下一步
继续探索或者结束去进行个人突破获得勾玉

**Comment by runhey** [comment]
很好的建议

**Comment by runhey** [comment]
你的描述并不清晰，我理解为两部分，一是探索唤起突破，二是突破唤起探索。无论如何这都直接绕过了本身的调度系统，这并不是很合适的操作。

**Comment by runhey** [comment]
所以可以选择给探索开一个小后门，而后者不给予考虑，更加合理的描述是在探索中新增一个配置项，awake_realmraid，为0时候不使用这一个功能，为[1~30]表示探索运行过程中检测突破卷数量，大于这个值将结束探索任务，而将突破任务设为当前

**Comment by YuuLong** [comment]
> 你的描述并不清晰，我理解为两部分，一是探索唤起突破，二是突破唤起探索。无论如何这都直接绕过了本身的调度系统，这并不是很合适的操作。

我的理解，大概是在执行其他任务的空档期开始探索。探索票满则跳转突破。也可以为其单独开一个混合探索和结界突破这两个任务的tasks。“肝勾玉”模式？

**Comment by pangpangjiang** [comment]
[仅供参考]
分享一下目前我的肝勾玉方式
探险间隔5秒一次，一次的话按默认的7次突破来算，任务优先级15
突破30分钟突破一次，任务优先级14
其他任务的话我安排任务优先级1-7左右
脚本设置最下面的优化设置（选择任务调度规则）选择“Priority”

**Comment by pangpangjiang** [comment]
分享一下目前我的肝勾玉方式
探险间隔5秒一次，一次的话按默认的7次突破来算，任务优先级15
突破30分钟突破一次，任务优先级14
其他任务的话我安排任务优先级1-7左右
脚本设置最下面的优化设置（选择任务调度规则）选择“Priority”
[仅供参考]
