### ISSUE TITLE
✨通知推送内容过于简单

### ISSUE THREAD

**Issue by yEs1do** [runhey/OnmyojiAutoScript#232]
### 当前不足

没有正在运行的任务名称

### 解决方案

已找到功能文件 .\module\notify\notify.py
希望可以在描述或标题中写明当前运行的任务，来判断是否需要人工干预。任务名称可翻译为中文。

**Comment by runhey** [comment]
英文到中文的翻译是在oasx端

**Comment by runhey** [comment]
添加了任务名在title里面

**Comment by yEs1do** [comment]
好哦！

**Comment by yEs1do** [comment]
> 添加了任务名在 title 里面

好哦！
测试了一下，配置名字后面曾经的“crashed”会变成任务名，太方便啦。
我说的翻译就是把“command”内容更改为中文，比如“Orochi”我知道是御魂八岐大蛇，但是“BondlingFairyland”对应契灵之境对我还是太难了……当然也不是啥必要的改动，见多了也就记住了。
