### ISSUE TITLE
✨寮突与悬赏封印一样，将凌晨时间完成的任务改为“今日”继续运行

### ISSUE THREAD

**Issue by yEs1do** [runhey/OnmyojiAutoScript#233]
### 当前不足

如果设置固定时间（比如 21 时）进行寮突，当前完成寮突的时间如果超过零点，会设置为后一天的 21 时（即跳过了一天）

### 解决方案

悬赏封印任务中有对时间的判定，可以加入判断，如果时间为 0-5 时，则重置为当天的时刻

**Comment by yunxi2367** [comment]
悬赏封印协助任务邀请好友改了UI，现在会卡在邀请好友的界面

**Comment by yEs1do** [comment]
https://github.com/runhey/OnmyojiAutoScript/pull/542
