### ISSUE TITLE
🎈看到大佬的作品被隔壁咸鱼的转载（大神）给转载还要收费我实在蚌埠住

### ISSUE THREAD

**Issue by pangpangjiang** [runhey/OnmyojiAutoScript#234]
### 描述

甚至收费70多块
![1ef7e7c36f5a12a2b3583a9da0c22f8](https://github.com/runhey/OnmyojiAutoScript/assets/166825505/8bc6dd7f-f12e-43ba-8e9a-2e03b3cfeb5a)
![8873cf2cba257e42b19c326d6dd67e5](https://github.com/runhey/OnmyojiAutoScript/assets/166825505/8e1d01e9-d10f-49d0-ab55-f0887de09ada)
![93f726b0e835e31b9aef852dc781460](https://github.com/runhey/OnmyojiAutoScript/assets/166825505/a3b1b1dd-deeb-41a1-b2fe-2a5fc4ad1dca)

**Comment by pangpangjiang** [comment]
算了，尊重他人命运，我还不是不多管闲事(惋惜

**Comment by runhey** [comment]
坏了，间谍身份暴露

**Comment by runhey** [comment]
这个有群吗

**Comment by runhey** [comment]
滴滴

**Comment by 52605016** [comment]
可以加个认证？之前用过断音需要加群，然后他会给你一个配置文件，没有这个文件启动脚本会自动删除。

**Comment by runhey** [comment]
治标不治本呀这样的话
