### ISSUE TITLE
从上游Alas同步设备相关

### ISSUE THREAD

**Issue by runhey** [runhey/OnmyojiAutoScript#244]
### 当前不足

同步新的截图方式

**Comment by xbj110825** [comment]
想要先同步/更新哪个截图方式呀，这两天有空看看

**Comment by runhey** [comment]
![e856623a4fd12638d34905b95f8d9250](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/6e21c49d-2f63-4c32-8a5a-99cc85b06669)

**Comment by runhey** [comment]
但是droidcast还是不行耶，droidcast_raw是可以的。貌似从地址拿到的图片是空的

**Comment by xbj110825** [comment]
我没有测试droidcast的场景，只测试了droidcast_raw，我看看，可能改漏了。

**Comment by xbj110825** [comment]
https://github.com/LmeSzinc/AzurLaneAutoScript/commit/69df0c26e4b2fde70f746d71549bafd8fa74ce3a
看上游似乎在去年9月，做了一次重构，底层只保留了DroidCast_raw.apk

**Comment by runhey** [comment]
噢那好吧，跟着

**Comment by runhey** [comment]
为什么我们没有这个东西还是能跑！
[bin/DroidCast/DroidCast_raw-release-1.0.apk](https://github.com/LmeSzinc/AzurLaneAutoScript/commit/69df0c26e4b2fde70f746d71549bafd8fa74ce3a#diff-204945eb623e8172d6ff5fac2552800b6f0b8ca23b8712d822af820a26a42194)

**Comment by xbj110825** [comment]
我们有DroidCastS-release-1.1.5.apk，我猜测这个和DroidCast_raw-release-1.0.apk很接近。我们有两个APK，一个是DroidCast，一个是DroidCast_raw。

**Comment by xbj110825** [comment]
用git直接来管理二进制文件就有这点不太好，不清楚这个二进制文件对应的源码在哪里，有没有做过什么改动。

**Comment by YuuLong** [comment]
> 用git直接来管理二进制文件就有这点不太好，不清楚这个二进制文件对应的源码在哪里，有没有做过什么改动。上游新增的那个apk，应该来自 https://github.com/Torther/DroidCast_raw/releases/download/v1.0/DroidCast_raw-release-1.0.apk 。DroidCastS-release-1.1.5.apk 这个搜了一下，感觉可能是自己编译的。

这个我之前了解了一下，首先回复你上述的问题，DroidCast_raw是在DroidCast的基础上重构的，相比原项目速度更快，所以在alas重构的时候就将DroidCast的调用也全部换成了DroidCast_raw。DroidCastS-release-1.1.5.apk这个包体是原有的DroidCastS的release包体，这个库后续更名为DroidCast_raw了，所以算是同源的

**Comment by YuuLong** [comment]
我这个端午如果放假的话，我先把DroidCast和DroidCast_raw这两个模式同步更新

**Comment by YuuLong** [comment]
> 用git直接来管理二进制文件就有这点不太好，不清楚这个二进制文件对应的源码在哪里，有没有做过什么改动。上游新增的那个apk，应该来自 https://github.com/Torther/DroidCast_raw/releases/download/v1.0/DroidCast_raw-release-1.0.apk 。DroidCastS-release-1.1.5.apk 这个搜了一下，感觉可能是自己编译的。

这个是原作者的github链接，https://github.com/Torther/DroidCastS 。点击跳转之后你可以看到他会自动跳转到https://github.com/Torther/DroidCast_raw 。
