### ISSUE TITLE
你好，我想请问一下。OAS如何自动更新或者手动更新呢？

### ISSUE THREAD

**Issue by vegetpig** [runhey/OnmyojiAutoScript#250]
### 描述

![微信截图_20240518182548](https://github.com/runhey/OnmyojiAutoScript/assets/115412285/0ff97888-1567-42a5-a087-ec50394b1eac)

> 
点击了更新器，弹出了一个命令行界面然后就没有了。后面点击手动更新报错了，麻烦有空的话帮我解答一下。谢谢！

**Comment by runhey** [comment]
结束oas服务，重启就可以了

**Comment by vegetpig** [comment]
你好，还是没有更新成功呢。结束后重启了

**Comment by runhey** [comment]
你的配置文件有吗

**Comment by runhey** [comment]
有oas的启动日志吗

**Comment by vegetpig** [comment]
[2024-05-19_server.txt](https://github.com/runhey/OnmyojiAutoScript/files/15367445/2024-05-19_server.txt)
大佬你好这个ok吗

**Comment by vegetpig** [comment]
> 你的配置文件有吗

配置文件是deploy.yaml吗

**Comment by runhey** [comment]
> > 你的配置文件有吗
> 
> 配置文件是deploy.yaml吗

对

**Comment by vegetpig** [comment]
> > > 你的配置文件有吗
> > 
> > 
> > 配置文件是deploy.yaml吗
> 
> 对

**Comment by vegetpig** [comment]
[deploy.zip](https://github.com/runhey/OnmyojiAutoScript/files/15367448/deploy.zip)


> > > 你的配置文件有吗
> > 
> > 
> > 配置文件是deploy.yaml吗
> 
> 对

[deploy.zip](https://github.com/runhey/OnmyojiAutoScript/files/15367449/deploy.zip)

**Comment by runhey** [comment]
```
2024-05-19 11:18:41.374 |     INFO | [ success ]                                
2024-05-19 11:18:41.599 |     INFO | New update available                       
2024-05-19 11:18:41.601 |     INFO | 00a36f98 - fix(KekkaiAction): Swipe to the end but no card is found          
```
看着是已经更新了

**Comment by vegetpig** [comment]
好的，那我就展示先不管了。谢谢大佬

**Comment by runhey** [comment]
打开文件夹，看看文件最近的修改时间，这个是很准确的
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/5f73f52b-26e0-4091-a972-2c9691ee70d2)

**Comment by vegetpig** [comment]
> 打开文件夹，看看文件最近的修改时间，这个是很准确的 ![image](https://private-user-images.githubusercontent.com/74492025/331845279-5f73f52b-26e0-4091-a972-2c9691ee70d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwODk5MDUsIm5iZiI6MTcxNjA4OTYwNSwicGF0aCI6Ii83NDQ5MjAyNS8zMzE4NDUyNzktNWY3M2Y1MmItMjZlMC00MDkxLWE5NzItMmM5NjkxZWU3MGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDAzMzMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMTRkZmJmYTUzM2U3N2U3MWE1NTM1MzUwYzI4ZWFjY2FkZmY1YmM3OTIzOTVmNzQ1MmQwYTZhYTVjMjRjODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XfXpWsaMz2TvEzfCUcxNmqwQo6t_yAoeEh1KRrivWfw)

大佬看看哪个文件的修改时间呢？

**Comment by runhey** [comment]
有个修改日期，看到最新的修改时间离今天近就可以了

**Comment by shityrone** [comment]
[2024-08-16_server.txt](https://github.com/user-attachments/files/16632590/2024-08-16_server.txt)
![deploy](https://github.com/user-attachments/assets/4baaa441-3bde-4634-bc51-5cb49b677493)

大佬您好，这是我的server文件，因为我按照这上面的操作核实，还是发现版本没更新，选择的分支也是dev，然后进入到oasx界面，发现百鬼选项还是英文的，这应该是没有更新成功吧。我退出服务之后也重启了，还是一样提示我版本为0.2.1，最新版本0.2.2

**Comment by shityrone** [comment]
您好，请问问题关闭了之后评论就无效了吗

**Comment by shityrone** [comment]
![更新](https://github.com/user-attachments/assets/d74651ae-32b5-4a82-912a-c889cdb88617)
佬您好，这是我点更新的界面
