### ISSUE TITLE
Some gui.py error on launch

### ISSUE THREAD

**Issue by KokeCacao** [runhey/OnmyojiAutoScript#257]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

# First Issue
On `SplitPanel.qml`,
```
function setDefalutConfig(name){
  contentDefalut.item.configName = name
}
```
gives error
```
TypeError: Value is null and could not be converted to an object
```

# Second Issue

On `MainWindow.qml`, line 90
```
notity.open()
```
gives error
```
ReferenceError: notity is nogt defined.
```

Apart from above error, I noticed many misspellings of words. Like... why `notity` instead of `notify` and `defalut` instead of `default`? It is really confusing and prone to error.

### 如何复现

1. run `python gui.py` on dev branch

### 预期行为

No error in the console. The program starts normally.

**Comment by runhey** [comment]
comment out it, line 90. this is my oversight

**Comment by runhey** [comment]
I can run normally. like
```
Connected to pydev debugger (build 232.10203.26)
═══════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ────────────────────────────────────
═══════════════════════════════════════════════════════════════════════════════
═══════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ────────────────────────────────────
═══════════════════════════════════════════════════════════════════════════════
INFO     2024-05-29 10:40:39.260 │ Update thread start                         
ERROR    2024-05-29 10:40:48.996 │ Update thread error:                        

Process finished with exit code 0
```

**Comment by KokeCacao** [comment]
> comment out it, line 90. this is my oversight

Yup. I did exactly that. Commenting `contentDefalut.item.configName = name` out also works, but I am not sure if I broke something by doing so. I don't have experience working with QML so I can't fix it myself.

**Comment by KokeCacao** [comment]
> contentDefalut.item.configName = name

Can you give me some context on what the following code is doing?

```
contentDefalut.item.configName = name
```

For example, what is `contentDefalut`. What's the type (a javascript object?)? Where is it initialized? What does it represent? I checked that `name` is `oas1` and is not null. Is `contentDefalut.item.configName` a dict access of a null object?

**Comment by runhey** [comment]
I've long forgotten how the qml works. I just remember it was messy when I wrote it. Don't recommend read gui.py but rather oasx.

**Comment by runhey** [comment]
Now, gui.py is only used to generate configuration information,  used to update image assets, likes "image.json".

**Comment by KokeCacao** [comment]
> Now, gui.py is only used to generate configuration information, used to update image assets, likes "image.json".

Yes. I do need to use it to take screenshots...

**Comment by runhey** [comment]
Is it working now? I archived a QML branch before using oasx. maybe you can try it.
