### ISSUE TITLE
无法添加任务

### ISSUE THREAD

**Issue by zhuxu1304** [runhey/OnmyojiAutoScript#26]
启用任务后在总览里的running，pending，waiting里面都没有。start以后无事发生

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/cf70b5f3-800e-461a-8e09-270f64f84fc4)
我昨天添加调度规则的时候，忘记了对原有的调度规则测试
已修复
