### ISSUE TITLE
🎈百鬼夜行

### ISSUE THREAD

**Issue by runhey** [runhey/OnmyojiAutoScript#269]
### 描述

这一部分主要是使用目标检测来识别式神，进而将信息输入决策模型来模拟控制，最终的目标是实现比人类更加智能地撒豆子。
子功能代码路径在`./tasks/Hyakkiyakou`, 分支hya
主要包括这四个部分组成
## 接入游戏 slave
针对实时性，需要这一部分提供专门的截屏和控制，要求10ms以内的截屏和50ms以内的点击
- [x] #270
- [x] #271
- [x] 主干任务流程，比如基本的邀请好友，点击开始，结束，退出这些
- [x] BUFF状态的检测，比如冰冻，好友概率，减速等等，要求就是快
- [x] #272

## 决策模型 agent
还没想好，利用所有信息进行决策，属于有记忆系统

## 跟踪器 tracker
模型已经训练好了， yolov10， 里面使用cython进行加速，包括preprocess和postprocess。
使用最经典的卡尔曼进行滤波，将会输出速度和位置，以及ID和置信度
- [ ] onnx量化到int8 ~不会
- [ ] 添加TensorRT部署方式，莫得空

## 辅助部分
- [x] 将每一帧的结果显示出来
- [x] 保存有意义的图片，用来回喂训练
- [x] 更多调试信息

**Comment by runhey** [comment]
| Label | Name | Label | Name | Label | Name | Label | Name|
|-----|-----|-----|-----|-----|-----|-----|-----|
| sp_001 | 少羽大天狗 | ssr_001 | 大天狗 | sr_001 | 桃花妖 | r_001 | 三尾狐 |
| sp_002 | 炼狱茨木童子 | ssr_002 | 酒吞童子 | sr_002 | 雪女 | r_002 | 座敷童子 |
| sp_003 | 稻荷神御馔津 | ssr_003 | 荒川之主 | sr_003 | 鬼使白 | r_003 | 鲤鱼精 |
| sp_004 | 苍风一目连 | ssr_004 | 阎魔 | sr_004 | 鬼使黑 | r_004 | 九命猫 |
| sp_005 | 赤影妖刀姬 | ssr_005 | 两面佛 | sr_005 | 孟婆 | r_005 | 狸猫 |
| sp_006 | 御怨般若 | ssr_006 | 小鹿男 | sr_006 | 犬神 | r_006 | 河童 |
| sp_007 | 骁浪荒川之主 | ssr_007 | 茨木童子 | sr_007 | 骨女 | r_007 | 童男 |
| sp_008 | 烬天玉澡前 | ssr_008 | 青行灯 | sr_008 | 鬼女红叶 | r_008 | 童女 |
| sp_009 | 鬼王酒吞童子 | ssr_009 | 妖刀姬 | sr_009 | 跳跳哥哥 | r_009 | 饿鬼 |
| sp_010 | 天剑韧心鬼切 | ssr_010 | 一目连 | sr_010 | 傀儡师 | r_010 | 巫师 |
| sp_011 | 聆海金鱼姬 | ssr_011 | 花鸟卷 | sr_011 | 海坊主 | r_011 | 鸦天狗 |
| sp_012 | 浮世青行灯 | ssr_012 | 辉夜姬 | sr_012 | 判官 | r_012 | 食发鬼 |
| sp_013 | 缚骨清姬 | ssr_013 | 荒 | sr_013 | 凤凰火 | r_013 | 武士之灵 |
| sp_014 | 待宵姑获鸟 | ssr_014 | 彼岸花 | sr_014 | 吸血姬 | r_014 | 雨女 |
| sp_015 | 麓铭大岳丸 | ssr_015 | 雪童子 | sr_015 | 妖狐 | r_015 | 跳跳弟弟 |
| sp_016 | 初翎山风 | ssr_016 | 山风 | sr_016 | 妖琴师 | r_016 | 跳跳妹妹 |
| sp_017 | 夜溟彼岸花 | ssr_017 | 玉澡前 | sr_017 | 食梦貘 | r_017 | 兵俑 |
| sp_018 | 蝉冰雪女 | ssr_018 | 御馔津 | sr_018 | 清姬 | r_018 | 丑时之女 |
| sp_019 | 空相面灵气 | ssr_019 | 面灵气 | sr_019 | 镰铀 | r_019 | 独眼小僧 |
| sp_020 | 绘世花鸟卷 | ssr_020 | 鬼切 | sr_020 | 姑获鸟 | r_020 | 铁鼠 |
| sp_021 | 因幡辉夜姬 | ssr_021 | 白藏主 | sr_021 | 二口女 | r_021 | 椒图 |
| sp_022 | 梦寻山兔 | ssr_022 | 八岐大蛇 | sr_022 | 白狼 | r_022 | 管狐 |
| sp_023 | 神堕八岐大蛇 | ssr_023 | 不知火 | sr_023 | 樱花妖 | r_023 | 山兔 |
| sp_024 | 大夜摩天阎魔 | ssr_024 | 大岳丸 | sr_024 | 惠比寿 | r_024 | 萤草 |
| sp_025 | 心狩鬼女红叶 | ssr_025 | 泷夜叉姬 | sr_025 | 络新妇 | r_025 | 蝴蝶精 |
| sp_026 | 神启荒 | ssr_026 | 云外镜 | sr_026 | 般若 | r_026 | 山童 |
| sp_027 | 禅心云外镜 | ssr_027 | 鬼童丸 | sr_027 | 青坊主 | r_027 | 首无 |
| sp_028 | 流光追月神 | ssr_028 | 缘结神 | sr_028 | 万年竹 | r_028 | 觉 |
| sp_029 | 修罗鬼童丸 | ssr_029 | 铃鹿御前 | sr_029 | 夜叉 | r_029 | 青蛙瓷器 |
| sp_030 | 寻森小鹿男 | ssr_030 | 紧那罗 | sr_030 | 黑童子 | r_030 | 古笼火 |
| sp_031 | 纺愿缘结神 | ssr_031 | 千姬 | sr_031 | 白童子 | r_031 | 免丸 |
| sp_032 | 渺念萤草 | ssr_032 | 帝释天 | sr_032 | 烟烟罗 | r_032 | 数珠 |
| sp_033 | 本真三尾狐 | ssr_033 | 阿修罗 | sr_033 | 金鱼姬 | r_033 | 小袖之手 |
| sp_034 | 鲸汐千姬 | ssr_034 | 食灵 | sr_034 | 档鸩 | r_034 | 电师 |
| sp_035 | 福悦座敷童子 | ssr_035 | 饭筒 | sr_035 | 以津真天 | r_035 | 天井下 |
|  |   | ssr_036 | 铃彦姬 | sr_036 | 匣中少女 | r_036 | 垢尝 |
|  |   | ssr_037 | 不见岳 | sr_037 | 小松丸 | r_037 | 影鳄 |
|  |   | ssr_038 | 须佐之男 | sr_038 | 书翁 | n_001 | 灯笼鬼 |
|  |   | ssr_039 | 寻香行 | sr_039 | 百目鬼 | n_002 | 提灯小僧 |
|  |   | ssr_040 | 季 | sr_040 | 追月神 | n_003 | 赤舌 |
|  |   | ssr_041 | 月读 | sr_041 | 日和坊 | n_004 | 盗墓小鬼 |
|  |   | ssr_042 | 言灵 | sr_042 | 熏 | n_005 | 寄生魂 |
|  |   | ssr_043 | 孔雀明王 | sr_043 | 奕 | n_006 | 唐纸伞妖 |
|  |   | ssr_044 | 天照 | sr_044 | 猫掌柜 | n_007 | 天邪鬼绿 |
|  |   | ssr_045 | 伊邪那美 | sr_045 | 人面树 | n_008 | 天邪鬼赤 |
|  |   | ssr_046 | 泷 | sr_046 | 於菊虫 | n_009 | 天邪鬼黄 |
|  |   |  |   | sr_047 | 一反木绵 | n_010 | 天邪鬼青 |
|  |   |  |   | sr_048 | 入殓师 | n_011 | 帚神 |
|  |   |  |   | sr_049 | 化鲸 | n_012 | 涂壁 |
|  |   |  |   | sr_050 | 海忍 | g_001 | 大天狗呱 |
|  |   |  |   | sr_051 | 久次良 | g_002 | 酒吞呱 |
|  |   |  |   | sr_052 | 蟹姬 | g_003 | 荒川呱 |
|  |   |  |   | sr_053 | 纸舞 | g_004 | 阎魔呱 |
|  |   |  |   | sr_054 | 星熊童子 | g_005 | 两面佛呱 |
|  |   |  |   | sr_055 | 风狸 | g_006 | 小鹿男呱 |
|  |   |  |   | sr_056 | 蝎女 | g_007 | 茨木呱 |
|  |   |  |   | sr_057 | 入内雀 | g_008 | 青行灯呱 |
|  |   |  |   | sr_058 | 怡细工 | g_009 | 妖刀姬呱 |
|  |   |  |   | sr_059 | 川猿 | g_010 | 一目连呱 |
|  |   |  |   | sr_060 | 迦楼罗 | g_011 | 花鸟卷呱 |
|  |   |  |   | sr_061 | 灵海蝶 | g_012 | 辉夜姬呱 |
|  |   |  |   | sr_062 | 粉婆婆 | g_013 | 荒呱 |
|  |   |  |   | sr_063 | 天逆每 | g_014 | 彼岸花呱 |
|  |   |  |   | sr_064 | 慧明灯 | g_015 | 雪童子呱 |
|  |   |  |   | sr_065 | 盗人神 | g_016 | 玉藻前呱 |
|  |   |  |   |  |   | g_017 | 御馒津呱 |

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/aebf321d-e580-4e4e-90ae-bd8d86380589)
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/da9e7674-8ac4-408d-a2bb-d44e22623126)

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/2ed8053a-bd06-4b3a-a14c-de3e01c992fb)

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/4edb9a17-a424-4679-baa3-ac12c3e14415)

**Comment by runhey** [comment]
## 上手指北
截至2024.06.25, 使用hya分支，自行安装依赖，缺什么装什么
`./toolkit/python.exe -m pip install -i https://pypi.org/simple/ oashya --trusted-host pypi.org`

- 第一次的时候oasx会缓存一下，叉掉再打开就可以了
- 目前只能选Onnxruntime 和 FP32
- 中间关键的截屏目前仅仅是使用windows的api，所以不要最小化模拟器，其他截屏方式太拉了
- 先用默认的参数跑一轮感受一下
- 最高优先级使用例子：  `sp_001, sp_003`
- 感谢各位反馈建议

**Comment by yEs1do** [comment]
ssr_035 叫饭笥，不叫饭筒哈哈哈！

**Comment by runhey** [comment]
一些小trick
- 式神选神乐，这个在训练的时候加入了数据集当个负样本
- 游戏画质选极致，减少特效，没有上下文的情况下人眼也难以识别，别说机器了
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/8e1d3710-8704-4e9b-88eb-8d28eca13ab5)

**Comment by pangpangjiang** [comment]
你好我研究了半天还是没有出现百鬼夜行的选项，可以稍微教学一下吗

**Comment by runhey** [comment]
首先你要切换分支hya

**Comment by yunxi2367** [comment]
改了分支打不开是什么原因

**Comment by runhey** [comment]
> 改了分支打不开是什么原因

 是你的原因

**Comment by runhey** [comment]
效果展示，[小b站直达](https://www.bilibili.com/video/BV1Au3ae7EAQ?t=32.6)

**Comment by yunxi2367** [comment]
> 效果展示，[小b站直达](https://www.bilibili.com/video/BV1Au3ae7EAQ?t=32.6)

ERROR        | 15:33:31.142 | ModuleNotFoundError: No module named 'cryptography'   
         ╭───────────────── Traceback (most recent call last) ─────────────────╮
         │ E:\yinyangshifuzhu\OAS\script.py:351 in run                         │
         │                                                                     │
         │   348 │   │   │   module_name = 'script_task'                       │
         │   349 │   │   │   module_path = str(Path.cwd() / 'tasks' / command  │
         │   350 │   │   │   logger.info(f'module_path: {module_path}, module_ │
         │ ❱ 351 │   │   │   task_module = load_module(module_name, module_pat │
         │   352 │   │   │   task_module.ScriptTask(config=self.config, device │
         │   353 │   │   except TaskEnd:                                       │
         │   354 │   │   │   return True                                       │
         │                                                                     │
         │ ╭──────────────────────────── locals ─────────────────────────────╮ │
         │ │     command = 'Hyakkiyakou'                                     │ │
         │ │           e = ModuleNotFoundError("No module named              │ │
         │ │               'cryptography'")                                  │ │
         │ │ module_name = 'script_task'                                     │ │
         │ │ module_path = 'E:\\yinyangshifuzhu\\OAS\\tasks\\Hyakkiyakou\\s… │ │
         │ │        self = <script.Script object at 0x0000022F16F1B910>      │ │
         │ ╰─────────────────────────────────────────────────────────────────╯ │
         │                                                                     │
         │ E:\yinyangshifuzhu\OAS\module\base\utils.py:900 in load_module      │
         │                                                                     │
         │   897 │   """                                                       │
         │   898 │   spec = importlib.util.spec_from_file_location(moduleName, │
         │   899 │   module = importlib.util.module_from_spec(spec)            │
         │ ❱ 900 │   spec.loader.exec_module(module)                           │
         │   901 │   sys.modules[moduleName] = module                          │
         │   902 │   return module                                             │
         │   903                                                               │
         │                                                                     │
         │ ╭──────────────────────────── locals ─────────────────────────────╮ │
         │ │     module = <module 'script_task' from                         │ │
         │ │              'E:\\yinyangshifuzhu\\OAS\\tasks\\Hyakkiyakou\\sc… │ │
         │ │ moduleFile = 'E:\\yinyangshifuzhu\\OAS\\tasks\\Hyakkiyakou\\sc… │ │
         │ │ moduleName = 'script_task'                                      │ │
         │ │       spec = ModuleSpec(name='script_task',                     │ │
         │ │              loader=<_frozen_importlib_external.SourceFileLoad… │ │
         │ │              object at 0x0000022F301C3C10>,                     │ │
         │ │              origin='E:\\yinyangshifuzhu\\OAS\\tasks\\Hyakkiya… │ │
         │ ╰─────────────────────────────────────────────────────────────────╯ │
         │ in exec_module:883                                                  │
         │ ╭──────────────────────────── locals ─────────────────────────────╮ │
         │ │   code = <code object <module> at 0x0000022F30200DF0, file      │ │
         │ │          "E:\yinyangshifuzhu\OAS\tasks\Hyakkiyakou\script_task… │ │
         │ │          line 1>                                                │ │
         │ │ module = <module 'script_task' from                             │ │
         │ │          'E:\\yinyangshifuzhu\\OAS\\tasks\\Hyakkiyakou\\script… │ │
         │ │   self = <_frozen_importlib_external.SourceFileLoader object at │ │
         │ │          0x0000022F301C3C10>                                    │ │
         │ ╰─────────────────────────────────────────────────────────────────╯ │
         │ in _call_with_frames_removed:241                                    │
         │ ╭──────────────────────────── locals ─────────────────────────────╮ │
         │ │ args = (                                                        │ │
         │ │        │   <code object <module> at 0x0000022F30200DF0, file    │ │
         │ │        "E:\yinyangshifuzhu\OAS\tasks\Hyakkiyakou\script_task.p… │ │
         │ │        line 1>,                                                 │ │
         │ │        │   {                                                    │ │
         │ │        │   │   '__name__': 'script_task',                       │ │
         │ │        │   │   '__doc__': None,                                 │ │
         │ │        │   │   '__package__': '',                               │ │
         │ │        │   │   '__loader__':                                    │ │
         │ │        <_frozen_importlib_external.SourceFileLoader object at   │ │
         │ │        0x0000022F301C3C10>,                                     │ │
         │ │        │   │   '__spec__': ModuleSpec(name='script_task',       │ │
         │ │        loader=<_frozen_importlib_external.SourceFileLoader      │ │
         │ │        object at 0x0000022F301C3C10>,                           │ │
         │ │        origin='E:\\yinyangshifuzhu\\OAS\\tasks\\Hyakkiyakou\\s… │ │
         │ │        │   │   '__file__':                                      │ │
         │ │        'E:\\yinyangshifuzhu\\OAS\\tasks\\Hyakkiyakou\\script_t… │ │
         │ │        │   │   '__cached__':                                    │ │
         │ │        'E:\\yinyangshifuzhu\\OAS\\tasks\\Hyakkiyakou\\__pycach… │ │
         │ │        │   │   '__builtins__': {                                │ │
         │ │        │   │   │   '__name__': 'builtins',                      │ │
         │ │        │   │   │   '__doc__': 'Built-in functions, exceptions,  │ │
         │ │        and other objects.\n\nNoteworthy: None is the `nil'+46,  │ │
         │ │        │   │   │   '__package__': '',                           │ │
         │ │        │   │   │   '__loader__': <class                         │ │
         │ │        '_frozen_importlib.BuiltinImporter'>,                    │ │
         │ │        │   │   │   '__spec__': ModuleSpec(name='builtins',      │ │
         │ │        loader=<class '_frozen_importlib.BuiltinImporter'>,      │ │
         │ │        origin='built-in'),                                      │ │
         │ │        │   │   │   '__build_class__': <built-in function        │ │
         │ │        __build_class__>,                                        │ │
         │ │        │   │   │   '__import__': <built-in function             │ │
         │ │        __import__>,                                             │ │
         │ │        │   │   │   'abs': <built-in function abs>,              │ │
         │ │        │   │   │   'all': <built-in function all>,              │ │
         │ │        │   │   │   'any': <built-in function any>,              │ │
         │ │        │   │   │   ... +147                                     │ │
         │ │        │   │   },                                               │ │
         │ │        │   │   'time': <module 'time' (built-in)>,              │ │
         │ │        │   │   'cv2': <module 'cv2' from                        │ │
         │ │        'E:\\yinyangshifuzhu\\OAS\\toolkit\\lib\\site-packages\… │ │
         │ │        │   │   ... +7                                           │ │
         │ │        │   }                                                    │ │
         │ │        )                                                        │ │
         │ │    f = <built-in function exec>                                 │ │
         │ │ kwds = {}                                                       │ │
         │ ╰─────────────────────────────────────────────────────────────────╯ │
         │                                                                     │
         │ E:\yinyangshifuzhu\OAS\tasks\Hyakkiyakou\script_task.py:15 in       │
         │ <module>                                                            │
         │                                                                     │
         │    12 from cached_property import cached_property                   │
         │    13 # Use cmd to install: ./toolkit/python.exe -m pip install -i  │
         │       oashya --trusted-host pypi.org                                │
         │    14 # update oashya:  ./toolkit/python.exe -m pip install --upgra │
         │ ❱  15 from oashya.tracker import Tracker                            │
         │    16 from oashya.labels import label2id                            │
         │    17 from oashya.utils import draw_tracks                          │
         │    18                                                               │
         │                                                                     │
         │ ╭──────────────────────────── locals ─────────────────────────────╮ │
         │ │ cached_property = <class 'cached_property.cached_property'>     │ │
         │ │          choice = <bound method Random.choice of <random.Random │ │
         │ │                   object at 0x0000022F14329E80>>                │ │
         │ │             cv2 = <module 'cv2' from                            │ │
         │ │                   'E:\\yinyangshifuzhu\\OAS\\toolkit\\lib\\sit… │ │
         │ │        datetime = <class 'datetime.datetime'>                   │ │
         │ │        fromfile = <built-in function fromfile>                  │ │
         │ │              np = <module 'numpy' from                          │ │
         │ │                   'E:\\yinyangshifuzhu\\OAS\\toolkit\\lib\\sit… │ │
         │ │            time = <module 'time' (built-in)>                    │ │
         │ │       timedelta = <class 'datetime.timedelta'>                  │ │
         │ │           uint8 = <class 'numpy.uint8'>                         │ │
         │ ╰─────────────────────────────────────────────────────────────────╯ │
         │                                                                     │
         │ in init tracker:19                                                  │
         ╰─────────────────────────────────────────────────────────────────────╯
         ModuleNotFoundError: No module named 'cryptography'

**Comment by yunxi2367** [comment]
这是为什么

**Comment by runhey** [comment]
目前手动安装依赖

**Comment by runhey** [comment]
好了现在hya分支完成了历史使命了

**Comment by runhey** [comment]
> 好耶！ 我正在修邀请好友的区域，时不时会点到好友头像弹出框，然后卡住重启

秒懂，代码中1、2区域同时点击，盲猜一波

**Comment by yEs1do** [comment]
> > 好耶！ 我正在修邀请好友的区域，时不时会点到好友头像弹出框，然后卡住重启
> 
> 秒懂，代码中 1、2 区域同时点击，盲猜一波

有可能。被点到的是第一个好友的头像，我正在看日志是点到哪里了，尝试复现中。最好不是你框太多了哦。
话说跨区好友功能在代码里设计好了咋没加入到配置中。

**Comment by yEs1do** [comment]
把砸 buff 的时机搞一搞就完美了，目睹几次 up 跑走没砸。
“有金卡及关注式神在场且未持有 up 时优先砸 buff 再砸式神，如果无金卡及关注式神在场则走过半场才砸 buff”这个算法好设计不

**Comment by runhey** [comment]
base rule
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/54b015cb-dddd-4438-b1ae-290052393330)

**Comment by runhey** [comment]
rule based

**Comment by yunxi2367** [comment]
砸到冻结，冻结里面出现SSR或者SP的时候，会等冻结结束才会继续砸

**Comment by runhey** [comment]
冰冻属于 TODO 状态

**Comment by pauserer** [comment]
您好，能开源一下数据集吗，想加一下新式神
