### ISSUE TITLE
OASX连接不上OAS

### ISSUE THREAD

**Issue by kingfu1980** [runhey/OnmyojiAutoScript#277]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

大佬，你好！我另外一台电脑可以顺畅运行，为了多开，我单独用了这台电脑挂机，但OASX一直报错，连接不上OAS，我不知道问题出在哪了？非常感谢！！！

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![微信截图_20240617162330](https://github.com/runhey/OnmyojiAutoScript/assets/172862967/5fd066cf-befa-4cd0-a557-fe71203fb606)
![微信截图_20240617162357](https://github.com/runhey/OnmyojiAutoScript/assets/172862967/9f30609d-cb12-4e3d-a55f-b4d6d8ac7bcd)
![微信截图_20240617162505](https://github.com/runhey/OnmyojiAutoScript/assets/172862967/313df7ca-c967-4c7e-a4aa-a8ab26c8a8f9)

### 还有别的吗？

另：以前都是直接下载github的文件，没想过注册~~~现在想加入咱们的qq群，可Github账号时间问题不能加入，能否给个机会~

**Comment by kingfu1980** [comment]
我补充一下我的log文件
[2024-06-17_server.txt](https://github.com/user-attachments/files/15864250/2024-06-17_server.txt)

**Comment by runhey** [comment]
127都能敲错， 真有你的

**Comment by runhey** [comment]
你qq是什么

**Comment by kingfu1980** [comment]
呵呵，真的抱歉，是我脑子短路了！！！我qq470367249，感谢！！！

**Comment by asssasssa** [comment]
[2024-06-22_server.txt](https://github.com/user-attachments/files/15935656/2024-06-22_server.txt)
![image](https://github.com/runhey/OnmyojiAutoScript/assets/171221614/9ed6d26e-e417-4216-93c2-5ad087c9f460)
为什么我也链接不上呢，还有单独的提问帖子是怎么发的，我不会，求教。

**Comment by asssasssa** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/171221614/80ff9831-dad2-4d54-8fa9-42147510ec16)

**Comment by diamondll** [comment]
> 127都能敲错， 真有你的

哈哈哈哈哈 真是辛苦大佬 人都要气晕
