### ISSUE TITLE
悬赏封印好友协助邀请好友时卡住

### ISSUE THREAD

**Issue by yunxi2367** [runhey/OnmyojiAutoScript#278]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

悬赏封印好友协助邀请好友的时候，由于邀请好友界面更新，会导致一直卡在邀请好友的界面不会进行下一步，手动邀请后才进行下一步操作

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by yunxi2367** [comment]
INFO           | 18:12:32.093 | module_path:                                          
         E:\yinyangshifuzhu\OAS\tasks\WantedQuests\script_task.py, module_name: 
         script_task                                                            
INFO           | 18:12:32.105 | UI get current page                                   
INFO           | 18:12:32.138 | [UI] page_realm_raid                                  
INFO           | 18:12:32.143 | <<< UI GOTO PAGE_MAIN >>>                             
INFO           | 18:12:32.184 | Page switch: page_realm_raid -> page_exploration      
INFO           | 18:12:32.189 | Click (1214,  123) @ PAGE_REALM_RAID_GOTO_EXPLORATION 
INFO           | 18:12:32.322 | Page switch: page_kekkai_toppa -> page_exploration    
INFO           | 18:12:32.538 | Page switch: page_exploration -> page_main            
INFO           | 18:12:32.543 | Click (  75,   69) @ PAGE_BACK_BLUE                   
INFO           | 18:12:33.910 | Page arrive: page_main                                
INFO           | 18:12:34.343 | Click ( 273,  239) @ WQ_WQ_SEAL                       
INFO           | 18:12:34.911 | All wanted quests are traced                          
INFO           | 18:12:34.921 | <<< INVITE FRIENDS >>>                                
INFO           | 18:12:35.734 | Click (1188,  149) @ UI_UI_BACK_RED                   
INFO           | 18:12:35.925 | <<< UI GOTO PAGE_EXPLORATION >>>                      
INFO           | 18:12:35.950 | Page switch: page_main -> page_exploration            
INFO           | 18:12:35.972 | Click ( 667,  154) @ PAGE_MAIN_GOTO_EXPLORATION       
INFO           | 18:12:37.123 | Page arrive: page_exploration                         
INFO           | 18:12:37.327 | [WQ_NUMBER 0.004s] [984]                              
INFO           | 18:12:37.539 | [WQ_TEXT_1 0.005s] [封印]                             
INFO           | 18:12:37.551 | [WQ_NUM_1 0.007s] [0/11]                              
INFO           | 18:12:37.556 | <<< START WANTED QUESTS >>>                           
INFO           | 18:12:38.730 | Click (  76,  243) @ WQ_TEXT_1                        
INFO           | 18:12:39.340 | [WQ_TYPE_1 0.006s] [挑战]                             
INFO           | 18:12:39.366 | [WQ_INFO_1 0.010s] [第三章（数量：14）]               
INFO           | 18:12:39.537 | Click (1041,  263) @ WQ_GOTO_1                        
INFO           | 18:12:42.353 | Click ( 923,  542) @ CHANLLENGE_WQC_FIRE

**Comment by yunxi2367** [comment]
![Uploading 微信截图_20240617213533.png…]()

**Comment by yunxi2367** [comment]
![微信截图_20240617213533](https://github.com/runhey/OnmyojiAutoScript/assets/172466650/c9002ddb-4809-4424-b5de-a1b9d3606d00)

**Comment by yunxi2367** [comment]
![ddf5bbd58d98e8aac3633d59d38aec2](https://github.com/runhey/OnmyojiAutoScript/assets/172466650/71a8cf2b-068c-4076-980a-b69fafe2dd78)

**Comment by LLiu-y-j** [comment]
我也出现了这个问题，卡在邀请好友界面，请问下解决了吗？

**Comment by runhey** [comment]
#286 mark
