### ISSUE TITLE
斗技和阴阳寮识别不到

### ISSUE THREAD

**Issue by ljxun** [runhey/OnmyojiAutoScript#282]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

1.斗技和阴阳寮识别不到，阴阳寮我经过改图可正常识别，但是我重新启动就会覆盖我的版本
2.请问我把项目中 Branch: master 都改成了 Branch: dev 但是 oasx更新器那边还是显示 当前分支: master ，是我的问题吗
3.用的雷电模拟器，试过MuMu12因为渠道服很容易闪退
4.以下图片是我的雷电模拟器截图
5.还请教一下，杂货铺为何其他物品可以购买，却不买黑蛋，我可以开发吗，还是有其他原因

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

正常运行

### 相关 Logs

```Text
INFO           | 22:37:19.688 | Click (1103,  148) @ sou_group_1                      
INFO           | 22:37:20.242 | Click (1168,  145) @ sou_group_1                      
INFO           | 22:37:21.652 | Click ( 980,  164) @ SS_SOU_SWITCH_1                  
WARNING  | 22:37:22.555 | Click team 1 failed in group 1                        
INFO           | 22:37:23.410 | Click (1001,  175) @ SS_SOU_SWITCH_1                  
INFO           | 22:37:23.462 | Switch soul_one group 1 team 1                        
INFO           | 22:37:23.463 | UI get current page                                   
INFO           | 22:37:23.479 | [UI] page_shikigami_records                           
INFO           | 22:37:23.481 | <<< UI GOTO PAGE_KEKKAI_TOPPA >>>                     
INFO           | 22:37:23.496 | Page switch: page_shikigami_records -> page_main      
INFO           | 22:37:23.499 | Click (  19,   43) @ PAGE_BACK_Y                      
INFO           | 22:37:23.721 | Page switch: page_main -> page_exploration            
INFO           | 22:37:23.730 | Click ( 671,  136) @ PAGE_MAIN_GOTO_EXPLORATION       
INFO           | 22:37:24.630 | Page switch: page_exploration -> page_realm_raid      
INFO           | 22:37:24.632 | Click ( 293,  670) @ PAGE_EXPLORATION_GOTO_REALM_RAID 
INFO           | 22:37:25.231 | Page switch: page_realm_raid -> page_kekkai_toppa     
INFO           | 22:37:29.466 | Page switch: page_realm_raid -> page_kekkai_toppa
```

### 截图

![Screenshot_20240622-224924](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/fdceb33c-eec1-4965-a2b9-8f75cd54d5e2)
![res_ryou_toppa - 副本 - 副本](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/0dc2014a-0fd5-4569-b67c-5a18c178c2a8)

![Screenshot_20240622-224852](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/f334781c-6b17-494f-b009-88099d2dd13a)

**Comment by runhey** [comment]
2是用pipeline来执行git命令，来获取。有些设备确实有你这样的情况

**Comment by runhey** [comment]
5
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/4ee3b1dd-3262-4bbc-a4ba-0d76affd576e)

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/42482c44-0f7a-43de-98e9-5a9e6aaaedbd)
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/a3c1d589-0e60-4c83-9a17-862e589055c0)
zhe'z这张图片，你的设备上跑的匹配值是多少

**Comment by ljxun** [comment]
> ![image](https://private-user-images.githubusercontent.com/74492025/341981119-42482c44-0f7a-43de-98e9-5a9e6aaaedbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzIxNTEsIm5iZiI6MTcxOTA3MTg1MSwicGF0aCI6Ii83NDQ5MjAyNS8zNDE5ODExMTktNDI0ODJjNDQtMGY3YS00M2RlLTk4ZTktNWE5ZTZhYWFlZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE1NTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0ZmJjM2QxY2MyMjA3ZjcwZjYzZTUyZmIzMzk4NjUwZjU3ZDZhYjM0MDRhNjI5YTk1OTEwZGEyZTQ1NWFiZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yn69LClvJllq0v0BQTQZYkcbykan4Ftw3BsJ-67TlzQ) ![image](https://private-user-images.githubusercontent.com/74492025/341981148-a3c1d589-0e60-4c83-9a17-862e589055c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzIxNTEsIm5iZiI6MTcxOTA3MTg1MSwicGF0aCI6Ii83NDQ5MjAyNS8zNDE5ODExNDgtYTNjMWQ1ODktMGU2MC00YzgzLTlhMTctODYyZTU4OTA1NWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE1NTczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQzMThiM2U3NjEwNTE3NDk1MGYyNmE2ODI0MjE1M2VlOGY4ZDM1YzVhZTJkN2QxNGNlZDdiOWYzNTEyNGZkNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GOSnMjc8PrFUHIuyOM_5g_YygQ0QXpSXObNvxdRGTkE) zhe'z这张图片，你的设备上跑的匹配值是多少



PS C:\Users\59169\Desktop\on\OnmyojiAutoScript-master> & C:/Users/59169/Desktop/on/OnmyojiAutoScript-master/toolkit/python.exe c:/Users/59169/Desktop/on/OnmyojiAutoScript-master/assets_test.py
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-06-23 00:07:11.570 │ roi_front size changed to 38x51
INFO     2024-06-23 00:07:11.573 │ [PAGE_MAIN_GOTO_TEAM]: False
False

这是跑的结果，用的斗技那个图

**Comment by ljxun** [comment]
> ![image](https://private-user-images.githubusercontent.com/74492025/341981119-42482c44-0f7a-43de-98e9-5a9e6aaaedbd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzM4NTcsIm5iZiI6MTcxOTA3MzU1NywicGF0aCI6Ii83NDQ5MjAyNS8zNDE5ODExMTktNDI0ODJjNDQtMGY3YS00M2RlLTk4ZTktNWE5ZTZhYWFlZGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE2MjU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NTllMTY4MzhhMWM2MTFjNTQ4ZDkwY2UzOTBjZmZlYmIxZjE2MDkyZThkNGI0OTZiZWNhZjY1MWVkYjBlMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BPFMqCKA7dBzsgPaut72p3GBe4jxKouysN4X-uaOUCo) ![image](https://private-user-images.githubusercontent.com/74492025/341981148-a3c1d589-0e60-4c83-9a17-862e589055c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNzM4NTcsIm5iZiI6MTcxOTA3MzU1NywicGF0aCI6Ii83NDQ5MjAyNS8zNDE5ODExNDgtYTNjMWQ1ODktMGU2MC00YzgzLTlhMTctODYyZTU4OTA1NWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDE2MjU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNDYyNzY3YzcyYmNlZjY2YWQwN2Q3Zjg2MTY2NTkyOWFmOTNjZDI0NDM0NWZkYjFkZGU2NzI5NjdjZDk4YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2VKJJfMGkEE8ZmrJK67xPXivaclFeo91coN12m8xpoI) zhe'z这张图片，你的设备上跑的匹配值是多少
![{`6HP~N$ROKB0@07(XDMOYI](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/fbd6f022-5ee6-456e-8392-372b9ff3ce15)
这是我本地代码，不知道你是不要想要这个

**Comment by ljxun** [comment]
#281

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/b7ffffa5-fdc0-4b81-b819-e843c4b4bdbe)
跑的没问题

**Comment by runhey** [comment]
你换一个截图试试？

**Comment by ljxun** [comment]
> 你换一个截图方式试试？

寮突破可以识别了，截图方式从DroidCast_raw换成了ADB_nc，下午试试斗技，
谢谢大佬！！
