### ISSUE TITLE
请问雷电模拟器，如何使用百鬼

### ISSUE THREAD

**Issue by ljxun** [runhey/OnmyojiAutoScript#301]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

请问雷电模拟器，如何使用百鬼
试了各种模拟器操作方式和截图方式组合，均不行，

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

[log.txt](https://github.com/user-attachments/files/16111242/log.txt)
[log.txt](https://github.com/user-attachments/files/16111247/log.txt)
[log.txt](https://github.com/user-attachments/files/16111250/log.txt)
[log.txt](http
[log.txt](https://github.com/user-attachments/files/16111258/log.txt)
s://github.com/user-attachments/files/16111253/log.txt)
[log.txt](htt
[log.txt](https://github.com/user-attachments/files/16111260/log.txt)
ps://gith
[log.txt](https://github.com/user-attachments/files/16111261/log.txt)
ub.com/us
[log.txt](https://github.com/user-attachments/files/16111263/log.txt)
er-attachments/files/16111259/log.txt)

**Comment by runhey** [comment]
看你的配置，比如
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/01c055cf-3506-4016-9384-fc0fb7f6118e)

**Comment by ljxun** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/7f9109bf-2b05-4366-baba-d0123dc20350)
![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/b0c781da-e54b-4f3c-b0b8-b00931f39c6b)

**Comment by ljxun** [comment]
别的截图方式正常，切换成windows分辨率也变了，我是2k分辨率

**Comment by runhey** [comment]
等等你究竟是用雷电还是mumu12
v

**Comment by ljxun** [comment]
我昨天用的雷电不行，今天试了木木也有问题

**Comment by runhey** [comment]
就用雷电，看看雷电的配置

**Comment by ljxun** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/80a3d394-494b-401c-b805-c3ac10407924)
[log.txt](https://github.com/user-attachments/files/16114877/log.txt)

**Comment by runhey** [comment]
目前看配置没有问题，估摸着是代码

**Comment by ljxun** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/a52b3820-3745-47dc-8872-aef73e73a3c4)
而且我手动打开页面，怎么会分分辨率也出现问题

**Comment by ljxun** [comment]
而且我手动打开页面，怎么会分分辨率也出现问题

**Comment by ljxun** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/c12762f4-527b-44cf-8d6e-d93037a30f99)
跟刚才MuMu12一样

**Comment by ljxun** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/d50f8543-6ba5-456a-9969-52ceeafd83ba)
换了其他截屏方式正常运行，我怀疑桌面分辨率会有影响

**Comment by ljxun** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/597fec54-bed0-4b09-84bc-b493f8a2cc6f)
找到分辨率的问题了，windows截图不可以随便拖动窗口大小
现在问题是进百鬼，豆子拉满十个了，然后不会丢豆子

**Comment by ljxun** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/718854db-1bd5-4acd-a224-58fd5fdc6a43)
还需要设置什么吗

**Comment by runhey** [comment]
你先勾上一个显示效果看看

**Comment by ljxun** [comment]
好用了  换成cpu引擎 就可以使用

**Comment by runhey** [comment]
先看完这个，https://runhey.github.io/OnmyojiAutoScript-website/docs/user-manual/hyakkiyakou

**Comment by ljxun** [comment]
好的 感谢感谢

**Comment by ljxun** [comment]
问一下 是不是百鬼也不可以关闭屏幕

**Comment by runhey** [comment]
对
