### ISSUE TITLE
探索执行出现问题，一直不进入28副本，点了探索又返回主页循环

### ISSUE THREAD

**Issue by sjdcode** [runhey/OnmyojiAutoScript#304]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

执行探索的过程中出现脚本内部参数赋值错误

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-07-07 01:58:20.567 │ <<< LAUNCHER CONFIG >>>
INFO     2024-07-07 01:58:20.575 │ [Host] 0.0.0.0
INFO     2024-07-07 01:58:20.582 │ [Port] 22288
INFO     2024-07-07 01:58:20.588 │ [Reload] False
[32mINFO[0m:     Started server process [[36m8752[0m]
[32mINFO[0m:     Waiting for application startup.
INFO     2024-07-07 01:58:22.394 │ OAS web service startup done
[32mINFO[0m:     Application startup complete.
[32mINFO[0m:     Uvicorn running on [1mhttp://0.0.0.0:22288[0m (Press CTRL+C to quit)
read: D:\桌面\oas\oas\config\oas1.json
[32mINFO[0m:     127.0.0.1:10267 - "[1mGET /oas1/Exploration/args HTTP/1.1[0m" [32m200 OK[0m
WARNING  2024-07-07 01:58:48.721 │ [oas1] script argument enable value is string, try to convert to bool
read: D:\桌面\oas\oas\config\oas1.json
INFO     2024-07-07 01:58:48.737 │ Set arg oas1.exploration.scheduler.enable.False
write: D:\桌面\oas\oas\config\oas1.json
[32mINFO[0m:     127.0.0.1:10287 - "[1mPUT /oas1/Exploration/scheduler/enable/value?types=boolean&value=false HTTP/1.1[0m" [32m200 OK[0m
WARNING  2024-07-07 01:58:49.330 │ [oas1] script argument enable value is string, try to convert to bool
read: D:\桌面\oas\oas\config\oas1.json
INFO     2024-07-07 01:58:49.352 │ Set arg oas1.exploration.scheduler.enable.True
write: D:\桌面\oas\oas\config\oas1.json
[32mINFO[0m:     127.0.0.1:10287 - "[1mPUT /oas1/Exploration/scheduler/enable/value?types=boolean&value=true HTTP/1.1[0m" [32m200 OK[0m
```

### 还有别的吗？

显示String类型赋值类Boolean

**Comment by runhey** [comment]
你的内容跟标题有关系吗，我甚至没有看着执行探索

**Comment by runhey** [comment]
日志里面看不到一丁点`一直不进入28副本，点了探索又返回主页循环`

**Comment by shenbohua** [comment]
同样出现这个问题════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── EXPLORATION ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
[I 240714 10:06:58 __init__:874] [pid:12120] [127.0.0.1:16416] newCommandTimeout updated to 168h0m0s
INFO     2024-07-14 10:06:58.379 | logger.py:333│ [u2.Device] Device(atx_agent_url=http://127.0.0.1:53617)
INFO     2024-07-14 10:06:59.735 | logger.py:333│ [Screen_size] 1280x720
INFO     2024-07-14 10:06:59.742 | script.py:350│ module_path: D:\Program Files
         (x86)\OnmyojiAutoScript-easy-install\tasks\Exploration\script_task.py, module_name: script_task
INFO     2024-07-14 10:07:00.064 | game_ui.py:96│ UI get current page
INFO     2024-07-14 10:07:00.080 | logger.py:333│ [UI] page_main
INFO     2024-07-14 10:07:00.090 | logger.py:326│ <<< UI GOTO PAGE_EXPLORATION >>>
INFO     2024-07-14 10:07:00.180 | game_ui.py:244│ Page switch: page_main -> page_exploration
INFO     2024-07-14 10:07:00.216 | control.py:74│ Click ( 678,  116) @ PAGE_MAIN_GOTO_EXPLORATION
INFO     2024-07-14 10:07:00.222 | logger.py:326│ <<< MINITOUCH INIT >>>
INFO     2024-07-14 10:07:00.258 | logger.py:333│ [Device Orientation] 1 (HOME key on the right)
INFO     2024-07-14 10:07:00.265 | connection.py:440│ Reuse forward: ForwardItem(serial='127.0.0.1:16416',
         local='tcp:20994', remote='localabstract:minitouch')
INFO     2024-07-14 10:07:00.275 | minitouch.py:401│ v 1
INFO     2024-07-14 10:07:00.279 | minitouch.py:405│ ^ 10 720 1280 0
INFO     2024-07-14 10:07:00.287 | minitouch.py:428│ $ 3500
INFO     2024-07-14 10:07:00.292 | minitouch.py:432│ minitouch running on port: 20994, pid: 3500
INFO     2024-07-14 10:07:00.300 | minitouch.py:435│ max_contact: 10; max_x: 720; max_y: 1280; max_pressure: 0
INFO     2024-07-14 10:07:04.424 | game_ui.py:221│ Page arrive: page_exploration
INFO     2024-07-14 10:07:05.955 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.733s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:07.185 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.304s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:07.195 | sub_ocr.py:40│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [3]
INFO     2024-07-14 10:07:07.201 | sub_ocr.py:59│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1084.0, 556.0, 132.0,
         29.0)
INFO     2024-07-14 10:07:07.206 | control.py:74│ Click (1197,  563) @ E_EXPLORATION_LEVEL_NUMBER
INFO     2024-07-14 10:07:08.812 | script.py:445│ Scheduler: End task `Exploration`
read: D:\Program Files (x86)\OnmyojiAutoScript-easy-install\config\oas1.json
INFO     2024-07-14 10:07:08.826 | config.py:213│ Pending tasks: ['Exploration']
INFO     2024-07-14 10:07:08.829 | logger.py:333│ [Task] Exploration (Enable, 5, 2023-01-01 00:00:00)
INFO     2024-07-14 10:07:08.834 | script.py:440│ Scheduler: Start task `Exploration`
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── EXPLORATION ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-07-14 10:07:09.506 | script.py:350│ module_path: D:\Program Files
         (x86)\OnmyojiAutoScript-easy-install\tasks\Exploration\script_task.py, module_name: script_task
INFO     2024-07-14 10:07:09.511 | game_ui.py:96│ UI get current page
INFO     2024-07-14 10:07:09.562 | control.py:74│ Click (1034,  155) @ UI_UI_BACK_RED
INFO     2024-07-14 10:07:09.618 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:09.624 | control.py:74│ Click (  67,   70) @ UI_UI_BACK_BLUE
INFO     2024-07-14 10:07:09.679 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:09.782 | logger.py:333│ [Package_name] com.netease.onmyoji.bili
INFO     2024-07-14 10:07:09.803 | logger.py:333│ [Device Orientation] 1 (HOME key on the right)
INFO     2024-07-14 10:07:10.569 | logger.py:333│ [UI] page_exploration
INFO     2024-07-14 10:07:10.574 | logger.py:326│ <<< UI GOTO PAGE_EXPLORATION >>>
INFO     2024-07-14 10:07:11.382 | game_ui.py:221│ Page arrive: page_exploration
INFO     2024-07-14 10:07:12.468 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.295s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:13.657 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.318s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:13.663 | sub_ocr.py:40│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [3]
INFO     2024-07-14 10:07:13.670 | sub_ocr.py:59│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1084.0, 556.0, 132.0,
         29.0)
INFO     2024-07-14 10:07:13.681 | control.py:74│ Click (1172,  558) @ E_EXPLORATION_LEVEL_NUMBER
INFO     2024-07-14 10:07:15.266 | script.py:445│ Scheduler: End task `Exploration`
read: D:\Program Files (x86)\OnmyojiAutoScript-easy-install\config\oas1.json
INFO     2024-07-14 10:07:15.280 | config.py:213│ Pending tasks: ['Exploration']
INFO     2024-07-14 10:07:15.284 | logger.py:333│ [Task] Exploration (Enable, 5, 2023-01-01 00:00:00)
INFO     2024-07-14 10:07:15.289 | script.py:440│ Scheduler: Start task `Exploration`
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── EXPLORATION ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-07-14 10:07:15.950 | script.py:350│ module_path: D:\Program Files
         (x86)\OnmyojiAutoScript-easy-install\tasks\Exploration\script_task.py, module_name: script_task
INFO     2024-07-14 10:07:15.955 | game_ui.py:96│ UI get current page
INFO     2024-07-14 10:07:16.004 | control.py:74│ Click (1058,  133) @ UI_UI_BACK_RED
INFO     2024-07-14 10:07:16.059 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:16.064 | control.py:74│ Click (  45,   61) @ UI_UI_BACK_BLUE
INFO     2024-07-14 10:07:16.119 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:16.200 | logger.py:333│ [Package_name] com.netease.onmyoji.bili
INFO     2024-07-14 10:07:16.219 | logger.py:333│ [Device Orientation] 1 (HOME key on the right)
INFO     2024-07-14 10:07:16.967 | logger.py:333│ [UI] page_exploration
INFO     2024-07-14 10:07:16.972 | logger.py:326│ <<< UI GOTO PAGE_EXPLORATION >>>
INFO     2024-07-14 10:07:17.796 | game_ui.py:221│ Page arrive: page_exploration
INFO     2024-07-14 10:07:18.868 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.296s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:20.020 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.291s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:20.027 | sub_ocr.py:40│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [3]
INFO     2024-07-14 10:07:20.032 | sub_ocr.py:59│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1084.0, 556.0, 132.0,
         29.0)
INFO     2024-07-14 10:07:20.037 | control.py:74│ Click (1124,  568) @ E_EXPLORATION_LEVEL_NUMBER
INFO     2024-07-14 10:07:21.619 | script.py:445│ Scheduler: End task `Exploration`
read: D:\Program Files (x86)\OnmyojiAutoScript-easy-install\config\oas1.json
INFO     2024-07-14 10:07:21.631 | config.py:213│ Pending tasks: ['Exploration']
INFO     2024-07-14 10:07:21.636 | logger.py:333│ [Task] Exploration (Enable, 5, 2023-01-01 00:00:00)
INFO     2024-07-14 10:07:21.640 | script.py:440│ Scheduler: Start task `Exploration`
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── EXPLORATION ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-07-14 10:07:22.368 | script.py:350│ module_path: D:\Program Files
         (x86)\OnmyojiAutoScript-easy-install\tasks\Exploration\script_task.py, module_name: script_task
INFO     2024-07-14 10:07:22.374 | game_ui.py:96│ UI get current page
INFO     2024-07-14 10:07:22.428 | control.py:74│ Click (1052,  130) @ UI_UI_BACK_RED
INFO     2024-07-14 10:07:22.484 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:22.489 | control.py:74│ Click (  71,   73) @ UI_UI_BACK_BLUE
INFO     2024-07-14 10:07:22.543 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:22.642 | logger.py:333│ [Package_name] com.netease.onmyoji.bili
INFO     2024-07-14 10:07:22.661 | logger.py:333│ [Device Orientation] 1 (HOME key on the right)
INFO     2024-07-14 10:07:23.570 | logger.py:333│ [UI] page_exploration
INFO     2024-07-14 10:07:23.575 | logger.py:326│ <<< UI GOTO PAGE_EXPLORATION >>>
INFO     2024-07-14 10:07:24.449 | game_ui.py:221│ Page arrive: page_exploration
INFO     2024-07-14 10:07:25.579 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.306s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:26.832 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.307s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:26.841 | sub_ocr.py:40│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [3]
INFO     2024-07-14 10:07:26.857 | sub_ocr.py:59│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1084.0, 556.0, 132.0,
         29.0)
INFO     2024-07-14 10:07:26.863 | control.py:74│ Click (1204,  583) @ E_EXPLORATION_LEVEL_NUMBER
INFO     2024-07-14 10:07:28.475 | script.py:445│ Scheduler: End task `Exploration`
read: D:\Program Files (x86)\OnmyojiAutoScript-easy-install\config\oas1.json
INFO     2024-07-14 10:07:28.491 | config.py:213│ Pending tasks: ['Exploration']
INFO     2024-07-14 10:07:28.495 | logger.py:333│ [Task] Exploration (Enable, 5, 2023-01-01 00:00:00)
INFO     2024-07-14 10:07:28.500 | script.py:440│ Scheduler: Start task `Exploration`
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── EXPLORATION ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-07-14 10:07:29.180 | script.py:350│ module_path: D:\Program Files
         (x86)\OnmyojiAutoScript-easy-install\tasks\Exploration\script_task.py, module_name: script_task
INFO     2024-07-14 10:07:29.187 | game_ui.py:96│ UI get current page
INFO     2024-07-14 10:07:29.238 | control.py:74│ Click (1038,  165) @ UI_UI_BACK_RED
INFO     2024-07-14 10:07:29.295 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:29.301 | control.py:74│ Click (  34,   73) @ UI_UI_BACK_BLUE
INFO     2024-07-14 10:07:29.356 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:29.455 | logger.py:333│ [Package_name] com.netease.onmyoji.bili
INFO     2024-07-14 10:07:29.474 | logger.py:333│ [Device Orientation] 1 (HOME key on the right)
INFO     2024-07-14 10:07:30.272 | logger.py:333│ [UI] page_exploration
INFO     2024-07-14 10:07:30.279 | logger.py:326│ <<< UI GOTO PAGE_EXPLORATION >>>
INFO     2024-07-14 10:07:31.152 | game_ui.py:221│ Page arrive: page_exploration
INFO     2024-07-14 10:07:32.390 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.305s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:33.824 | logger.py:333│ [E_EXPLORATION_LEVEL_NUMBER 0.385s] ['第二十五章', '第二十六章',
         '第二十七章', '第二十八章']
INFO     2024-07-14 10:07:33.835 | sub_ocr.py:40│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [3]
INFO     2024-07-14 10:07:33.841 | sub_ocr.py:59│ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1084.0, 556.0, 132.0,
         29.0)
INFO     2024-07-14 10:07:33.850 | control.py:74│ Click (1118,  583) @ E_EXPLORATION_LEVEL_NUMBER
INFO     2024-07-14 10:07:35.894 | script.py:445│ Scheduler: End task `Exploration`
read: D:\Program Files (x86)\OnmyojiAutoScript-easy-install\config\oas1.json
INFO     2024-07-14 10:07:35.912 | config.py:213│ Pending tasks: ['Exploration']
INFO     2024-07-14 10:07:35.918 | logger.py:333│ [Task] Exploration (Enable, 5, 2023-01-01 00:00:00)
INFO     2024-07-14 10:07:35.923 | script.py:440│ Scheduler: Start task `Exploration`
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── EXPLORATION ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-07-14 10:07:37.049 | script.py:350│ module_path: D:\Program Files
         (x86)\OnmyojiAutoScript-easy-install\tasks\Exploration\script_task.py, module_name: script_task
INFO     2024-07-14 10:07:37.059 | game_ui.py:96│ UI get current page
INFO     2024-07-14 10:07:37.142 | control.py:74│ Click (1061,  139) @ UI_UI_BACK_RED
INFO     2024-07-14 10:07:37.202 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:37.210 | control.py:74│ Click (  51,   60) @ UI_UI_BACK_BLUE
INFO     2024-07-14 10:07:37.267 | game_ui.py:137│ Trying to switch to supported page
INFO     2024-07-14 10:07:37.400 | logger.py:333│ [Package_name] com.netease.onmyoji.bili
INFO     2024-07-14 10:07:37.433 | logger.py:333│ [Device Orientation] 1 (HOME key on the right)
