### ISSUE TITLE
使用mumu模拟器下载全渠道端百鬼会黑屏

### ISSUE THREAD

**Issue by you-dada** [runhey/OnmyojiAutoScript#305]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

使用mumu模拟器下载全渠道端百鬼开启运行跟踪黑屏（指弹出窗口黑屏），并且脚本不运行（报错）

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![IMG_20240707_122048](https://github.com/runhey/OnmyojiAutoScript/assets/136242517/76b29006-bf2d-4506-92a5-ba7b9bd0c523)

**Comment by runhey** [comment]
快来日志

**Comment by you-dada** [comment]
![98528531da801e90058375895e3561d](https://github.com/runhey/OnmyojiAutoScript/assets/136242517/95dc2825-b4a1-4610-ae37-a61f19e6e0f4)

**Comment by you-dada** [comment]
日志到这就不动了

**Comment by runhey** [comment]
还有一个debug的选项，勾上再跑一次

**Comment by runhey** [comment]
还有你脚本的配置

**Comment by you-dada** [comment]
您能详细是一下debug选项在哪吗，没有找到

**Comment by runhey** [comment]
if appear_then_click("想点的按钮"):
        continue

**Comment by you-dada** [comment]
![b910a9965c49927220913874cd4ccce](https://github.com/runhey/OnmyojiAutoScript/assets/136242517/5fa410aa-cbf8-4ac3-bc15-7f7faf677948)

**Comment by runhey** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/d1b2e726-06d7-4c3d-a4c6-52bd935f30b4)

**Comment by you-dada** [comment]
刚才那张截图已经是开启状态

**Comment by runhey** [comment]
好

**Comment by you-dada** [comment]
![1d3a9c90139f5a3e175640ffc413ea7](https://github.com/runhey/OnmyojiAutoScript/assets/136242517/791a7edb-41a2-4f85-9eb4-ead6a3d5ad25)

**Comment by runhey** [comment]
Handle别auto

**Comment by you-dada** [comment]
问题依旧

**Comment by you-dada** [comment]
![70a9ed3f9ca77cd4fa2301631350d9f](https://github.com/runhey/OnmyojiAutoScript/assets/136242517/7d61d52c-1e28-47ad-85cc-3f7160324a11)

**Comment by runhey** [comment]
emm

**Comment by runhey** [comment]
你能不能截屏一下里面撒百鬼的图。
我怀疑是没有检测到这个标志就一直空跑
![train_check_run](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/1e612636-a4f1-4ccb-a59f-12562c157eaf)

![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/8fe94ce9-d5c0-44b2-b5ab-a9433b88eda8)

**Comment by you-dada** [comment]
又行了唉，大佬牛！

**Comment by you-dada** [comment]
但是现在豆子不会切到10

**Comment by you-dada** [comment]
![1012629c3c7219516ee97f4fbf86780](https://github.com/runhey/OnmyojiAutoScript/assets/136242517/7a1934f8-c788-48ee-9cac-004b585f4e4b)

**Comment by you-dada** [comment]
不管了，能用就行，感谢佬

**Comment by kongdr418** [comment]
你好，你是如何解决的？我的问题和你的一模一样
