### ISSUE TITLE
🎈请问我自己调试ScriptTask 报错，需要怎么处理？

### ISSUE THREAD

**Issue by ljxun** [runhey/OnmyojiAutoScript#307]
### 描述

搜索引擎查询了，有些看不懂
![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/46197cb8-7e0f-4e0f-be95-75cd1c88afd8)

**Comment by runhey** [comment]
你的工作路径要在oas根路径

**Comment by runhey** [comment]
pycharm不好吗非得用vscode

**Comment by ljxun** [comment]
好的 我试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月8日(周一) 晚上7:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [runhey/OnmyojiAutoScript] 🎈请问我自己调试ScriptTask 报错，需要怎么处理？ (Issue #307)




 
你的工作路径要在oas根路径

**Comment by ljxun** [comment]
新手上路，请多关照。哈哈哈



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月8日(周一) 晚上7:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [runhey/OnmyojiAutoScript] 🎈请问我自己调试ScriptTask 报错，需要怎么处理？ (Issue #307)




 
pycharm不好吗非得用vscode
