### ISSUE TITLE
杂货铺‘’黑蛋‘’在oasx显示 “破碎符咒”

### ISSUE THREAD

**Issue by ljxun** [runhey/OnmyojiAutoScript#308]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [ ] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

杂货铺‘’黑蛋‘’在oasx显示 “破碎符咒”
我一直在看黑蛋为啥不买 ，才发现这个是黑蛋

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/runhey/OnmyojiAutoScript/assets/43953295/dd90364b-6487-4893-9171-a5a0f99785bf)

**Comment by runhey** [comment]
这个我记得改了

**Comment by shityrone** [comment]
佬，您好。我刚刚在网站上重新下载了0.2.3版本的，好像还是显示破碎的咒符
