### ISSUE TITLE
mumu刷魂土脚本不运行

### ISSUE THREAD

**Issue by you-dada** [runhey/OnmyojiAutoScript#314]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

mumu刷魂土脚本不运行，似乎卡在ui识上

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![aca4d310826c8e0cd177dd861f11d63](https://github.com/runhey/OnmyojiAutoScript/assets/136242517/0d876378-6d3e-4f89-87af-4f93ad2f249d)

**Comment by you-dada** [comment]
![7d35cb6b58339e0765ff7d4075ea3fd](https://github.com/runhey/OnmyojiAutoScript/assets/136242517/cfe514fe-1e0e-41da-9296-1a6d19d969bc)

**Comment by yunxi2367** [comment]
运行时间设置到现在

**Comment by you-dada** [comment]
可以了，感谢大佬，打扰了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年07月11日 22:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [runhey/OnmyojiAutoScript] mumu刷魂土脚本不运行 (Issue #314) |

运行时间设置到现在
