### ISSUE TITLE
通用邀请任务存在设计缺陷

### ISSUE THREAD

**Issue by yEs1do** [runhey/OnmyojiAutoScript#334]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

正常现象：如果设定邀请一个人，队友名字也只填写一个 A，那么会邀请 A。
有些奇妙的设计：如果设定邀请一个人，但队友名字中填写两个人 A B，那么会向 A B 同时发送一次邀请。
问题现象：如果设定邀请两个人，队友名字中填写 A B，那么会分别发送两次邀请，第一次邀请 A 和 B，第二次邀请 B，导致 B 实际在第一次就被邀请，第二次连邀请的加号都识别不到。
所以如果我想要邀请两个人组三人队，应该如何设置？！我觉得无论队友名字填写几位，邀请两个人都应该先邀请 A 再邀请 B，不然三人队的设计就没有意义了。

另外，在悬赏封印任务中，只填写一个人的名字也会邀请两个人，看来是 “通用邀请” 任务的设计问题。

### LOG
> ──────────────────────────────── INVITE FRIEND ─────────────────────────────────
INFO           | 21:07:14.059 | INVITE FRIEND                                         
INFO           | 21:07:14.060 | Ensure enter invite page                              
INFO           | 21:07:14.661 | Room type: normal_3                                   
INFO           | 21:07:14.662 | Click add to invite friend                            
INFO           | 21:07:14.965 | Click (1126,  270) @ GI_ADD_2                         
INFO           | 21:07:15.271 | [F_LIST_1 0.006s] [好友]                              
INFO           | 21:07:15.279 | [F_LIST_2 0.005s] [最近]                              
INFO           | 21:07:15.286 | [F_LIST_3 0.005s] [察友]                              
INFO           | 21:07:15.291 | [F_LIST_4 0.004s] [跨区]                              
INFO           | 21:07:15.293 | Friend class: ['好友', '最近', '寮友', '跨区']        
INFO           | 21:07:15.295 | Find recent friend                                    
INFO           | 21:07:15.565 | Click ( 493,  140) @ GI_FLAG_2_OFF                    
INFO           | 21:07:16.773 | Click ( 518,  143) @ GI_FLAG_2_OFF                    
INFO           | 21:07:17.069 | Now find friend in ”最近“                             
INFO           | 21:07:18.289 | [FRIEND_NAME_1 0.214s] ['手动打码小号1',             
         '网易一手动打码1']                                                      
INFO           | 21:07:18.292 | OCR [FRIEND_NAME_1] detected in [0]                   
INFO           | 21:07:18.294 | OCR [FRIEND_NAME_1] detected in (445.0, 200.0, 154.0, 
         21.0)                                                                  
INFO           | 21:07:18.297 | Click ( 520,  211) @ FRIEND_NAME_1                    
INFO           | 21:07:18.537 | [FRIEND_NAME_2 0.189s] ['手动打码小号2',                 
         '网易一手动打码2']                                                      
INFO           | 21:07:18.539 | OCR [FRIEND_NAME_2] detected in [1]                   
INFO           | 21:07:18.542 | OCR [FRIEND_NAME_2] detected in (734.0, 233.0, 149.0, 
         20.0)                                                                  
INFO           | 21:07:18.544 | Click ( 803,  233) @ FRIEND_NAME_2                    
INFO           | 21:07:19.612 | Click invite ensure                                   
INFO           | 21:07:19.621 | Click ( 756,  557) @ GI_INVITE_ENSURE                 
INFO           | 21:07:24.921 | Click add to invite friend                            
INFO           | 21:07:24.936 | Click (1105,  272) @ GI_ADD_2                         
INFO           | 21:07:25.233 | [F_LIST_1 0.005s] [好友]                              
INFO           | 21:07:25.238 | [F_LIST_2 0.004s] [最近]                              
INFO           | 21:07:25.245 | [F_LIST_3 0.005s] [察友]                              
INFO           | 21:07:25.251 | [F_LIST_4 0.004s] [跨区]                              
INFO           | 21:07:25.252 | Friend class: ['好友', '最近', '寮友', '跨区']        
INFO           | 21:07:25.254 | Find recent friend                                    
INFO           | 21:07:25.531 | Click ( 490,  145) @ GI_FLAG_2_OFF                    
INFO           | 21:07:25.831 | Now find friend in ”最近“                             
INFO           | 21:07:27.025 | [FRIEND_NAME_1 0.188s] ['手动打码小号1',             
         '网易一手动打码1']                                                      
INFO           | 21:07:27.028 | OCR [FRIEND_NAME_1] detected in None                  
INFO           | 21:07:27.225 | [FRIEND_NAME_2 0.194s] ['手动打码小号2',                 
         '网易一手动打码2']                                                      
INFO           | 21:07:27.229 | OCR [FRIEND_NAME_2] detected in [0]                   
INFO           | 21:07:27.231 | OCR [FRIEND_NAME_2] detected in (737.0, 200.0, 109.0, 
         20.0)                                                                  
INFO           | 21:07:27.233 | Click ( 816,  201) @ FRIEND_NAME_2                    
INFO           | 21:07:28.301 | Click invite ensure                                   
INFO           | 21:07:28.310 | Click ( 742,  563) @ GI_INVITE_ENSURE                 
INFO           | 21:07:30.622 | Start challenge and user invite two friends           
INFO           | 21:07:30.923 | Click (1226,  613) @ GI_FIRE                          

### 截图

如果觉得我描述的不清楚，需要的话我录一段视频

**Comment by runhey** [comment]
我记得是，OCR识别的逻辑是出现其中的字，就会判断是

**Comment by yEs1do** [comment]
这两个名字完全不相似，目前测试的猜测情况是固定邀请紧挨着的后面一个人，无论后面那一个叫什么

**Comment by runhey** [comment]
你两个小号叫什么

**Comment by runhey** [comment]
你填的配置是不是有问题啊

**Comment by runhey** [comment]
```
INFO | 21:07:17.069 | Now find friend in ”最近“
INFO | 21:07:18.289 | [FRIEND_NAME_1 0.214s] ['手动打码小号1',
'网易一手动打码1']
INFO | 21:07:18.292 | OCR [FRIEND_NAME_1] detected in [0]
INFO | 21:07:18.294 | OCR [FRIEND_NAME_1] detected in (445.0, 200.0, 154.0,
21.0)
INFO | 21:07:18.297 | Click ( 520, 211) @ FRIEND_NAME_1
---------------------------------------------------------------------------------
INFO | 21:07:18.537 | [FRIEND_NAME_2 0.189s] ['手动打码小号2',
'网易一手动打码2']
INFO | 21:07:18.539 | OCR [FRIEND_NAME_2] detected in [1]
INFO | 21:07:18.542 | OCR [FRIEND_NAME_2] detected in (734.0, 233.0, 149.0,
20.0)
INFO | 21:07:18.544 | Click ( 803, 233) @ FRIEND_NAME_2
INFO | 21:07:19.612 | Click invite ensure
INFO | 21:07:19.621 | Click ( 756, 557) @ GI_INVITE_ENSURE
INFO | 21:07:24.921 | Click add to invite friend
```

**Comment by runhey** [comment]
```python
    def detect_select(self, name: str = None) -> bool:
        """
        在当前的页面检测是否有好友， 如果有就选中这个好友
        :return:
        """
        if not name:
            return False

        self.screenshot()
        self.O_FRIEND_NAME_1.keyword = name
        self.O_FRIEND_NAME_2.keyword = name
        appear_1 = self.ocr_appear_click(self.O_FRIEND_NAME_1, interval=2)
        appear_2 = self.ocr_appear_click(self.O_FRIEND_NAME_2, interval=2)
        if not appear_1 and not appear_2:
            logger.info('Current page no friend')
            return False

        while appear_1 or appear_2:
            self.screenshot()
            if self.appear(self.I_SELECTED):
                break
            appear_1 = self.ocr_appear_click(self.O_FRIEND_NAME_1, interval=2)
            appear_2 = self.ocr_appear_click(self.O_FRIEND_NAME_2, interval=2)

        return True
```

**Comment by yEs1do** [comment]
OCR 识别问题，现已通过缩短查找关键字的方式间接解决，如“陈情匿旧酒”仅搜索“陈情”防止匹配到第二个好友
