### ISSUE TITLE
✨出现异常无法重启

### ISSUE THREAD

**Issue by pangpangjiang** [runhey/OnmyojiAutoScript#338]
### 当前不足

以前出现问题识别不了会自动重启，这个怎么改回去
![Uploading IMG_2130.png…]()

**Comment by pangpangjiang** [comment]
感觉是因为我没有选择网络异常立刻重启这个选项，我选择的是等待10s，明天看看👀

**Comment by runhey** [comment]
看不懂
看不到图片

**Comment by runhey** [comment]
也没有日志

**Comment by pangpangjiang** [comment]
> 也没有日志> 也没有日志不好意思我表达的意思是在之前的版本中如果出现识别不了的问题，游戏会自动重启，但是自从这个月开始已经不会自动重启了
比如之前我打探索的时候不小心点开了聊天界面忘记关了，过一会就会自动重启游戏，重新进行探索
这是之前几天发生的问题，我是一个【资深】OAS用户我基本上全天挂着游戏和OAS
但是我又不太懂的代码，所以我想问一下我要怎么去更改一下某些代码来达成：
｛出现问题｝
｛等待｝
｛无法解决｝
｛重新启动｝
｛再次执行任务｝
这里就会引出两条路
｛成功｝｛失败｝
失败的话就直接放弃
大概是这个意思

**Comment by runhey** [comment]
我不懂，我可以建议你复制好原先的配置文件。然后删掉整个OAS重新安装

**Comment by pangpangjiang** [comment]
好的，下次出现问题我会记录，保留日志和截图，谢谢
