### ISSUE TITLE
百鬼夜行 不能自动开始

### ISSUE THREAD

**Issue by haodedong** [runhey/OnmyojiAutoScript#339]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

打开百鬼夜行日志报错

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 20:14:20.176 | Start scheduler loop: ddd                             
INFO           | 20:14:20.229 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 20:14:20.235 | [Task] Hyakkiyakou (Enable, 5, 2023-01-01 00:00:00)   
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 20:14:20.268 |   DEVICE                                              
INFO           | 20:14:20.283 | [AdbBinary]                                           
         C:/Users/Administrator/Downloads/OnmyojiAutoScript-easy-install/Onmyoji
         AutoScript-easy-install/toolkit/Lib/site-packages/adbutils/binaries/adb
         .exe                                                                   
INFO           | 20:14:20.297 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 20:14:20.322 | <<< DETECT DEVICE >>>                                 
INFO           | 20:14:20.352 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 20:14:20.363 | 127.0.0.1:7555                                        
INFO           | 20:14:20.374 | Auto device detection found only one device, using it 
INFO           | 20:14:20.390 | already connected to 127.0.0.1:7555                   
INFO           | 20:14:20.409 | [AdbDevice] AdbDevice(serial=127.0.0.1:7555)          
INFO           | 20:14:20.419 | <<< DETECT PACKAGE >>>                                
INFO           | 20:14:20.426 | Get package list                                      
INFO           | 20:14:20.618 | Here are the available packages in device             
         "127.0.0.1:7555", copy to Alas.Emulator.PackageName to use it          
INFO           | 20:14:20.656 | com.netease.onmyoji.wyzymnqsd_cps                     
INFO           | 20:14:20.669 | Auto package detection found only one package, using  
         it                                                                     
INFO           | 20:14:20.684 | Server changed, release resources                     
INFO           | 20:14:20.693 | [PackageName] com.netease.onmyoji.wyzymnqsd_cps       
INFO           | 20:14:20.702 | <<< HANDLE >>>                                        
INFO           | 20:14:20.797 | Handle is empty. oas not use handle                   
INFO           | 20:14:20.815 | Screenshot interval set to 0.3s                       
INFO           | 20:14:20.822 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 20:14:20.859 | [nemud.app_keep_alive] false                          
INFO           | 20:14:20.871 | Update droidcast resolution                           
INFO           | 20:14:20.903 | [u2.Device]                                           
         Device(atx_agent_url=http://127.0.0.1:13279)                           
INFO           | 20:14:20.957 | [Device Orientation] 1 (HOME key on the right)        
INFO           | 20:14:20.982 | Droicast resolution: (720, 1280)                      
INFO           | 20:14:21.001 | Reuse forward: ForwardItem(serial='127.0.0.1:7555',   
         local='tcp:20663', remote='tcp:53516')                                 
INFO           | 20:14:21.400 | [Screen_size] 1280x720                                
INFO           | 20:14:21.424 | module_path:                                          
         C:\Users\Administrator\Downloads\OnmyojiAutoScript-easy-install\Onmyoji
         AutoScript-easy-install\tasks\Hyakkiyakou\script_task.py, module_name: 
         script_task                                                            
INFO           | 20:14:21.892 | UI get current page                                   
INFO           | 20:14:21.968 | [UI] page_town                                        
INFO           | 20:14:21.976 | <<< UI GOTO PAGE_HYAKKIYAKOU >>>                      
INFO           | 20:14:22.099 | Page switch: page_town -> page_hyakkiyakou            
INFO           | 20:14:22.116 | Click ( 922,  187) @ PAGE_TOWN_GOTO_HYAKKIYAKOU       
INFO           | 20:14:22.130 | <<< MINITOUCH INIT >>>                                
INFO           | 20:14:22.177 | [Device Orientation] 1 (HOME key on the right)        
INFO           | 20:14:22.192 | Reuse forward: ForwardItem(serial='127.0.0.1:7555',   
         local='tcp:20377', remote='localabstract:minitouch')                   
INFO           | 20:14:22.215 |      v 1                                              
INFO           | 20:14:22.227 | ^ 10 720 1280 0                                       
INFO           | 20:14:22.242 |   $ 7360                                              
INFO           | 20:14:22.251 | minitouch running on port: 20377, pid: 7360           
INFO           | 20:14:22.259 | max_contact: 10; max_x: 720; max_y: 1280;             
         max_pressure: 0                                                        
INFO           | 20:14:24.102 | Page arrive: page_hyakkiyakou                         
WARNING  | 20:14:24.116 | Page Error                                            
WARNING  | 20:15:22.207 | Wait too long                                         
WARNING  | 20:15:22.223 | Waiting for set()                                     
INFO           | 20:15:22.400 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
ERROR        | 20:15:22.415 | GameStuckError: Wait too long                         
WARNING  | 20:15:22.431 | Saving error: ./log/error/1721304922431               
WARNING  | 20:15:22.924 | Game stuck, com.netease.onmyoji.wyzymnqsd_cps will be 
         restarted in 10 seconds                                                
WARNING  | 20:15:22.940 | If you are playing by hand, please stop Alas          
INFO           | 20:15:22.948 | Notifier: DDD                                         
INFO           | 20:15:22.956 | Task call: restart                                    
INFO           | 20:15:33.006 | Scheduler: End task `Hyakkiyakou`                     
INFO           | 20:15:33.054 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 20:15:33.080 | [Task] Hyakkiyakou (Enable, 5, 2023-01-01 00:00:00)   
INFO           | 20:15:33.097 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 20:15:33.514 | module_path:                                          
         C:\Users\Administrator\Downloads\OnmyojiAutoScript-easy-install\Onmyoji
         AutoScript-easy-install\tasks\Hyakkiyakou\script_task.py, module_name: 
         script_task                                                            
INFO           | 20:15:33.549 | UI get current page                                   
INFO           | 20:15:33.890 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
INFO           | 20:15:33.978 | [Device Orientation] 1 (HOME key on the right)        
WARNING  | 20:15:43.722 | Unknown ui page                                       
INFO           | 20:15:43.730 | [EMULATOR__SCREENSHOT_METHOD]                         
         ScreenshotMethod.DROIDCAST_RAW                                         
INFO           | 20:15:43.740 | [EMULATOR__CONTROL_METHOD] ControlMethod.MINITOUCH    
WARNING  | 20:15:43.751 | Starting from current page is not supported           
WARNING  | 20:15:43.760 | Supported page: ['page_main', 'page_summon',          
         'page_exploration', 'page_town', 'page_awake_zones', 'page_soul_zones',
         'page_realm_raid', 'page_goryou_realm', 'page_delegation',             
         'page_secret_zones', 'page_area_boss', 'page_heian_kitan',             
         'page_six_gates', 'page_bondling_fairyland', 'page_kekkai_toppa',      
         'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel',   
         'page_hyakkisen', 'page_shikigami_records', 'page_onmyodo',            
         'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team',  
         'page_collection']                                                     
WARNING  | 20:15:43.772 | Supported page: Any page with a "HOME" button on the  
         upper-right                                                            
CRITICAL    | 20:15:43.798 | Please switch to a supported page before starting oas 
INFO           | 20:15:43.815 | Game server may be under maintenance or network may be
         broken, check server status now                                        
CRITICAL    | 20:15:43.824 | Game page unknown                                     
WARNING  | 20:15:43.831 | Saving error: ./log/error/1721304943831               
INFO           | 20:15:44.257 | Notifier: DDD                                         
INFO           | 20:15:44.291 | Script ddd process exit                               
ERROR        | 20:15:44.304 | Error: 1
```

### 截图

![2024-07-18_20-15-43-720177](https://github.com/user-attachments/assets/048f25dc-7527-4ac2-bf1a-b7eb16ca0d5d)

**Comment by haodedong** [comment]
尊敬的作者您好，我是用的是mumu模拟器。模拟器配置如下：
基础信息
UUID :  d22e8223-45a2-4be9-be73-cd7ed0787e3e
模拟器版本 :  3.8.30.3010
模拟器磁盘（可用/总）空间 :  115.2GB/125GB
日志路径 :  C:\Program Files\Netease\MuMuPlayer-12.0\vms\MuMuPlayer-12.0-0\logs\

运行环境
VT :  开启
Hyper-V :  关闭
网络环境检测 :  正常
以管理员运行方式 :  是
DirectX 11是否安装 :  是
防火墙 :  关闭

电脑配置
主板型号 :  Manufacturer: Dell Inc.  Product: 005T15
CPU :  Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
系统版本 :  Windows 10 64-bit Kernel 10.0.19042
显卡驱动 :  正常
显卡驱动型号 :  20.19.15.5126 (20200121)
所有显卡 :  Intel(R) HD Graphics 4600  |  Microsoft Basic Render Driver
当前使用显卡 :  Intel(R) HD Graphics 4600
安装磁盘(可用/总)空间 :  14.8GB/111.8GB
可用内存/总内存 :  2.3GB/7.9GB

模拟器设置
Root :  关闭
显卡渲染模式 :  DirectX 模式
性能设置 :  3核/3GB
手机型号 :  HUAWEI 畅享 50
分辨率 :  1280 * 720
高帧率 :  关闭
后台保活 :  关闭

连接设备
音频输入 :  未连接
音频输出 :  已连接

网络信息
MuMu DNS :  192.168.31.1
电脑DNS :  192.168.31.1
Rom MAC地址 :  08:5a:5c:2f:e0:00

ADB调试端口 :  16384
MuMu出口IP地址 :  10.0.2.15
电脑出口IP地址 :  119.112.46.223

其它信息
其它版本信息 :  vm: 120.1.68.009 hyperv: 6.3.19.0 renderer: 0.0.176.0
Vendor :  NetEase
OpenGL Renderer :  MuMu GL (Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0)
OpenGL Version :  OpenGL ES 3.1 V132
运行时间 :  22 : 55 : 8

**Comment by haodedong** [comment]
作者您好，之前确实是我的问题，之前填的是auto，现在已经改正了
2:08:40.197 | Start scheduler loop: oas3                            
INFO           | 22:08:40.232 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 22:08:40.259 | [Task] Hyakkiyakou (Enable, 5, 2023-01-01 00:00:00)   
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 22:08:40.271 |   DEVICE                                              
INFO           | 22:08:40.296 | [AdbBinary]                                           
         C:/Users/Administrator/Downloads/OnmyojiAutoScript-easy-install2/Onmyoj
         iAutoScript-easy-install/toolkit/Lib/site-packages/adbutils/binaries/ad
         b.exe                                                                  
INFO           | 22:08:40.335 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 22:08:40.362 | <<< DETECT DEVICE >>>                                 
INFO           | 22:08:40.382 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 22:08:40.392 | 127.0.0.1:16384                                       
INFO           | 22:08:40.397 | 127.0.0.1:7555                                        
INFO           | 22:08:40.418 | already connected to 127.0.0.1:16384                  
INFO           | 22:08:40.433 | [AdbDevice] AdbDevice(serial=127.0.0.1:16384)         
INFO           | 22:08:40.454 | <<< DETECT PACKAGE >>>                                
INFO           | 22:08:40.461 | Get package list                                      
INFO           | 22:08:40.660 | Here are the available packages in device             
         "127.0.0.1:16384", copy to Alas.Emulator.PackageName to use it         
INFO           | 22:08:40.668 | com.netease.onmyoji.wyzymnqsd_cps                     
INFO           | 22:08:40.674 | Auto package detection found only one package, using  
         it                                                                     
INFO           | 22:08:40.705 | Server changed, release resources                     
INFO           | 22:08:40.721 | [PackageName] com.netease.onmyoji.wyzymnqsd_cps       
INFO           | 22:08:40.734 | <<< HANDLE >>>                                        
INFO           | 22:08:40.743 | Handle is handle num. oas use it as root handle num   
INFO           | 22:08:40.776 | Handle number 919650 is valid                         
INFO           | 22:08:40.790 | The root handle title is MuMu模拟器12 and num is      
         919650                                                                 
INFO           | 22:08:40.796 | Emulator handle structure:                            
INFO           | 22:08:40.802 | MuMu模拟器12                                          
INFO           | 22:08:40.828 | └── MuMuPlayer                                        
INFO           | 22:08:40.855 |     └── nemudisplay                                   
INFO           | 22:08:40.859 |   919650                                              
INFO           | 22:08:40.866 | └── 589852                                            
INFO           | 22:08:40.870 |     └── 328380                                        
INFO           | 22:08:40.896 | Emulator family: EmulatorFamily.FAMILY_MUMU           
INFO           | 22:08:40.906 | Your window screen scale rate: 1.0                    
INFO           | 22:08:40.913 | The emulator is MuMu模拟器12                          
INFO           | 22:08:40.916 | Screenshot handle num: 589852                         
INFO           | 22:08:40.920 | Emulator screenshot size: (1280, 720)                 
INFO           | 22:08:40.925 | Screenshot interval set to 0.3s                       
INFO           | 22:08:40.931 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 22:08:40.992 | [Screen_size] 1280x720                                
INFO           | 22:08:41.006 | module_path:                                          
         C:\Users\Administrator\Downloads\OnmyojiAutoScript-easy-install2\Onmyoj
         iAutoScript-easy-install\tasks\Hyakkiyakou\script_task.py, module_name:
         script_task                                                            
INFO           | 22:08:41.347 | UI get current page                                   
INFO           | 22:08:41.373 | [UI] page_main                                        
INFO           | 22:08:41.388 | <<< UI GOTO PAGE_HYAKKIYAKOU >>>                      
INFO           | 22:08:41.470 | Page switch: page_main -> page_town                   
INFO           | 22:08:41.525 | Click ( 745,  293) @ PAGE_MAIN_GOTO_TOWN              
INFO           | 22:08:41.544 | <<< MINITOUCH INIT >>>                                
INFO           | 22:08:41.586 | [Device Orientation] 1 (HOME key on the right)        
INFO           | 22:08:41.596 | Reuse forward: ForwardItem(serial='127.0.0.1:16384',  
         local='tcp:20527', remote='localabstract:minitouch')                   
INFO           | 22:08:41.606 |      v 1                                              
INFO           | 22:08:41.616 | ^ 10 720 1280 0                                       
INFO           | 22:08:41.620 |   $ 2437                                              
INFO           | 22:08:41.646 | minitouch running on port: 20527, pid: 2437           
INFO           | 22:08:41.659 | max_contact: 10; max_x: 720; max_y: 1280;             
         max_pressure: 0                                                        
INFO           | 22:08:43.293 | Page switch: page_town -> page_hyakkiyakou            
INFO           | 22:08:43.300 | Click ( 899,  180) @ PAGE_TOWN_GOTO_HYAKKIYAKOU       
INFO           | 22:08:46.010 | Page arrive: page_hyakkiyakou                         
WARNING  | 22:08:46.042 | Page Error                                            
WARNING  | 22:09:43.347 | Wait too long                                         
WARNING  | 22:09:43.361 | Waiting for set()                                     
INFO           | 22:09:43.434 | [u2.Device]                                           
         Device(atx_agent_url=http://127.0.0.1:4827)                            
INFO           | 22:09:43.717 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
ERROR        | 22:09:43.790 | GameStuckError: Wait too long                         
WARNING  | 22:09:43.861 | Saving error: ./log/error/1721311783861               
WARNING  | 22:09:44.596 | Game stuck, com.netease.onmyoji.wyzymnqsd_cps will be 
         restarted in 10 seconds                                                
WARNING  | 22:09:44.607 | If you are playing by hand, please stop Alas          
INFO           | 22:09:44.614 | Notifier: OAS3                                        
INFO           | 22:09:44.624 | Task call: restart                                    
INFO           | 22:09:54.661 | Scheduler: End task `Hyakkiyakou`                     
INFO           | 22:09:54.730 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 22:09:54.750 | [Task] Hyakkiyakou (Enable, 5, 2023-01-01 00:00:00)   
INFO           | 22:09:54.796 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 22:09:54.853 | module_path:                                          
         C:\Users\Administrator\Downloads\OnmyojiAutoScript-easy-install2\Onmyoj
         iAutoScript-easy-install\tasks\Hyakkiyakou\script_task.py, module_name:
         script_task                                                            
INFO           | 22:09:54.873 | UI get current page                                   
INFO           | 22:09:55.267 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
INFO           | 22:09:55.320 | [Device Orientation] 1 (HOME key on the right)        
WARNING  | 22:10:05.089 | Unknown ui page                                       
INFO           | 22:10:05.110 | [EMULATOR__SCREENSHOT_METHOD]                         
         ScreenshotMethod.WINDOW_BACKGROUND                                     
INFO           | 22:10:05.126 | [EMULATOR__CONTROL_METHOD] ControlMethod.MINITOUCH    
WARNING  | 22:10:05.132 | Starting from current page is not supported           
WARNING  | 22:10:05.140 | Supported page: ['page_main', 'page_summon',          
         'page_exploration', 'page_town', 'page_awake_zones', 'page_soul_zones',
         'page_realm_raid', 'page_goryou_realm', 'page_delegation',             
         'page_secret_zones', 'page_area_boss', 'page_heian_kitan',             
         'page_six_gates', 'page_bondling_fairyland', 'page_kekkai_toppa',      
         'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel',   
         'page_hyakkisen', 'page_shikigami_records', 'page_onmyodo',            
         'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team',  
         'page_collection']                                                     
WARNING  | 22:10:05.185 | Supported page: Any page with a "HOME" button on the  
         upper-right                                                            
CRITICAL    | 22:10:05.195 | Please switch to a supported page before starting oas 
INFO           | 22:10:05.235 | Game server may be under maintenance or network may be
         broken, check server status now                                        
CRITICAL    | 22:10:05.268 | Game page unknown                                     
WARNING  | 22:10:05.341 | Saving error: ./log/error/1721311805341               
INFO           | 22:10:06.133 | Notifier: OAS3                                        
INFO           | 22:10:06.161 | Script oas3 process exit                              
ERROR        | 22:10:06.188 | Error: 1

**Comment by haodedong** [comment]
现在就是一直卡在要进入百鬼的页面，然后就不动啦

**Comment by runhey** [comment]
收到

**Comment by haodedong** [comment]
![2024-07-18_22-10-05-062509](https://github.com/user-attachments/assets/f265fd80-3321-4f1d-a5d0-96a34fd62448)
[log.txt](https://github.com/user-attachments/files/16284516/log.txt)

**Comment by haodedong** [comment]
给您添麻烦了

**Comment by runhey** [comment]
好吧确实有问题，切换其他任意界面启动就可以的

**Comment by runhey** [comment]
比如庭院

**Comment by haodedong** [comment]
感谢您大晚上帮忙查找问题，我在庭院启动也不好使，是不是我的配置不对呀，日志如下
═══════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 22:32:41.386 | Start scheduler loop: oas3                            
INFO           | 22:32:41.397 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 22:32:41.423 | [Task] Hyakkiyakou (Enable, 5, 2023-01-01 00:00:00)   
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 22:32:41.438 |   DEVICE                                              
INFO           | 22:32:41.443 | [AdbBinary]                                           
         C:/Users/Administrator/Downloads/OnmyojiAutoScript-easy-install2/Onmyoj
         iAutoScript-easy-install/toolkit/Lib/site-packages/adbutils/binaries/ad
         b.exe                                                                  
INFO           | 22:32:41.448 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 22:32:41.453 | <<< DETECT DEVICE >>>                                 
INFO           | 22:32:41.456 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 22:32:41.460 | 127.0.0.1:16384                                       
INFO           | 22:32:41.468 | 127.0.0.1:7555                                        
INFO           | 22:32:41.493 | already connected to 127.0.0.1:16384                  
INFO           | 22:32:41.505 | [AdbDevice] AdbDevice(serial=127.0.0.1:16384)         
INFO           | 22:32:41.510 | <<< DETECT PACKAGE >>>                                
INFO           | 22:32:41.514 | Get package list                                      
INFO           | 22:32:41.754 | Here are the available packages in device             
         "127.0.0.1:16384", copy to Alas.Emulator.PackageName to use it         
INFO           | 22:32:41.775 | com.netease.onmyoji.wyzymnqsd_cps                     
INFO           | 22:32:41.783 | Auto package detection found only one package, using  
         it                                                                     
INFO           | 22:32:41.787 | Server changed, release resources                     
INFO           | 22:32:41.791 | [PackageName] com.netease.onmyoji.wyzymnqsd_cps       
INFO           | 22:32:41.794 | <<< HANDLE >>>                                        
INFO           | 22:32:41.797 | Handle is handle num. oas use it as root handle num   
INFO           | 22:32:41.821 | Handle number 1312866 is valid                        
INFO           | 22:32:41.832 | The root handle title is MuMu模拟器12 and num is      
         1312866                                                                
INFO           | 22:32:41.838 | Emulator handle structure:                            
INFO           | 22:32:41.849 | MuMu模拟器12                                          
INFO           | 22:32:41.850 | └── MuMuPlayer                                        
INFO           | 22:32:41.859 |     └── nemudisplay                                   
INFO           | 22:32:41.862 |  1312866                                              
INFO           | 22:32:41.864 | └── 1836318                                           
INFO           | 22:32:41.883 |     └── 1247336                                       
INFO           | 22:32:41.897 | Emulator family: EmulatorFamily.FAMILY_MUMU           
INFO           | 22:32:41.913 | Your window screen scale rate: 1.0                    
INFO           | 22:32:41.922 | The emulator is MuMu模拟器12                          
INFO           | 22:32:41.926 | Screenshot handle num: 1836318                        
INFO           | 22:32:41.929 | Emulator screenshot size: (1280, 720)                 
INFO           | 22:32:41.934 | Screenshot interval set to 0.3s                       
INFO           | 22:32:41.941 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 22:32:42.003 | [Screen_size] 1280x720                                
INFO           | 22:32:42.017 | module_path:                                          
         C:\Users\Administrator\Downloads\OnmyojiAutoScript-easy-install2\Onmyoj
         iAutoScript-easy-install\tasks\Hyakkiyakou\script_task.py, module_name:
         script_task                                                            
INFO           | 22:32:42.308 | UI get current page                                   
INFO           | 22:32:42.324 | [UI] page_main                                        
INFO           | 22:32:42.330 | <<< UI GOTO PAGE_HYAKKIYAKOU >>>                      
INFO           | 22:32:42.392 | Page switch: page_main -> page_town                   
INFO           | 22:32:42.442 | Click ( 735,  262) @ PAGE_MAIN_GOTO_TOWN              
INFO           | 22:32:42.448 | <<< MINITOUCH INIT >>>                                
INFO           | 22:32:42.474 | [Device Orientation] 1 (HOME key on the right)        
INFO           | 22:32:42.490 | Create forward: ForwardItem(serial='127.0.0.1:16384', 
         local='tcp:20120', remote='localabstract:minitouch')                   
INFO           | 22:32:42.507 |      v 1                                              
INFO           | 22:32:42.512 | ^ 10 720 1280 0                                       
INFO           | 22:32:42.515 |   $ 3138                                              
INFO           | 22:32:42.518 | minitouch running on port: 20120, pid: 3138           
INFO           | 22:32:42.521 | max_contact: 10; max_x: 720; max_y: 1280;             
         max_pressure: 0                                                        
INFO           | 22:32:44.119 | Page switch: page_town -> page_hyakkiyakou            
INFO           | 22:32:44.139 | Click ( 918,  230) @ PAGE_TOWN_GOTO_HYAKKIYAKOU       
INFO           | 22:32:47.444 | Page arrive: page_hyakkiyakou                         
WARNING  | 22:32:47.460 | Page Error                                            
WARNING  | 22:33:44.333 | Wait too long                                         
WARNING  | 22:33:44.346 | Waiting for set()                                     
INFO           | 22:33:44.378 | [u2.Device]                                           
         Device(atx_agent_url=http://127.0.0.1:6078)                            
INFO           | 22:33:44.567 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
ERROR        | 22:33:44.579 | GameStuckError: Wait too long                         
WARNING  | 22:33:44.594 | Saving error: ./log/error/1721313224594               
WARNING  | 22:33:45.179 | Game stuck, com.netease.onmyoji.wyzymnqsd_cps will be 
         restarted in 10 seconds                                                
WARNING  | 22:33:45.186 | If you are playing by hand, please stop Alas          
INFO           | 22:33:45.190 | Notifier: OAS3                                        
INFO           | 22:33:45.193 | Task call: restart                                    
INFO           | 22:33:55.979 | Scheduler: End task `Hyakkiyakou`

**Comment by haodedong** [comment]
现象就是首先会从庭院调整到町中，进入这个百鬼夜行的页面，然后日志提示
INFO           | 22:32:47.444 | Page arrive: page_hyakkiyakou                         
WARNING  | 22:32:47.460 | Page Error    
然后就卡在这里了

**Comment by haodedong** [comment]
如果勾选了朋友，日志是
INFO           | 22:37:33.412 | Page arrive: page_hyakkiyakou                         
WARNING  | 22:37:33.446 | Page Error                                            
──────────────────────────────── INVITE FRIEND ─────────────────────────────────
INFO           | 22:37:33.480 | INVITE FRIEND                                         
INFO           | 22:37:33.724 | Click ( 139,  572) @ HYA_HINVITE                      
INFO           | 22:37:35.849 | Click ( 619,  287) @ friend_1                         
INFO           | 22:37:36.139 | Click ( 785,  258) @ friend_2                         
INFO           | 22:37:36.444 | Invite friend done

**Comment by haodedong** [comment]
早点休息吧

**Comment by runhey** [comment]
![hya_haccess](https://github.com/user-attachments/assets/e5893942-f503-4d42-886f-7f8be9f5cd99)
这张按钮匹配的阈值只有0.77

**Comment by runhey** [comment]
你看这个 https://github.com/runhey/OnmyojiAutoScript/issues/332
