### ISSUE TITLE
阴阳师在模拟器里如果脚本自动执行阴阳师就会卡在进入界面一直报错，如果手动进入游戏，脚本又会出现找不到游戏界面的错误。

### ISSUE THREAD

**Issue by lvk19941208** [runhey/OnmyojiAutoScript#344]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

阴阳师在模拟器里如果脚本自动执行阴阳师就会卡在进入界面一直报错，如果手动进入游戏，脚本又会出现找不到游戏界面的错误。

### 如何复现

1. 启动脚本，模拟器自动启动游戏，结果游戏会卡在登录界面无法登录。
2. 手动登录游戏，会报错无法找到游戏界面

### 预期行为

希望脚本能正常运行

### 相关 Logs

```Text
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────── KEKKAIUTILIZE ─────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-07-19 20:28:21.988 | logger.py:333│ [Screen_size] 1280x720
INFO     2024-07-19 20:28:21.993 | script.py:350│ module_path:
         E:\YYSJB\OnmyojiAutoScript-easy-install\tasks\KekkaiUtilize\script_task.py, module_name: script_task
INFO     2024-07-19 20:28:22.137 | game_ui.py:96│ UI get current page
[I 240719 20:28:22 __init__:874] [pid:10576] [127.0.0.1:7555] newCommandTimeout updated to 168h0m0s
INFO     2024-07-19 20:28:22.209 | logger.py:333│ [u2.Device] Device(atx_agent_url=http://127.0.0.1:61450)
INFO     2024-07-19 20:28:22.275 | logger.py:333│ [Package_name] com.netease.onmyoji.wyzymnqsd_cps
INFO     2024-07-19 20:28:22.291 | logger.py:333│ [Device Orientation] 1 (HOME key on the right)
WARNING  2024-07-19 20:28:32.240 | game_ui.py:153│ Unknown ui page
INFO     2024-07-19 20:28:32.245 | logger.py:333│ [EMULATOR__SCREENSHOT_METHOD] ScreenshotMethod.WINDOW_BACKGROUND
INFO     2024-07-19 20:28:32.248 | logger.py:333│ [EMULATOR__CONTROL_METHOD] ControlMethod.MINITOUCH
WARNING  2024-07-19 20:28:32.251 | game_ui.py:156│ Starting from current page is not supported
WARNING  2024-07-19 20:28:32.266 | game_ui.py:157│ Supported page: ['page_main', 'page_summon', 'page_exploration',
         'page_town', 'page_awake_zones', 'page_soul_zones', 'page_realm_raid', 'page_goryou_realm', 'page_delegation',
         'page_secret_zones', 'page_area_boss', 'page_heian_kitan', 'page_six_gates', 'page_bondling_fairyland',
         'page_kekkai_toppa', 'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel', 'page_hyakkisen',
         'page_shikigami_records', 'page_onmyodo', 'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team',
         'page_collection']
WARNING  2024-07-19 20:28:32.288 | game_ui.py:158│ Supported page: Any page with a "HOME" button on the upper-right
CRITICAL 2024-07-19 20:28:32.301 | game_ui.py:159│ Please switch to a supported page before starting oas
INFO     2024-07-19 20:28:32.307 | script.py:377│ Game server may be under maintenance or network may be broken, check
         server status now
CRITICAL 2024-07-19 20:28:32.318 | script.py:379│ Game page unknown
WARNING  2024-07-19 20:28:32.323 | script.py:96│ Saving error: ./log/error/1721392112323
INFO     2024-07-19 20:28:32.379 | config.py:377│ Notifier: OAS1
INFO     2024-07-19 20:28:32.388 | script_process.py:139│ Script oas1 process exit
ERROR    2024-07-19 20:28:32.402 | logger.py:363│ Error: 1
```

### 截图

![4(V_4BD1WIRQCN7`M$W9MRS](https://github.com/user-attachments/assets/43e0b790-a059-48e6-962a-7d3dcdf95531)
![6BF D1X9E9FINU~QJU1$2ZC](https://github.com/user-attachments/assets/073bdbfc-13c8-423f-ba79-f88a3d0ca8b3)
![H7XMU3Z_0UGA_6}N (
![4(V_4BD1WIRQCN7`M$W9MRS](https://github.com/user-attachments/assets/43e0b790-a059-48e6-962a-7d3dcdf95531)
![6BF D1X9E9FINU~QJU1$2ZC](https://github.com/user-attachments/assets/073bdbfc-13c8-423f-ba79-f88a3d0ca8b3)
3}F](https://github.com/user-attachments/assets/1514c524-9563-43e2-87ac-97545bbee4cf)
![O{Y663 _O`2J SV{2AMJWL](https://github.com/user-attachments/assets/5302f336-33b1-4e36-9cd8-20b32c983eea)
![RJ3}XZTJ_@ _AOOQHXRCQDW](https://github.com/user-attachments/assets/b72252a9-a4f0-4e41-beeb-ad4ac8713438)

### 还有别的吗？

希望有大佬能帮忙看看并解决，非常感谢

**Comment by runhey** [comment]
尝试探索大世界启动

**Comment by lvk19941208** [comment]
> 尝试探索大世界启动
尝试了，还是不行，我将代码和截图发给您看一下，麻烦您了，谢谢
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────── KEKKAIUTILIZE ─────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-07-19 20:45:38.662 | logger.py:333│ [Screen_size] 1280x720
INFO     2024-07-19 20:45:38.665 | script.py:350│ module_path:
         E:\YYSJB\OnmyojiAutoScript-easy-install\tasks\KekkaiUtilize\script_task.py, module_name: script_task
INFO     2024-07-19 20:45:38.796 | game_ui.py:96│ UI get current page
[I 240719 20:45:38 __init__:874] [pid:6168] [127.0.0.1:7555] newCommandTimeout updated to 168h0m0s
INFO     2024-07-19 20:45:38.849 | logger.py:333│ [u2.Device] Device(atx_agent_url=http://127.0.0.1:61450)
INFO     2024-07-19 20:45:38.890 | logger.py:333│ [Package_name] com.netease.onmyoji.wyzymnqsd_cps
INFO     2024-07-19 20:45:38.902 | logger.py:333│ [Device Orientation] 1 (HOME key on the right)
WARNING  2024-07-19 20:45:48.900 | game_ui.py:153│ Unknown ui page
INFO     2024-07-19 20:45:48.902 | logger.py:333│ [EMULATOR__SCREENSHOT_METHOD] ScreenshotMethod.WINDOW_BACKGROUND
INFO     2024-07-19 20:45:48.906 | logger.py:333│ [EMULATOR__CONTROL_METHOD] ControlMethod.MINITOUCH
WARNING  2024-07-19 20:45:48.909 | game_ui.py:156│ Starting from current page is not supported
WARNING  2024-07-19 20:45:48.913 | game_ui.py:157│ Supported page: ['page_main', 'page_summon', 'page_exploration',
         'page_town', 'page_awake_zones', 'page_soul_zones', 'page_realm_raid', 'page_goryou_realm', 'page_delegation',
         'page_secret_zones', 'page_area_boss', 'page_heian_kitan', 'page_six_gates', 'page_bondling_fairyland',
         'page_kekkai_toppa', 'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel', 'page_hyakkisen',
         'page_shikigami_records', 'page_onmyodo', 'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team',
         'page_collection']
WARNING  2024-07-19 20:45:48.917 | game_ui.py:158│ Supported page: Any page with a "HOME" button on the upper-right
CRITICAL 2024-07-19 20:45:48.919 | game_ui.py:159│ Please switch to a supported page before starting oas
INFO     2024-07-19 20:45:48.925 | script.py:377│ Game server may be under maintenance or network may be broken, check
         server status now
CRITICAL 2024-07-19 20:45:48.927 | script.py:379│ Game page unknown
WARNING  2024-07-19 20:45:48.930 | script.py:96│ Saving error: ./log/error/1721393148930
INFO     2024-07-19 20:45:48.977 | config.py:377│ Notifier: OAS1
INFO     2024-07-19 20:45:48.979 | script_process.py:139│ Script oas1 process exit
ERROR    2024-07-19 20:45:48.983 | logger.py:363│ Error: 1


════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 20:45:38.491 | Start scheduler loop: oas1                            
INFO           | 20:45:38.500 | Pending tasks: ['KekkaiUtilize', 'KekkaiActivation',  
         'DemonEncounter', 'AreaBoss', 'RealmRaid', 'RyouToppa', 'DailyTrifles',
         'Hunt', 'Orochi', 'Sougenbi', 'EvoZone', 'CollectiveMissions',         
         'SoulsTidy', 'Delegation', 'Hyakkiyakou', 'WeeklyTrifles', 'Duel']     
INFO           | 20:45:38.504 | [Task] KekkaiUtilize (Enable, 2, 2023-01-01 00:00:00) 
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 20:45:38.510 |   DEVICE                                              
INFO           | 20:45:38.512 | [AdbBinary]                                           
         E:/YYSJB/OnmyojiAutoScript-easy-install/toolkit/Lib/site-packages/adbut
         ils/binaries/adb.exe                                                   
INFO           | 20:45:38.515 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 20:45:38.521 | <<< DETECT DEVICE >>>                                 
INFO           | 20:45:38.523 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 20:45:38.526 | 127.0.0.1:7555                                        
INFO           | 20:45:38.530 | Auto device detection found only one device, using it 
INFO           | 20:45:38.535 | already connected to 127.0.0.1:7555                   
INFO           | 20:45:38.539 | [AdbDevice] AdbDevice(serial=127.0.0.1:7555)          
INFO           | 20:45:38.541 | <<< DETECT PACKAGE >>>                                
INFO           | 20:45:38.544 | Get package list                                      
INFO           | 20:45:38.585 | Here are the available packages in device             
         "127.0.0.1:7555", copy to Alas.Emulator.PackageName to use it          
INFO           | 20:45:38.588 | com.netease.onmyoji.wyzymnqsd_cps                     
INFO           | 20:45:38.590 | Auto package detection found only one package, using  
         it                                                                     
INFO           | 20:45:38.592 | Server changed, release resources                     
INFO           | 20:45:38.595 | [PackageName] com.netease.onmyoji.wyzymnqsd_cps       
INFO           | 20:45:38.599 | <<< HANDLE >>>                                        
INFO           | 20:45:38.602 | Handle is auto. oas will find window emulator         
INFO           | 20:45:38.606 | Handle auto seclect to find MuMu模拟器12 and use it as
         root_title                                                             
INFO           | 20:45:38.609 | Handle is handle string. oas use it as root handle    
         title                                                                  
INFO           | 20:45:38.612 | The root handle title is MuMu模拟器12 and num is      
         919496                                                                 
INFO           | 20:45:38.615 | Emulator handle structure:                            
INFO           | 20:45:38.618 | MuMu模拟器12                                          
INFO           | 20:45:38.621 | └── MuMuPlayer                                        
INFO           | 20:45:38.623 |     └── nemudisplay                                   
INFO           | 20:45:38.625 |   919496                                              
INFO           | 20:45:38.629 | └── 1182478                                           
INFO           | 20:45:38.632 |     └── 2426032                                       
INFO           | 20:45:38.634 | Emulator family: EmulatorFamily.FAMILY_MUMU           
INFO           | 20:45:38.636 | Your window screen scale rate: 1.0                    
INFO           | 20:45:38.640 | The emulator is MuMu模拟器12                          
INFO           | 20:45:38.642 | Screenshot handle num: 1182478                        
INFO           | 20:45:38.644 | Emulator screenshot size: (1280, 720)                 
INFO           | 20:45:38.646 | Screenshot interval set to 0.3s                       
INFO           | 20:45:38.651 | Scheduler: Start task `KekkaiUtilize`                 
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────── KEKKAIUTILIZE ─────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 20:45:38.662 | [Screen_size] 1280x720                                
INFO           | 20:45:38.665 | module_path:                                          
         E:\YYSJB\OnmyojiAutoScript-easy-install\tasks\KekkaiUtilize\script_task
         .py, module_name: script_task                                          
INFO           | 20:45:38.796 | UI get current page                                   
INFO           | 20:45:38.849 | [u2.Device]                                           
         Device(atx_agent_url=http://127.0.0.1:61450)                           
INFO           | 20:45:38.890 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
INFO           | 20:45:38.902 | [Device Orientation] 1 (HOME key on the right)        
WARNING  | 20:45:48.900 | Unknown ui page                                       
INFO           | 20:45:48.902 | [EMULATOR__SCREENSHOT_METHOD]                         
         ScreenshotMethod.WINDOW_BACKGROUND                                     
INFO           | 20:45:48.906 | [EMULATOR__CONTROL_METHOD] ControlMethod.MINITOUCH    
WARNING  | 20:45:48.909 | Starting from current page is not supported           
WARNING  | 20:45:48.913 | Supported page: ['page_main', 'page_summon',          
         'page_exploration', 'page_town', 'page_awake_zones', 'page_soul_zones',
         'page_realm_raid', 'page_goryou_realm', 'page_delegation',             
         'page_secret_zones', 'page_area_boss', 'page_heian_kitan',             
         'page_six_gates', 'page_bondling_fairyland', 'page_kekkai_toppa',      
         'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel',   
         'page_hyakkisen', 'page_shikigami_records', 'page_onmyodo',            
         'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team',  
         'page_collection']                                                     
WARNING  | 20:45:48.917 | Supported page: Any page with a "HOME" button on the  
         upper-right                                                            
CRITICAL    | 20:45:48.919 | Please switch to a supported page before starting oas 
INFO           | 20:45:48.925 | Game server may be under maintenance or network may be
         broken, check server status now                                        
CRITICAL    | 20:45:48.927 | Game page unknown                                     
WARNING  | 20:45:48.930 | Saving error: ./log/error/1721393148930               
INFO           | 20:45:48.977 | Notifier: OAS1                                        
INFO           | 20:45:48.979 | Script oas1 process exit                              
ERROR        | 20:45:48.983 | Error: 1                                              
![B$1(NRDGRT7)Y{SS}~7)N1B](https://github.com/user-attachments/assets/d89620fb-d05b-406e-a9aa-586c315a1c08)
![~EV_J(7U8RC$G RRM225(HP](https://github.com/user-attachments/assets/920b1a85-757b-4a28-92e2-a95af9584d8a)
![2B0FDEEX%}A}3$(NLO}3SMB](https://github.com/user-attachments/assets/c2c80057-d281-4489-8d6e-fc04d34bd465)

**Comment by runhey** [comment]
./log/error/1721393148930
这里有个报错的最终保存，有图片

**Comment by runhey** [comment]
发出来

**Comment by lvk19941208** [comment]
> 发出来

![2024-07-19_20-45-48-899988](https://github.com/user-attachments/assets/803df30f-9c8c-4291-b31d-d2b0828eddd4)
[log.txt](https://github.com/user-attachments/files/16312309/log.txt)


里面是一个全黑的图片，然后我把这个文件夹里的TXT文本也发您一下，不好意思，麻烦您了

**Comment by runhey** [comment]
换一个截屏方式

**Comment by lvk19941208** [comment]
> 换一个截屏方式

啊啊啊啊，非常感谢您，我换成ADB后，脚本运行成功了。不好意思，麻烦您这么久的时间。谢谢
