### ISSUE TITLE
缺少对应加成的情况下，oas还是会给你选一个其他加成，而不是报错

### ISSUE THREAD

**Issue by Belowen** [runhey/OnmyojiAutoScript#360]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

NFO | 16:33:47.499 | Page arrive: page_main
INFO | 16:33:47.500 | Open buff
INFO | 16:33:47.794 | Click ( 378, 48) @ GB_BUFF_1
INFO | 16:33:48.994 | Gold 50 buff
INFO | 16:33:49.436 | [GOLD_50 0.139s] ['觉醒副本掉落额外的觉醒材料',
'八岐大蛇掉落额外的御魂材料', '战斗胜利获得的金币增加100%',
'战斗胜利获得的经验增加100%', '战斗胜利获得的经验增加50%']
INFO | 16:33:49.438 | OCR [GOLD_50] detected in [0, 2, 4]
INFO | 16:33:49.439 | OCR [GOLD_50] detected in (432.0, 143.0, 325.0, 22.0)
INFO | 16:33:49.605 | Close buff
INFO | 16:33:49.900 | Click ( 381, 43) @ GB_BUFF_1
INFO | 16:33:50.202 | UI get current page
INFO | 16:33:50.205 | [UI] page_main

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by runhey** [comment]
我就想要张图，1280x720大小的
