### ISSUE TITLE
六道之门满柔风卡仿造加成界面

### ISSUE THREAD

**Issue by AU-R-O-RA** [runhey/OnmyojiAutoScript#371]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [ ] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

当六道之门柔风五级以后，再次进入仿造加成界面，会一直点击仿造，导致不能正常继续。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

大佬可以考虑在仿造加成界面加入柔风识别嘛，识别到五级之后直接退出仿造。或者在一次完整的六道过程中，记录成功获取柔风次数，等到五次之后，再进入通过战斗获取加成时，直接选择最后一个加成，进入其他获取加成界面时，直接退出，这样好像能加快六道的速度，不知道可不可行。

**Comment by runhey** [comment]
好了弄好了
