### ISSUE TITLE
更省时间的卡57结界突破办法✨

### ISSUE THREAD

**Issue by sophiiae** [runhey/OnmyojiAutoScript#377]
### 其他内容

可以添加另一个我一直用的卡57的方法供选择，前8个正常打，最后一个（右下角）退2再打，会比打8退4更便捷省时间

**Comment by sophiiae** [comment]
如果可以使用 “再次挑战” 而用退出会更好

**Comment by userDming** [comment]
推荐个我常用的，和你的类似前八个正常打，留右下角退四次再打；之后新的一轮从右下角开始，不用退可以实现18退4

**Comment by sophiiae** [comment]
> 推荐个我常用的，和你的类似前八个正常打，留右下角退四次再打；之后新的一轮从右下角开始，不用退可以实现18退4

这个也可以，但是如果没有连着打就容易忘，不一定非要最后一个，如果单个退4的话，下一轮从那个开始打就行。

**Comment by runhey** [comment]
省时间对机器来说很重要吗

**Comment by runhey** [comment]
搞不明白

**Comment by sophiiae** [comment]
省时间对机器本身确实不重要，任何程序跑的时间对机器来说都不重要，只不过是对用户来说重要罢了，我也只不过提出一种可行的操作方案作为参考而已
