### ISSUE TITLE
个人突破优化

### ISSUE THREAD

**Issue by runhey** [runhey/OnmyojiAutoScript#38]
添加一种更优化的模式，“打九退四”
每次选择打九个，固定到左上角第一个的时候退四次，保证稳定57级

**Comment by TripleEarth** [comment]
有等级卡57的大佬防守阵容，导致57不能必过。建议加一个进攻2-3次失败就刷新的机制，目前是会直接停止任务

**Comment by runhey** [comment]
该打不过还是打不过 不如直接刷新

**Comment by runhey** [comment]
补充一个，打三次就更新，期间等待五分钟的刷新时间
