### ISSUE TITLE
✨希望增加活动答题一次性答满150题选项

### ISSUE THREAD

**Issue by xh1572** [runhey/OnmyojiAutoScript#387]
### 当前不足

![PixPin_2024-08-15_12-04-54](https://github.com/user-attachments/assets/74dfb6f0-f505-4b37-99b4-c4328c0e608d)
活动答题有个排行榜奖励，同分共排名，因此答满一次150题就可以拿满奖励

### 解决方案

希望增加答满150题选项，日常可以只答满10题后故意选错，直接退出据说会吞奖励

### 其他内容

[题库.xlsx](https://github.com/user-attachments/files/16621482/default.xlsx)
附上本次活动的题库，应该是全的

**Comment by ohspecial** [comment]
已经更了

**Comment by yunxi2367** [comment]
> 已经更了

题库有问题，不是完全正确的
