### ISSUE TITLE
答题活动选错答案，可能题库不全

### ISSUE THREAD

**Issue by yunxi2367** [runhey/OnmyojiAutoScript#388]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

答题活动题库不全，会回答错误答案

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

继续答题直至150提后退出

### 截图

![报错问题](https://github.com/user-attachments/assets/008c86e3-5b32-4c1b-ba16-4d8e595b28fc)

### 还有别的吗？

我在nga上找到了最新的题库
[题库4.2.xlsx](https://github.com/user-attachments/files/16632821/4.2.xlsx)

**Comment by runhey** [comment]
早加进去了

**Comment by yunxi2367** [comment]
> 早加进去了

总是10多题开始就会选错

**Comment by yunxi2367** [comment]
> 早加进去了

测试了很多遍答题，发现原因是，出现个别题目没有点击到答案导致错误

**Comment by runhey** [comment]
测试150，成功率3/4

**Comment by yunxi2367** [comment]
> 测试150，成功率3/4

是我的设置问题吗，最高也就140
