### ISSUE TITLE
卡在困28开始界面

### ISSUE THREAD

**Issue by kiy-00** [runhey/OnmyojiAutoScript#392]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

探索模式下，卡在困28的开始界面，等待很久都没有反应，问了很多群友都没有这个情况，不知道是bug还是个人问题

### 如何复现

正常开启oasx，设置好探索模式，当到达困28开始界面时卡死

### 预期行为

正常开始刷困28副本

### 截图

![image](https://github.com/user-attachments/assets/4826a837-32df-4764-9b07-f05871a2a8f4)

**Comment by ookie23** [comment]
一样

**Comment by runhey** [comment]
你多少级，你游戏截图呢

**Comment by runhey** [comment]
日志按日志的格式上传，游戏截图归游戏截图，不会可以看其他的issue
