### ISSUE TITLE
招财上宾引发的结界经验体力盒子识别问题

### ISSUE THREAD

**Issue by 2120371896** [runhey/OnmyojiAutoScript#396]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

开通招财上宾后，经验盒子上限由80000扩充到96000，导致识别不出来卡住，而后一直重启反复这个过程

### 如何复现

1. 前往 '结界'
2. 点击 '经验食盒'
3. 识别不出来
4. 重启
5. 重复上述动作

### 预期行为

正常识别经验食盒

### 相关 Logs

```Text
INFO     2024-08-26 01:14:46.396 │ [BOX_EXP 0.006s] [60000+32000]
WARNING  2024-08-26 01:14:46.401 │ Unexpected ocr result: None
INFO     2024-08-26 01:14:46.696 │ [BOX_EXP 0.004s] [60000+32000]
WARNING  2024-08-26 01:14:46.699 │ Unexpected ocr result: None
INFO     2024-08-26 01:14:46.996 │ [BOX_EXP 0.005s] [60000+32000]
WARNING  2024-08-26 01:14:46.999 │ Unexpected ocr result: None
INFO     2024-08-26 01:14:47.297 │ [BOX_EXP 0.005s] [60000+32000]
WARNING  2024-08-26 01:14:47.301 │ Unexpected ocr result: None
INFO     2024-08-26 01:14:47.603 │ [BOX_EXP 0.007s] [60000+32000]
WARNING  2024-08-26 01:14:47.607 │ Unexpected ocr result: None
INFO     2024-08-26 01:14:47.900 │ [BOX_EXP 0.006s] [60000+32000]
```

### 截图

![2](https://github.com/user-attachments/assets/37bc5482-fc8b-4191-9e9a-8e3a4fd2f02e)
![3](https://github.com/user-attachments/assets/d4db81d5-6e5b-46df-903b-ced341082b3d)
![Uploading 4.png…]()

### 还有别的吗？

![Uploading 5.png…]()

**Comment by runhey** [comment]
要一个1280x720的图
招财上宾要氪金吗

**Comment by 2120371896** [comment]
要充30，可以拿我号

**Comment by runhey** [comment]
要图

**Comment by runhey** [comment]
我对经验不感兴趣

**Comment by 2120371896** [comment]
![1](https://github.com/user-attachments/assets/e7b2de63-7913-4cc5-8628-c18675903393)

**Comment by 2120371896** [comment]
这张应该是1280×720刚好
