### ISSUE TITLE
自定义庭院之帝庭，卷庭

### ISSUE THREAD

**Issue by yuyuyuc** [runhey/OnmyojiAutoScript#419]
- 希望大佬有时间可以加进去！![帝庭、卷庭.zip](https://github.com/user-attachments/files/16915103/default.zip)

**Comment by runhey** [comment]
这个皮肤叫啥呀为什么颜色不一样

**Comment by yuyuyuc** [comment]
> 这个皮肤叫啥呀为什么颜色不一样

天穹之境和绘世洞天，一个随时间改变，一个随登场阴阳师改变 (๑•̀‧̫•́๑)

**Comment by runhey** [comment]
不做，太难了
