### ISSUE TITLE
当期爬塔无法正常运作

### ISSUE THREAD

**Issue by wumengzhimeng** [runhey/OnmyojiAutoScript#428]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

在当期爬塔中脚本操作到ENTER SHIKIGAMI就无法继续。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

希望能正常运作

### 截图

![QQ20240911-151632](https://github.com/user-attachments/assets/b6bdb1d8-2635-454a-995b-acca3f127361)

**Comment by wumengzhimeng** [comment]
> 爬塔脚本里面的图片是4月活动的，需要手动更新，还有脚本中图片识别的部分数据，但是修改后下次启动仍会被覆盖
您好我想问一下，这个爬塔脚本的图片具体是在哪里进行修改呢

**Comment by ljxun** [comment]
不是dev分支，更新爬塔了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月11日(周三) 下午3:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [runhey/OnmyojiAutoScript] 当期爬塔无法正常运作 (Issue #428)




  
爬塔脚本里面的图片是4月活动的，需要手动更新，还有脚本中图片识别的部分数据，但是修改后下次启动仍会被覆盖
 您好我想问一下，这个爬塔脚本的图片具体是在哪里进行修改呢

**Comment by wumengzhimeng** [comment]
> 不是dev分支，更新爬塔了吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月11日(周三) 下午3:39 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [runhey/OnmyojiAutoScript] 当期爬塔无法正常运作 (Issue #428) 爬塔脚本里面的图片是4月活动的，需要手动更新，还有脚本中图片识别的部分数据，但是修改后下次启动仍会被覆盖 您好我想问一下，这个爬塔脚本的图片具体是在哪里进行修改呢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

感谢制作组大佬，问题解决了，我没看手册对不起

**Comment by jia957804321** [comment]
可以详细说一下你说怎么解决的嘛

**Comment by wumengzhimeng** [comment]
> 可以详细说一下你说怎么解决的嘛

具体可以看文档的安装这部分的教程，里面有个红色框起来的字 你应当编辑 Branch 分支为 dev 而不是master

**Comment by jia957804321** [comment]
好的谢谢

**Comment by Opeanuts** [comment]
> > 可以详细说一下你说怎么解决的嘛
> 
> 具体可以看文档的安装这部分的教程，里面有个红色框起来的字 你应当编辑 Branch 分支为 dev 而不是master

您好请问一下，是把deploy.yaml文件里的Branch: master改成Branch: dev吗，为什么我这里改完还是用不了啊

**Comment by Joelqi** [comment]
> > > 可以详细说一下你说怎么解决的嘛
> > 
> > 
> > 具体可以看文档的安装这部分的教程，里面有个红色框起来的字 你应当编辑 Branch 分支为 dev 而不是master
> 
> 您好请问一下，是把deploy.yaml文件里的Branch: master改成Branch: dev吗，为什么我这里改完还是用不了啊

你重新下一遍就好，先把config改了，然后再去运行，之前你运行的这些文件是已经从master分支下载了的，所以最简单的方式就是删掉重新下载一遍就好。
