### ISSUE TITLE
✨当期爬塔和逢魔之刻希望加上【执行任务前切换御魂】的功能

### ISSUE THREAD

**Issue by nyanyaww** [runhey/OnmyojiAutoScript#430]
### 当前不足

我再使用当期爬塔的时候需要手动切换一次御魂，虽然感觉也能接受，但是我希望加一个自动切换御魂的功能。
当然也可能是我用法不对，有更好用法可以和我说一下。

### 解决方案

当期爬塔和逢魔之刻希望加上【执行任务前切换御魂】这个小功能

**Comment by runhey** [comment]
加了

**Comment by nyanyaww** [comment]
感谢大佬！
