### ISSUE TITLE
✨添加防封优化

### ISSUE THREAD

**Issue by qinantong** [runhey/OnmyojiAutoScript#436]
### 当前不足

在周年庆999的时候发现脚本点击挑战的频率相同，有被鬼使黑的风险。

### 解决方案

其实很简单，在脚本里在每次task结束随机sleep几秒就行，甚至可以指定秒数概率，防止sleep太久效率低下。还有已经做的滑动屏幕可以适当提高一些频率。最后谢谢各位大佬的制作！

**Comment by runhey** [comment]
我觉得你说的对
![image](https://github.com/user-attachments/assets/7e73708b-d11c-4526-9a9c-a75a7c266314)
![image](https://github.com/user-attachments/assets/7e73708b-d11c-4526-9a9c-a75a7c266314)

**Comment by qinantong** [comment]
大佬，忽然想到直接改进appear_then_click函数会不会更好，在函数中设置随机延时，后面的所有调用就更安全了。

**Comment by runhey** [comment]
一点都不好。
所谓的随机休息，纯粹是毫无依据意淫出来的，用脚本到现在没有说挨这点鬼使黑的
要是想正儿八经的的防，就应该减少单次任务的次数提高任务之间的交叉性

**Comment by runhey** [comment]
已添加
