### ISSUE TITLE
探索任务使用绘卷模式时在副本内有时会将樱饼数量识别为突破券数量导致卡住

### ISSUE THREAD

**Issue by xh1572** [runhey/OnmyojiAutoScript#440]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

如题，猜测是因为大地图界面突破券数量的位置和副本内界面樱饼数量在同一位置导致的，打完一个怪回到选怪界面时有可能触发，有时打一两个怪就会出现又是打十几个会出现

与选择up类型应该无关，我尝试过全部和只打达摩，都有可能触发

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

或许修改一下绘卷模式检测突破券的时机就好？比如只有退回到大地图界面时检测。

### 截图

![image](https://github.com/user-attachments/assets/0b59a795-51c8-4b2e-a7b3-5524207977db)

**Comment by runhey** [comment]
这个日志很异常，多发几次这种异常情况的日志

**Comment by runhey** [comment]
INFO     2024-09-15 00:17:11.430 │ <<< SOLO >>>                                                                         
INFO     2024-09-15 00:17:11.848 │ [REALM_RAID_NUMBER 0.003s] [11/30]                                                   
INFO     2024-09-15 00:17:12.335 │ [E_EXPLORATION_LEVEL_NUMBER 0.098s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:17:12.829 │ [E_EXPLORATION_LEVEL_NUMBER 0.092s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:17:12.830 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [2]                                     
INFO     2024-09-15 00:17:12.831 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1085.0, 495.0, 131.0, 28.0)            
INFO     2024-09-15 00:17:12.832 │ Click (1118,  520) @ E_EXPLORATION_LEVEL_NUMBER                                      
INFO     2024-09-15 00:17:15.498 │ [REALM_RAID_NUMBER1 0.003s] [1/30]                                                   
INFO     2024-09-15 00:17:15.815 │ Click ( 952,  522) @ RES_E_EXPLORATION_CLICK                                         
INFO     2024-09-15 00:17:18.643 │ Click ( 942,  268) @ RES_NORMAL_BATTLE_BUTTON                                        
───────────────────────────── GENERAL BATTLE START ─────────────────────────────



INFO     2024-09-15 00:19:28.655 │ Get reward success                                                                   
INFO     2024-09-15 00:19:29.442 │ Click ( 781,  456) @ RES_BATTLE_REWARD                                               
INFO     2024-09-15 00:19:30.389 │ Click (1040,  284) @ UI_UI_REWARD                                                    
INFO     2024-09-15 00:19:31.286 │ Get reward success                                                                   
INFO     2024-09-15 00:19:32.138 │ [REALM_RAID_NUMBER 0.003s] [/30]                                                     
WARNING  2024-09-15 00:19:32.139 │ Unexpected ocr result: None                                                          
INFO     2024-09-15 00:19:32.621 │ [E_EXPLORATION_LEVEL_NUMBER 0.094s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:19:33.105 │ [E_EXPLORATION_LEVEL_NUMBER 0.089s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:19:33.107 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [2]                                     
INFO     2024-09-15 00:19:33.108 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1085.0, 494.0, 131.0, 29.0)            
INFO     2024-09-15 00:19:33.109 │ Click (1161,  518) @ E_EXPLORATION_LEVEL_NUMBER                                      
INFO     2024-09-15 00:19:34.236 │ [REALM_RAID_NUMBER1 0.003s] [3/30]                                                   
INFO     2024-09-15 00:19:34.550 │ Click ( 943,  519) @ RES_E_EXPLORATION_CLICK                                         
INFO     2024-09-15 00:19:37.386 │ Click ( 924,  293) @ RES_NORMAL_BATTLE_BUTTON                                        
───────────────────────────── GENERAL BATTLE START ─────────────────────────────


INFO     2024-09-15 00:21:08.533 │ Click (1086,  184) @ UI_UI_REWARD                                                    
INFO     2024-09-15 00:21:08.942 │ Get reward success                                                                   
INFO     2024-09-15 00:21:09.860 │ Swipe (1100,  150) -> ( 405,  146)                                                   
INFO     2024-09-15 00:21:10.855 │ [REALM_RAID_NUMBER 0.003s] [5/30]                                                    
INFO     2024-09-15 00:21:11.329 │ [E_EXPLORATION_LEVEL_NUMBER 0.092s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:21:11.797 │ [E_EXPLORATION_LEVEL_NUMBER 0.092s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:21:11.798 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [2]                                     
INFO     2024-09-15 00:21:11.799 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1085.0, 494.0, 131.0, 29.0)            
INFO     2024-09-15 00:21:11.800 │ Click (1140,  513) @ E_EXPLORATION_LEVEL_NUMBER                                      
INFO     2024-09-15 00:21:12.861 │ [REALM_RAID_NUMBER1 0.004s] [5/30]                                                   
INFO     2024-09-15 00:21:13.167 │ Click ( 980,  551) @ RES_E_EXPLORATION_CLICK                                         
INFO     2024-09-15 00:21:16.025 │ Click ( 939,  297) @ RES_NORMAL_BATTLE_BUTTON                                        
───────────────────────────── GENERAL BATTLE START ─────────────────────────────
INFO     2024-09-15 00:21:16.925 │ GENERAL BATTLE START                                                                 
INFO     2024-09-15 00:21:16.925 │ Current count: 12    


INFO     2024-09-15 00:23:28.813 │ Click (1234,  537) @ GB_REWARD                                                       
INFO     2024-09-15 00:23:29.612 │ Boss battle, minions cnt 18                                                          
INFO     2024-09-15 00:23:31.976 │ Swipe (1093,  154) -> ( 399,  154)                                                   
INFO     2024-09-15 00:23:31.977 │ Swipe y distance is 0                                                                
INFO     2024-09-15 00:23:32.923 │ [REALM_RAID_NUMBER 0.003s] [7/30]                                                    
INFO     2024-09-15 00:23:33.417 │ [E_EXPLORATION_LEVEL_NUMBER 0.091s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:23:33.951 │ [E_EXPLORATION_LEVEL_NUMBER 0.093s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:23:33.954 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [2]                                     
INFO     2024-09-15 00:23:33.955 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1084.0, 493.0, 133.0, 31.0)            
INFO     2024-09-15 00:23:33.956 │ Click (1153,  517) @ E_EXPLORATION_LEVEL_NUMBER                                      
INFO     2024-09-15 00:23:35.832 │ [REALM_RAID_NUMBER1 0.002s] [7/30]                                                   
INFO     2024-09-15 00:23:36.198 │ Click ( 963,  534) @ RES_E_EXPLORATION_CLICK                                         
INFO     2024-09-15 00:23:39.084 │ Click ( 937,  296) @ RES_NORMAL_BATTLE_BUTTON                                        
───────────────────────────── GENERAL BATTLE START ─────────────────────────────
INFO     2024-09-15 00:23:39.973 │ GENERAL BATTLE START                                                                 
INFO     2024-09-15 00:23:39.975 │ Current count: 19                 


                                                        
INFO     2024-09-15 00:25:29.227 │ Swipe (1094,  165) -> ( 417,  160)                                                   
INFO     2024-09-15 00:25:30.562 │ Click ( 569,  484) @ RES_BATTLE_REWARD                                               
INFO     2024-09-15 00:25:31.500 │ Click (1099,  417) @ UI_UI_REWARD                                                    
INFO     2024-09-15 00:25:32.389 │ Get reward success                                                                   
INFO     2024-09-15 00:25:33.286 │ [REALM_RAID_NUMBER 0.003s] [7/30]                                                    
INFO     2024-09-15 00:25:33.762 │ [E_EXPLORATION_LEVEL_NUMBER 0.089s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:25:34.228 │ [E_EXPLORATION_LEVEL_NUMBER 0.092s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:25:34.230 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [2]                                     
INFO     2024-09-15 00:25:34.232 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1085.0, 494.0, 131.0, 29.0)            
INFO     2024-09-15 00:25:34.233 │ Click (1163,  507) @ E_EXPLORATION_LEVEL_NUMBER                                      
INFO     2024-09-15 00:25:35.364 │ [REALM_RAID_NUMBER1 0.002s] [7/30]                                                   
INFO     2024-09-15 00:25:35.681 │ Click ( 989,  536) @ RES_E_EXPLORATION_CLICK                                         
INFO     2024-09-15 00:25:38.491 │ Click ( 938,  265) @ RES_NORMAL_BATTLE_BUTTON                                        
───────────────────────────── GENERAL BATTLE START ─────────────────────────────
INFO     2024-09-15 00:25:39.363 │ GENERAL BATTLE START                                                                 
INFO     2024-09-15 00:25:39.365 │ Current count: 25                                 


                                                 
INFO     2024-09-15 00:28:18.680 │ Click ( 781,  473) @ RES_BATTLE_REWARD                                               
INFO     2024-09-15 00:28:19.595 │ Click (1022,  173) @ UI_UI_REWARD                                                    
INFO     2024-09-15 00:28:20.486 │ Get reward success                                                                   
INFO     2024-09-15 00:28:21.359 │ [REALM_RAID_NUMBER 0.002s] [10/30]                                                   
INFO     2024-09-15 00:28:21.828 │ [E_EXPLORATION_LEVEL_NUMBER 0.092s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:28:22.308 │ [E_EXPLORATION_LEVEL_NUMBER 0.091s] ['第二十六章', '第二十七章', '第二十八章']       
INFO     2024-09-15 00:28:22.309 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [2]                                     
INFO     2024-09-15 00:28:22.310 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1085.0, 494.0, 131.0, 29.0)            
INFO     2024-09-15 00:28:22.311 │ Click (1159,  495) @ E_EXPLORATION_LEVEL_NUMBER                                      
INFO     2024-09-15 00:28:23.406 │ [REALM_RAID_NUMBER1 0.003s] [10/30]                                                  
INFO     2024-09-15 00:28:23.734 │ Click ( 907,  529) @ RES_E_EXPLORATION_CLICK                                         
INFO     2024-09-15 00:28:26.479 │ Click ( 953,  282) @ RES_NORMAL_BATTLE_BUTTON                                        
───────────────────────────── GENERAL BATTLE START ─────────────────────────────
INFO     2024-09-15 00:28:27.362 │ GENERAL BATTLE START                                                                 
INFO     2024-09-15 00:28:27.363 │ Current count: 33                          


INFO     2024-09-15 00:30:12.808 │ Get reward                                                                           
INFO     2024-09-15 00:30:13.107 │ Click ( 661,  617) @ GB_REWARD                                                       
INFO     2024-09-15 00:30:14.920 │ Click ( 218,  313) @ GB_REWARD                                                       
INFO     2024-09-15 00:30:15.649 │ Boss battle, minions cnt 38                                                          
INFO     2024-09-15 00:30:17.563 │ Swipe (1102,  161) -> ( 400,  153)                                                   
INFO     2024-09-15 00:30:18.500 │ Treasure box appear, get it.                                                         
INFO     2024-09-15 00:30:18.882 │ Click (  40,  476) @ RES_TREASURE_BOX_CLICK                                          
INFO     2024-09-15 00:30:19.704 │ [REALM_RAID_NUMBER 0.003s] [11/30]                                                   
INFO     2024-09-15 00:30:20.163 │ [E_EXPLORATION_LEVEL_NUMBER 0.096s] ['第二十六章', '第二十七章', '第二十八章',       
         '阴界']                                                                                                        
INFO     2024-09-15 00:30:20.615 │ [E_EXPLORATION_LEVEL_NUMBER 0.088s] ['第二十六章', '第二十七章', '第二十八章',       
         '阴界']                                                                                                        
INFO     2024-09-15 00:30:20.617 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [2]                                     
INFO     2024-09-15 00:30:20.618 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1085.0, 494.0, 130.0, 29.0)            
INFO     2024-09-15 00:30:20.620 │ Click (1161,  510) @ E_EXPLORATION_LEVEL_NUMBER                                      
WARNING  2024-09-15 00:30:23.968 │ Wait until appear RES_E_EXPLORATION_CLICK timeout                                    
INFO     2024-09-15 00:30:24.821 │ [E_EXPLORATION_LEVEL_NUMBER 0.092s] ['第二十六章', '第二十七章', '第二十八章',       
         '阴界']                                                                                                        
INFO     2024-09-15 00:30:24.822 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [2]                                     
INFO     2024-09-15 00:30:24.823 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1085.0, 494.0, 130.0, 29.0)            
INFO     2024-09-15 00:30:24.825 │ Click (1182,  500) @ E_EXPLORATION_LEVEL_NUMBER                                      
WARNING  2024-09-15 00:30:27.965 │ Wait until appear RES_E_EXPLORATION_CLICK timeout                                    
INFO     2024-09-15 00:30:28.792 │ [E_EXPLORATION_LEVEL_NUMBER 0.093s] ['第二十六章', '第二十七章', '第二十八章',       
         '阴界']                                                                                                        
INFO     2024-09-15 00:30:28.794 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in [2]                                     
INFO     2024-09-15 00:30:28.795 │ OCR [E_EXPLORATION_LEVEL_NUMBER] detected in (1085.0, 495.0, 131.0, 28.0)            
INFO     2024-09-15 00:30:28.796 │ Click (1160,  522) @ E_EXPLORATION_LEVEL_NUMBER                                      
INFO     2024-09-15 00:30:29.893 │ [REALM_RAID_NUMBER1 0.003s] [11/30]                                                  
INFO     2024-09-15 00:30:30.234 │ Click ( 983,  541) @ RES_E_EXPLORATION_CLICK                                         
INFO     2024-09-15 00:30:33.053 │ Click ( 940,  274) @ RES_NORMAL_BATTLE_BUTTON                                        
───────────────────────────── GENERAL BATTLE START ─────────────────────────────
INFO     2024-09-15 00:30:33.939 │ GENERAL BATTLE START                                                                 
INFO     2024-09-15 00:30:33.940 │ Current count: 39

**Comment by ljxun** [comment]
其实就是还在探索里面识别成在大世界了，判断
大世界情况多加点条件就可以

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月15日(周日) 凌晨0:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [runhey/OnmyojiAutoScript] 探索任务使用绘卷模式时在副本内有时会将樱饼数量识别为突破券数量导致卡住 (Issue #440)




 
这个日志很异常，多发几次这种异常情况的日志

**Comment by xh1572** [comment]
> 这个日志很异常，多发几次这种异常情况的日志

![image](https://github.com/user-attachments/assets/ee7e5805-d9db-445f-a7d3-cdc0f2530dd4)
![image](https://github.com/user-attachments/assets/58e4961b-585b-4bc6-874c-85cc9b122a06)
![image](https://github.com/user-attachments/assets/80348ef8-e11b-4b19-b75b-0ec434b4656a)
![image](https://github.com/user-attachments/assets/d18d7335-ebea-41b2-8cef-d65ea5bc6ae3)
找了几个，这两天碰到还挺多的

**Comment by xh1572** [comment]
[cid:da94b831-6420-4ae0-bc25-7a22167229af]
今天的
________________________________

**Comment by xh1572** [comment]
![image](https://github.com/user-attachments/assets/f4da55c4-aa2d-447d-b739-41fc1b412e33)

**Comment by runhey** [comment]
> 其实就是还在探索里面识别成在大世界了，判断 大世界情况多加点条件就可以
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月15日(周日) 凌晨0:40 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [runhey/OnmyojiAutoScript] 探索任务使用绘卷模式时在副本内有时会将樱饼数量识别为突破券数量导致卡住 (Issue #440) 这个日志很异常，多发几次这种异常情况的日志 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

很有道理，按照这个思路改了，试一下

**Comment by xh1572** [comment]
私密马赛绘卷已经开完了不刷探索了，改了应该就没问题了，这个issue可以关了应该，辛苦了

 

发件人: huangrunheng ***@***.***> 
发送时间: 2024年9月15日 23:29
收件人: runhey/OnmyojiAutoScript ***@***.***>
抄送: xh1572 ***@***.***>; Author ***@***.***>
主题: Re: [runhey/OnmyojiAutoScript] 探索任务使用绘卷模式时在副本内有时会将樱饼数量识别为突破券数量导致卡住 (Issue #440)

 

其实就是还在探索里面识别成在大世界了，判断 大世界情况多加点条件就可以
…
---原始邮件--- 发件人: @.> 发送时间: 2024年9月15日(周日) 凌晨0:40 收件人: @.>; 抄送: @.>; 主题: Re: [runhey/OnmyojiAutoScript] 探索任务使用绘卷模式时在副本内有时会将樱饼数量识别为突破券数量导致卡住 (Issue #440 <https://github.com/runhey/OnmyojiAutoScript/issues/440> ) 这个日志很异常，多发几次这种异常情况的日志 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

很有道理，按照这个思路改了，试一下
