### ISSUE TITLE
✨运行时间长导致日志多，界面卡住

### ISSUE THREAD

**Issue by 327836130** [runhey/OnmyojiAutoScript#443]
### 当前不足

运行时间一长，咱们界面就卡住了，点不动，好像是日志太多，清理一下就能恢复

### 解决方案

希望可以出一个日志定期清理的功能，保持咱们使用的时候流畅起来

**Comment by runhey** [comment]
不会，OASX就是设计成启动完就叉掉的

**Comment by 327836130** [comment]
您的邮件已收到，谢谢
