### ISSUE TITLE
希望增加颜色匹配方法

### ISSUE THREAD

**Issue by ljxun** [runhey/OnmyojiAutoScript#445]
### 当前不足

有的图片颜色不同appear方法识别效果是相同的
希望增加颜色匹配方法

### 解决方案

def color_image_same(file: str,file1: str):
    # 读取两张图片
    img1 = cv2.imread(file)
    img2 = cv2.imread(file1)

    # 计算直方图
    hist1 = cv2.calcHist([img1], [0], None, [256], [0, 256])
    hist2 = cv2.calcHist([img2], [0], None, [256], [0, 256])

    # 归一化直方图
    cv2.normalize(hist1, hist1)
    cv2.normalize(hist2, hist2)

    # 计算直方图的相似度
    similarity = cv2.compareHist(hist1, hist2, cv2.HISTCMP_CORREL)

    print(f'颜色直方图相似度: {similarity}')
    return similarity

### 其他内容

![Screenshots_create_daoguan](https://github.com/user-attachments/assets/205b6e3d-8cd8-4825-828b-def7b0113a37)
![Screenshots_create_daoguan_ok](https://github.com/user-attachments/assets/586c1582-cb20-42f4-b61b-bf863c680951)

具体实现靠你了

**Comment by ljxun** [comment]
![MuMu12-20240909-201659](https://github.com/user-attachments/assets/e187b4a1-6945-4372-bc3c-f7bdd9daefb7)
![MuMu12-20240914-122509](https://github.com/user-attachments/assets/36e0acdb-fc31-45c1-bd66-07aed123de16)

**Comment by ohspecial** [comment]
你看看module.atom.image.py这个文件的sift_match跟match_mean_color用不用得上？

**Comment by endlesswxk** [comment]
不需要颜色识别， 我认为每次进来都点击一下就可以了，
