### ISSUE TITLE
网络错误不知道原因

### ISSUE THREAD

**Issue by 1623917407** [runhey/OnmyojiAutoScript#448]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

启动登入之后更改设置的时候突然网络错误无法打开页面，并且出现警告

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
网络错误
错课代码: This exception was thrown because the response has a status code of500 and RequestOotions validatestatus was copfigured to throw for this status code
The status code of 500 has the following meaning: "Server error - the server failed to fulfil an apparently valid request"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your reguest code or you have to fix the server code
500
```

### 截图

![78c45b2c59ad17805ff68bce2ed1b00b](https://github.com/user-attachments/assets/90bc4e1e-e5fd-463f-b161-b431019036f9)

**Comment by runhey** [comment]
https://github.com/runhey/OnmyojiAutoScript/issues/276

我也不知道你什么原因

**Comment by 1623917407** [comment]
> #276
> 
> 我也不知道你什么原因

刚刚尝试了一下重装，好像问题出在oas身上，网络不可访问了，oas重装都不能从数据库下来，挂梯子也没用，只能等过段时间看看会不会恢复正常了

**Comment by luoaolalala** [comment]
我在OASX的界面里也出现了相同胡错误，另外补充一个OAS里的报错：
![QQ20240918-161325](https://github.com/user-attachments/assets/d66fcfe3-200d-4a19-a0fa-651f2211d334)

不知道怎么解决，我重装OAS了
