### ISSUE TITLE
窗口句柄错误

### ISSUE THREAD

**Issue by 20021025** [runhey/OnmyojiAutoScript#450]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

运行脚本的时候日志显示无效的窗口句柄

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
error: (1400, 'GetWindowRect', '无效的窗口句柄。')                     
INFO           | 19:19:58.046 | Script oas1 process exit                              
ERROR        | 19:19:58.048 | Error: 1
```

**Comment by runhey** [comment]
### 一、你知道怎么正确提问吗
https://runhey.github.io/OnmyojiAutoScript-website/docs/user-manual/scientific-question
### 二、不是写了 窗口句柄 不对吗
这个明明设置不对，反正就是文档爱看不看，上来酷酷就问
![image](https://github.com/user-attachments/assets/2069ca66-9ca3-4651-8506-53a4218601e0)
### 三、你给的日志就三条
我要给你猜呢
### 四、不会用这个平台可以去学别傻里傻气的
搜索知道吗
![image](https://github.com/user-attachments/assets/849573f6-3a4a-4e7c-8dd8-8605c271ffc0)

**Comment by 20021025** [comment]
大佬🐎的好，已经解决了，谢谢大佬
