### ISSUE TITLE
运行百鬼进入后不撒豆子

### ISSUE THREAD

**Issue by 1104800668** [runhey/OnmyojiAutoScript#452]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

窗口化模式下进入，oas正常运行至百鬼撒豆界面，oas停止运行弹窗并报错。报错代码为：
IndexError: index 719 is out of bounds for axis 0 with size 495

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
INFO     2024-09-16 23:50:49.754 │ INVITE FRIEND
INFO     2024-09-16 23:50:50.050 │ Click ( 180,  603) @ HYA_HINVITE
INFO     2024-09-16 23:50:50.966 │ Click ( 507,  246) @ friend_1
INFO     2024-09-16 23:50:51.254 │ Invite friend done
INFO     2024-09-16 23:50:51.551 │ Click (1072,  647) @ HYA_HACCESS
INFO     2024-09-16 23:50:53.346 │ Click (1186,  651) @ HYA_HSTART
INFO     2024-09-16 23:50:53.679 │ Click ( 657,  425) @ hselect_2
INFO     2024-09-16 23:50:55.468 │ Click (1214,  584) @ HYA_HSTART
INFO     2024-09-16 23:50:56.357 │ Add stuck record: BATTLE_STATUS_S
INFO     2024-09-16 23:50:56.360 │ <<< START HYAKKIYAKOU >>>
ERROR    2024-09-16 23:50:56.365 │ IndexError: index 719 is out of bounds for axis 0 with size 495
         ╭───────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────╮         │ D:\hero\22\jingling\OnmyojiAutoScript-easy-install\OnmyojiAutoScript-easy-install\script.py:352 in run      │         │                                                                                                             │         │   349 │   │   │   module_path = str(Path.cwd() / 'tasks' / command / (module_name+'.py'))                   │         │   350 │   │   │   logger.info(f'module_path: {module_path}, module_name: {module_name}')                    │         │   351 │   │   │   task_module = load_module(module_name, module_path)                                       │         │ ❱ 352 │   │   │   task_module.ScriptTask(config=self.config, device=self.device).run()                      │         │   353 │   │   except TaskEnd:                                                                               │         │   354 │   │   │   return True                                                                               │         │   355 │   │   except GameNotRunningError as e:                                                              │         │                                                                                                             │         │ ╭──────────────────────────────────────────────── locals ─────────────────────────────────────────────────╮ │         │ │     command = 'Hyakkiyakou'                                                                             │ │         │ │           e = IndexError('index 719 is out of bounds for axis 0 with size 495')                         │ │         │ │ module_name = 'script_task'                                                                             │ │         │ │ module_path = 'D:\\hero\\22\\jingling\\OnmyojiAutoScript-easy-install\\OnmyojiAutoScript-easy-instal'+… │ │
         │ │        self = <script.Script object at 0x00000000042D37F0>                                              │ │         │ │ task_module = <module 'script_task' from                                                                │ │         │ │               'D:\\hero\\22\\jingling\\OnmyojiAutoScript-easy-install\\OnmyojiAutoScript-easy-install\… │ │
         │ ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────╯ │         │                                                                                                             │         │ D:\hero\22\jingling\OnmyojiAutoScript-easy-install\OnmyojiAutoScript-easy-install\tasks\Hyakkiyakou\script_ │         │ task.py:139 in run                                                                                          │         │                                                                                                             │         │   136 │   │   │   │   logger.info('Hyakkiyakou time limit out')                                             │         │   137 │   │   │   │   break                                                                                 │         │   138 │   │   │                                                                                             │         │ ❱ 139 │   │   │   self.one()                                                                                │         │   140 │   │   │   hya_count += 1                                                                            │         │   141 │   │                                                                                                 │         │   142 │   │   while 1:                                                                                      │         │                                                                                                             │         │ ╭────────────────────────────── locals ──────────────────────────────╮                                      │         │ │  hya_count = 0                                                     │                                      │         │ │ limit_time = Time(0, 20)                                           │                                      │         │ │       self = <script_task.ScriptTask object at 0x0000000016902590> │                                      │         │ ╰────────────────────────────────────────────────────────────────────╯                                      │         │                                                                                                             │         │ D:\hero\22\jingling\OnmyojiAutoScript-easy-install\OnmyojiAutoScript-easy-install\tasks\Hyakkiyakou\script_ │         │ task.py:181 in one                                                                                          │         │                                                                                                             │         │   178 │   │   if self._config.debug_config.hya_show:                                                        │         │   179 │   │   │   self.debugger.show_start()                                                                │         │   180 │   │   while 1:                                                                                      │         │ ❱ 181 │   │   │   self.fast_screenshot()                                                                    │         │   182 │   │   │   if self.appear(self.I_HEND):                                                              │         │   183 │   │   │   │   break                                                                                 │         │   184 │   │   │   if not self.appear(self.I_CHECK_RUN):                                                     │         │                                                                                                             │         │ ╭────────────────────────────────── locals ───────────────────────────────────╮                             │         │ │   click_button = <module.atom.click.RuleClick object at 0x00000000166EC100> │                             │         │ │ init_bean_flag = False                                                      │                             │         │ │    last_action = [0, 0, False, 10]                                          │                             │         │ │           self = <script_task.ScriptTask object at 0x0000000016902590>      │                             │         │ ╰─────────────────────────────────────────────────────────────────────────────╯                             │         │                                                                                                             │         │ D:\hero\22\jingling\OnmyojiAutoScript-easy-install\OnmyojiAutoScript-easy-install\tasks\Hyakkiyakou\slave\h │         │ ya_device.py:33 in fast_screenshot                                                                          │         │                                                                                                             │         │   30 │   │   self.hya_screenshot_interval.wait()                                                            │         │   31 │   │   self.hya_screenshot_interval.reset()                                                           │         │   32 │   │   self.device.image = self.device.screenshot_window_background()                                 │         │ ❱ 33 │   │   if image_black(self.device.image):                                                             │         │   34 │   │   │   logger.error('Screenshot image is black, try again')                                       │         │   35 │   │   │   raise RequestHumanTakeover('Screenshot image is black, try again')                         │         │   36 │   │   if self.hya_fs_check_timer.reached():                                                          │         │                                                                                                             │         │ ╭─────────────────────────── locals ───────────────────────────╮                                            │         │ │ self = <script_task.ScriptTask object at 0x0000000016902590> │                                            │         │ ╰──────────────────────────────────────────────────────────────╯                                            │         │                                                                                                             │         │ D:\hero\22\jingling\OnmyojiAutoScript-easy-install\OnmyojiAutoScript-easy-install\tasks\Hyakkiyakou\slave\h │         │ ya_device.py:13 in image_black                                                                              │         │                                                                                                             │         │   10                                                                                                        │         │   11 def image_black(img) -> bool:                                                                          │         │   12 │   for y, x in [(0, 0), (719, 1279), (719, 0), (0, 1279)]:                                            │         │ ❱ 13 │   │   if np.all(img[y, x] != 0):                                                                     │         │   14 │   │   │   return False                                                                               │         │   15 │   return True                                                                                        │         │   16                                                                                                        │         │                                                                                                             │         │ ╭──────────────── locals ─────────────────╮                                                                 │         │ │ img = array([[[0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   ...,                      │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0]],               │                                                                 │         │ │       │                                 │                                                                 │         │ │       │      [[0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   ...,                      │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0]],               │                                                                 │         │ │       │                                 │                                                                 │         │ │       │      [[0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   ...,                      │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0]],               │                                                                 │         │ │       │                                 │                                                                 │         │ │       │      ...,                       │                                                                 │         │ │       │                                 │                                                                 │         │ │       │      [[0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   ...,                      │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0]],               │                                                                 │         │ │       │                                 │                                                                 │         │ │       │      [[0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   ...,                      │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0]],               │                                                                 │         │ │       │                                 │                                                                 │         │ │       │      [[0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   ...,                      │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0],                │                                                                 │         │ │       │   │   [0, 0, 0]]], dtype=uint8) │                                                                 │         │ │   x = 1279                              │                                                                 │         │ │   y = 719                               │                                                                 │         │ ╰─────────────────────────────────────────╯                                                                 │         ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ 
IndexError: index 719 is out of bounds for axis 0 with size 495
WARNING  2024-09-16 23:50:57.079 │ Saving error: ./log/error/1726501857079
INFO     2024-09-16 23:50:58.227 │ Notifier: OAS1
INFO     2024-09-16 23:50:58.230 │ Script oas1 process exit
ERROR    2024-09-16 23:50:58.233 │ Error: 1
```

### 截图

模拟器设置：
![捕获1](https://github.com/user-attachments/assets/e39392a3-2d4e-4ac3-9eaa-9f3113f3c090)
百鬼设置：
![捕获3](https://github.com/user-attachments/assets/c684060a-f77b-4570-810f-fb6588425b58)
![捕获2](https://github.com/user-attachments/assets/a95d2ffc-1562-4ab1-81f3-8108ae85d08c)

**Comment by runhey** [comment]
![image](https://github.com/user-attachments/assets/299b0493-a862-4feb-a5e1-b24eed360d69)
这个日志你让人怎么看

**Comment by 1104800668** [comment]
> ![图像](https://private-user-images.githubusercontent.com/74492025/368018643-299b0493-a862-4feb-a5e1-b24eed360d69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTI1OTIsIm5iZiI6MTcyNjU1MjI5MiwicGF0aCI6Ii83NDQ5MjAyNS8zNjgwMTg2NDMtMjk5YjA0OTMtYTg2Mi00ZmViLWE1ZTEtYjI0ZWVkMzYwZDY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA1NTEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MTE3NThhYzlmZTQ4ODU4YWIyNzFjYjEzZjRiYjg3ODAyMmUxNmI5MThhMmY0ZWQ1MzhkN2VlODkzNjIzNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DZOXiZehr4l5lpCyfgVwiH8wx9pIo7jKUh8m72vReyk)这个日志你让人怎么看

不好意思不好意思，直接从oas复制的。
日志报错：
INFO           | 14:12:57.849 | Start scheduler loop: oas1                            
INFO           | 14:12:57.873 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 14:12:57.879 | [Task] Hyakkiyakou (Enable, 5, 2023-01-01 00:00:00)   
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 14:12:57.890 |   DEVICE                                              
INFO           | 14:12:57.896 | [AdbBinary]                                           
         D:/hero/22/jingling/OnmyojiAutoScript-easy-install/OnmyojiAutoScript-ea
         sy-install/toolkit/Lib/site-packages/adbutils/binaries/adb.exe         
INFO           | 14:12:57.904 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 14:12:57.912 | <<< DETECT DEVICE >>>                                 
INFO           | 14:12:57.920 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 14:12:57.929 | 127.0.0.1:7555                                        
INFO           | 14:12:57.946 | connected to 127.0.0.1:16384                          
INFO           | 14:12:57.963 | [AdbDevice] AdbDevice(serial=127.0.0.1:16384)         
INFO           | 14:12:57.973 | <<< DETECT PACKAGE >>>                                
INFO           | 14:12:57.983 | Get package list                                      
INFO           | 14:12:58.278 | Here are the available packages in device             
         "127.0.0.1:16384", copy to Alas.Emulator.PackageName to use it         
INFO           | 14:12:58.286 | com.netease.onmyoji.wyzymnqsd_cps                     
INFO           | 14:12:58.294 | Auto package detection found only one package, using  
         it                                                                     
INFO           | 14:12:58.302 | Server changed, release resources                     
INFO           | 14:12:58.307 | [PackageName] com.netease.onmyoji.wyzymnqsd_cps       
INFO           | 14:12:58.314 | <<< HANDLE >>>                                        
INFO           | 14:12:58.319 | Handle is handle string. oas use it as root handle    
         title                                                                  
INFO           | 14:12:58.324 | The root handle title is MuMu模拟器12 and num is      
         458992                                                                 
INFO           | 14:12:58.338 | Emulator handle structure:                            
INFO           | 14:12:58.344 | MuMu模拟器12                                          
INFO           | 14:12:58.349 | └── MuMuPlayer                                        
INFO           | 14:12:58.355 |     └── nemudisplay                                   
INFO           | 14:12:58.360 |   458992                                              
INFO           | 14:12:58.366 | └── 197732                                            
INFO           | 14:12:58.370 |     └── 525544                                        
INFO           | 14:12:58.375 | Emulator family: EmulatorFamily.FAMILY_MUMU           
INFO           | 14:12:58.381 | Your window screen scale rate: 1.0                    
INFO           | 14:12:58.386 | The emulator is MuMu模拟器12                          
INFO           | 14:12:58.393 | Screenshot handle num: 197732                         
INFO           | 14:12:58.399 | Emulator screenshot size: (1792, 1008)                
INFO           | 14:12:58.405 | Screenshot interval set to 0.3s                       
INFO           | 14:12:58.409 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 14:12:58.427 | Connecting to local emulator, using host 10.176.64.210
INFO           | 14:12:58.434 | Reverse server listening on 10.176.64.210:20302,      
         client can send data to 10.176.64.210:20302                            
INFO           | 14:12:58.454 | sdk_ver: 32                                           
INFO           | 14:12:58.504 | [nc command] ['nc']                                   
INFO           | 14:12:58.794 | [Screen_size] 1280x720                                
INFO           | 14:12:58.802 | module_path:                                          
         D:\hero\22\jingling\OnmyojiAutoScript-easy-install\OnmyojiAutoScript-ea
         sy-install\tasks\Hyakkiyakou\script_task.py, module_name: script_task  
INFO           | 14:12:59.235 | UI get current page                                   
INFO           | 14:12:59.247 | [UI] page_main                                        
INFO           | 14:12:59.255 | <<< UI GOTO PAGE_HYAKKIYAKOU >>>                      
INFO           | 14:12:59.326 | Page switch: page_main -> page_town                   
INFO           | 14:12:59.368 | Click ( 738,  301) @ PAGE_MAIN_GOTO_TOWN              
INFO           | 14:12:59.374 | <<< MINITOUCH INIT >>>                                
INFO           | 14:12:59.402 | [Device Orientation] 1 (HOME key on the right)        
INFO           | 14:12:59.409 | Create forward: ForwardItem(serial='127.0.0.1:16384', 
         local='tcp:20026', remote='localabstract:minitouch')                   
INFO           | 14:12:59.420 |      v 1                                              
INFO           | 14:12:59.425 | ^ 10 720 1280 0                                       
INFO           | 14:12:59.431 |  $ 26041                                              
INFO           | 14:12:59.436 | minitouch running on port: 20026, pid: 26041          
INFO           | 14:12:59.443 | max_contact: 10; max_x: 720; max_y: 1280;             
         max_pressure: 0                                                        
INFO           | 14:12:59.783 | roi_front size changed to 66x75                       
INFO           | 14:13:01.319 | Page switch: page_town -> page_hyakkiyakou            
INFO           | 14:13:01.327 | Click ( 883,  228) @ PAGE_TOWN_GOTO_HYAKKIYAKOU       
INFO           | 14:13:01.927 | Page arrive: page_hyakkiyakou                         
WARNING  | 14:13:01.935 | Page Error                                            
──────────────────────────────── INVITE FRIEND ─────────────────────────────────
INFO           | 14:13:01.942 | INVITE FRIEND                                         
INFO           | 14:13:02.220 | Click ( 162,  604) @ HYA_HINVITE                      
INFO           | 14:13:03.103 | Click ( 544,  250) @ friend_1                         
INFO           | 14:13:03.460 | Invite friend done                                    
INFO           | 14:13:03.726 | Click (1098,  651) @ HYA_HACCESS                      
INFO           | 14:13:05.865 | Click (1123,  647) @ HYA_HSTART                       
INFO           | 14:13:06.203 | Click ( 645,  488) @ hselect_2                        
INFO           | 14:13:07.987 | Click (1152,  563) @ HYA_HSTART                       
INFO           | 14:13:08.924 | Add stuck record: BATTLE_STATUS_S                     
INFO           | 14:13:08.930 | <<< START HYAKKIYAKOU >>>                             
INFO           | 14:13:08.935 | Reset Debugger Thread Environment                     
INFO           | 14:13:08.940 | OAS Track Debugger show image start

**Comment by runhey** [comment]
你给的最新的没有报错

**Comment by runhey** [comment]
这些看了吗
![image](https://github.com/user-attachments/assets/38118e9f-1cfa-4506-9ebb-1ae9118335b5)

**Comment by 1104800668** [comment]
> 这些看了吗 ![image](https://private-user-images.githubusercontent.com/74492025/368030438-38118e9f-1cfa-4506-9ebb-1ae9118335b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NTQ1ODksIm5iZiI6MTcyNjU1NDI4OSwicGF0aCI6Ii83NDQ5MjAyNS8zNjgwMzA0MzgtMzgxMThlOWYtMWNmYS00NTA2LTllYmItMWFlOTExODMzNWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA2MjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MmZhNmIxNGUzYTlhOWNlYTE2OGQ1NjhkZWZiZmU4OGJiY2I5MGQ3MDEzZGVmMmYzODY2NjY4MmFlYTQ4YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tl2lbl3NEfouFKN3g_jn1TeBItlpULoXi3ikvf3OHIw)

大佬，这些都有看过，但不太相似。在我昨晚重启系统后，报错内容似乎不一样了。我再贴两张图请您看一下

**Comment by 1104800668** [comment]
进入百鬼选完人后：跳出弹窗oas tracker，后续就没有响应了，日志也截然而止
![捕获 4PNG](https://github.com/user-attachments/assets/f6c4c30a-f2bb-4d5d-81b1-11c608be5538)



日志：════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 14:29:47.915 | Start scheduler loop: oas1                            
INFO           | 14:29:47.935 | Pending tasks: ['Restart', 'Hyakkiyakou']             
INFO           | 14:29:47.941 | [Task] Restart (Enable, 0, 2024-09-17 14:21:40)       
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 14:29:47.950 |   DEVICE                                              
INFO           | 14:29:47.954 | [AdbBinary]                                           
         D:/hero/22/jingling/OnmyojiAutoScript-easy-install/OnmyojiAutoScript-ea
         sy-install/toolkit/Lib/site-packages/adbutils/binaries/adb.exe         
INFO           | 14:29:47.961 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 14:29:47.968 | <<< DETECT DEVICE >>>                                 
INFO           | 14:29:47.973 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 14:29:47.981 | 127.0.0.1:16384                                       
INFO           | 14:29:47.986 | 127.0.0.1:7555                                        
INFO           | 14:29:47.995 | already connected to 127.0.0.1:16384                  
INFO           | 14:29:48.002 | [AdbDevice] AdbDevice(serial=127.0.0.1:16384)         
INFO           | 14:29:48.007 | <<< DETECT PACKAGE >>>                                
INFO           | 14:29:48.012 | Get package list                                      
INFO           | 14:29:48.369 | Here are the available packages in device             
         "127.0.0.1:16384", copy to Alas.Emulator.PackageName to use it         
INFO           | 14:29:48.374 | com.netease.onmyoji.wyzymnqsd_cps                     
INFO           | 14:29:48.379 | Auto package detection found only one package, using  
         it                                                                     
INFO           | 14:29:48.383 | Server changed, release resources                     
INFO           | 14:29:48.387 | [PackageName] com.netease.onmyoji.wyzymnqsd_cps       
INFO           | 14:29:48.392 | <<< HANDLE >>>                                        
INFO           | 14:29:48.397 | Handle is handle string. oas use it as root handle    
         title                                                                  
INFO           | 14:29:48.401 | The root handle title is MuMu模拟器12 and num is      
         458992                                                                 
INFO           | 14:29:48.405 | Emulator handle structure:                            
INFO           | 14:29:48.410 | MuMu模拟器12                                          
INFO           | 14:29:48.414 | └── MuMuPlayer                                        
INFO           | 14:29:48.417 |     └── nemudisplay                                   
INFO           | 14:29:48.422 |   458992                                              
INFO           | 14:29:48.427 | └── 197732                                            
INFO           | 14:29:48.431 |     └── 525544                                        
INFO           | 14:29:48.435 | Emulator family: EmulatorFamily.FAMILY_MUMU           
INFO           | 14:29:48.441 | Your window screen scale rate: 1.0                    
INFO           | 14:29:48.445 | The emulator is MuMu模拟器12                          
INFO           | 14:29:48.449 | Screenshot handle num: 197732                         
INFO           | 14:29:48.454 | Emulator screenshot size: (1792, 1008)                
INFO           | 14:29:48.458 | Screenshot interval set to 0.3s                       
INFO           | 14:29:48.462 | Skip task `Restart` at scheduler start                
INFO           | 14:29:48.477 | Delay task `restart` to 2024-09-18 09:05:00           
         (success=True, server_update=True)                                     
INFO           | 14:29:48.549 | [restart.scheduler.next_run] 2024-09-18 09:05:00      
INFO           | 14:29:48.571 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 14:29:48.577 | [Task] Hyakkiyakou (Enable, 5, 2023-01-01 00:00:00)   
INFO           | 14:29:48.582 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 14:29:48.599 | Connecting to local emulator, using host 10.176.64.210
INFO           | 14:29:48.605 | Reverse server listening on 10.176.64.210:20006,      
         client can send data to 10.176.64.210:20006                            
INFO           | 14:29:48.632 | sdk_ver: 32                                           
INFO           | 14:29:48.688 | [nc command] ['nc']                                   
INFO           | 14:29:49.150 | [Screen_size] 1280x720                                
INFO           | 14:29:49.156 | module_path:                                          
         D:\hero\22\jingling\OnmyojiAutoScript-easy-install\OnmyojiAutoScript-ea
         sy-install\tasks\Hyakkiyakou\script_task.py, module_name: script_task  
INFO           | 14:29:49.569 | UI get current page                                   
INFO           | 14:29:49.581 | [UI] page_main                                        
INFO           | 14:29:49.588 | <<< UI GOTO PAGE_HYAKKIYAKOU >>>                      
INFO           | 14:29:49.607 | Page switch: page_main -> page_town                   
INFO           | 14:29:49.648 | Click ( 708,  288) @ PAGE_MAIN_GOTO_TOWN              
INFO           | 14:29:49.652 | <<< MINITOUCH INIT >>>                                
INFO           | 14:29:49.720 | [Device Orientation] 1 (HOME key on the right)        
INFO           | 14:29:49.727 | Reuse forward: ForwardItem(serial='127.0.0.1:16384',  
         local='tcp:20026', remote='localabstract:minitouch')                   
INFO           | 14:29:49.734 |      v 1                                              
INFO           | 14:29:49.740 | ^ 10 720 1280 0                                       
INFO           | 14:29:49.744 |  $ 26041                                              
INFO           | 14:29:49.750 | minitouch running on port: 20026, pid: 26041          
INFO           | 14:29:49.754 | max_contact: 10; max_x: 720; max_y: 1280;             
         max_pressure: 0                                                        
INFO           | 14:29:50.121 | roi_front size changed to 66x75                       
INFO           | 14:29:51.643 | Page switch: page_town -> page_hyakkiyakou            
INFO           | 14:29:51.650 | Click ( 908,  186) @ PAGE_TOWN_GOTO_HYAKKIYAKOU       
INFO           | 14:29:52.240 | Page arrive: page_hyakkiyakou                         
WARNING  | 14:29:52.246 | Page Error                                            
──────────────────────────────── INVITE FRIEND ─────────────────────────────────
INFO           | 14:29:52.253 | INVITE FRIEND                                         
INFO           | 14:29:52.571 | Click ( 159,  620) @ HYA_HINVITE                      
INFO           | 14:29:53.472 | Click ( 578,  251) @ friend_1                         
INFO           | 14:29:53.782 | Invite friend done                                    
INFO           | 14:29:54.071 | Click (1093,  556) @ HYA_HACCESS                      
INFO           | 14:29:56.166 | Click (1129,  628) @ HYA_HSTART                       
INFO           | 14:29:56.547 | Click ( 652,  337) @ hselect_2                        
INFO           | 14:29:58.357 | Click (1144,  591) @ HYA_HSTART                       
INFO           | 14:29:58.662 | Click ( 644,  575) @ hselect_2                        
INFO           | 14:30:00.505 | Click (1205,  652) @ HYA_HSTART                       
INFO           | 14:30:01.395 | Add stuck record: BATTLE_STATUS_S                     
INFO           | 14:30:01.400 | <<< START HYAKKIYAKOU >>>                             
INFO           | 14:30:01.404 | Reset Debugger Thread Environment                     
INFO           | 14:30:01.408 | Hyakkiyakou Save Result Mode Enabled                  
INFO           | 14:30:01.413 | OAS Track Debugger show image start

**Comment by 1104800668** [comment]
![捕获 4PNG](https://github.com/user-attachments/assets/d1d7215b-3585-4219-8905-ef95df61d0d9)

**Comment by runhey** [comment]
INFO | 14:29:48.449 | Screenshot handle num: 197732
INFO | 14:29:48.454 | Emulator screenshot size: (1792, 1008)


不要拉伸模拟器

**Comment by 1104800668** [comment]
OK了大佬，看其他帖子里不要缩放，就一直想着全屏窗口运行，糊涂了。感谢感谢
