### ISSUE TITLE
网络错误：系统检测到在一个调用中尝试使用指针参数时的无效指针地址

### ISSUE THREAD

**Issue by kbpb2000** [runhey/OnmyojiAutoScript#461]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

![E R0 X7PRSV_HSGO%ZSXA 3](https://github.com/user-attachments/assets/bb347535-7a1a-460b-9cef-2c4e26e342f7)
![FW3@L` {_)`)DT9}GTA`EVU](https://github.com/user-attachments/assets/b76f342c-28a3-4fce-881a-349ea2aae4d5)
![KC1L2{S$21OC_N~ATF4}F01](https://github.com/user-attachments/assets/1f5bd9bf-08ed-48b5-9f8c-22dc8f77302c)
用笔记本就一直这样，不太清楚是什么原因，防火墙看着好像也没有屏蔽，台式机就没出现这个情况

### 如何复现

1. 前往 'oasx'
2. 点击 '右下角再回去点击login'
3. 出现问题

### 还有别的吗？

希望能到得到解决，感谢佬

**Comment by runhey** [comment]
![image](https://github.com/user-attachments/assets/1faccbc0-9fff-42ee-9067-c76e9a591964)

**Comment by runhey** [comment]
这句话安装失败了

**Comment by runhey** [comment]
oasx 在启动后就不会管后端后面的日志。所以你应该换一个启动oas的方式来看日志

**Comment by kbpb2000** [comment]
![image](https://github.com/user-attachments/assets/fca29bf3-fd9a-4f6d-9101-b8d3048089e5)
没有传完，我单独启动oas会出现这个情况，是不是杀毒软件给删了什么东西啊

**Comment by runhey** [comment]
管理员执行 
netsh winsock reset 
然后重启电脑

**Comment by runhey** [comment]
LmeSzinc给说过的

**Comment by kbpb2000** [comment]
那个网络修复.bat吗，我看过这个issue，但是我找不到这个文件

**Comment by runhey** [comment]
不懂你说啥子

**Comment by kbpb2000** [comment]
犯傻了，没事没事，我试一下这个法子

**Comment by kbpb2000** [comment]
我喜欢你，感谢大佬
