### ISSUE TITLE
显示网络错误 错误代码 500

### ISSUE THREAD

**Issue by Onlier1** [runhey/OnmyojiAutoScript#462]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

一直报错，点什么都没用，错误代码500.The server has encountered a situation it does not know how to handle.

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
因为没法正常使用所以没有错误log。
```

### 截图

![20C%HMJL7VO$__~6J}DZ96H](https://github.com/user-attachments/assets/d8d33b45-cc1d-4cb2-bd6b-4cf384eceb0d)

### 还有别的吗？

好像是使用过程中更改了某一项的设置，之后就一直不能用了，曾经重装了一次，短暂的使用了几分钟后就又报错了。

**Comment by runhey** [comment]
按你的意思是配置异常，在./config文件夹下找到对应的配置文件，然后删掉

**Comment by Onlier1** [comment]
> 应该是叫oas1.json

解决了 感谢佬
