### ISSUE TITLE
百鬼撒豆动作不生效，勾选跟踪功能后弹出窗口是黑屏，切换点击模式仍然没成功

### ISSUE THREAD

**Issue by MaxYi666** [runhey/OnmyojiAutoScript#467]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [ ] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

百鬼撒豆动作不生效，勾选跟踪功能后弹出窗口是黑屏，切换点击模式仍然没成功

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by runhey** [comment]
****系列

#450
