### ISSUE TITLE
地域鬼王 挑战次数

### ISSUE THREAD

**Issue by TripleEarth** [runhey/OnmyojiAutoScript#47]
无法识别挑战次数，比如声望只够挑战2个，挑战完后其他 挑战 按钮会变灰，但是依然不停的尝试点击挑战

**Comment by runhey** [comment]
有在配置里面设置挑战boss的个数吗

**Comment by runhey** [comment]
突然想到一开始写的时候是按照，boss热度来进行挑战，如果有的人没有对应的范围权限，那么也会死点某个boss

**Comment by runhey** [comment]
所有有必要改一下

**Comment by runhey** [comment]
已修改
