### ISSUE TITLE
希望悬赏功能不去猪猪第七层

### ISSUE THREAD

**Issue by ghg11** [runhey/OnmyojiAutoScript#471]
### 描述

柴犬悬赏默认去猪猪皮肤塔第七层 但是难度较大 而且悬赏功能没有更换御魂预设功能 造成悬赏任务经常重启（超时）甚至黄点 希望可以把猪塔7拉黑（

**Comment by runhey** [comment]
谁是猪猪

**Comment by runhey** [comment]
![image](https://github.com/user-attachments/assets/4d25f9d2-a099-4c74-a294-038b93714286)

**Comment by runhey** [comment]
https://github.com/runhey/OnmyojiAutoScript/commit/c9f77c5990c5d6efd5191d92c221d2a86d8a88e3

**Comment by runhey** [comment]
这个版本支持优先使用探索完成任务
