### ISSUE TITLE
✨期待将来完善保存配置方案功能，以及导入导出配置

### ISSUE THREAD

**Issue by loseLight** [runhey/OnmyojiAutoScript#483]
### 当前不足

说一说个人的一些想法，希望oas可以变得越来越完美。
**背景：**
目前保存配置只能通过左边栏的“+”来保存管理。

如果用左边栏的“+”来创建保存一个游戏账号的多个不同的配置有些缺点：

1. 每个配置都会展示出来，占用界面空间不说，而且每个都还可以独立执行，这在逻辑上不合理。一个账号应该只能执行一个才符合现实。（随然不会有哪个傻x一个账号同时执行n个，我只是说逻辑上）。
2. 左边栏的“+”应该是用来创建账号副本的，一个账号创建一个，而不是用来创建一个账号下的多个不同配置。
3. 只能增加、不能删除。要删除只能去config目录删除后重新启动，才能显示修改。

### 解决方案

1. 一个账号的多种不同配置，应该是在账号设置界面有一个下拉选择框进行选择，例如：点击下拉框，显示1级菜单：配置文件1、配置文件2等，鼠标停在配置文件1上，显示配置文件1的2级菜单：导入全部配置、只导入御魂配置、只导入业原火配置等。
2. 当然，这些改善要对oasx的界面做一些调整，。

关于**_导入配置_**功能的建议：
建议设计成支持导入全部、或者只导入其中的某个、几个配置。

**Comment by runhey** [comment]
感谢你的建议，不过我得给你泼冷水，这并不是由于其他缘由，而是单纯的遵循最初的设计理念。

OAS最终目标是实现全自动，虽然目前还不行。起手就是”一个游戏账号多个配置“属实把我乐了，应该是一个配置就够了，那之后就不用看了。

参考alas，https://github.com/LmeSzinc/AzurLaneAutoScript/issues/687#issuecomment-953849913

**Comment by loseLight** [comment]
哈哈哈，原来如此，思虑不周让您见笑了。
这样的话，在全自动完成之前，确实没必要弄配置方案这一块。
不过要全自动的话，八岐大蛇的层数那一块，建议加一个功能，解决“周一周二刷第十层，周三周四刷十一层，周五周六刷十二层...”之类的问题，。

**Comment by loseLight** [comment]
虽然没全自动，但已经很强了，全自动不远了
最后，感谢oas开发小队的辛勤付出，么么哒！！！

**Comment by loseLight** [comment]
虽然没全自动，但已经很强了，全自动不远了
最后，感谢oas开发小队的辛勤付出，么么哒！！！
