### ISSUE TITLE
关于斗鸡的使用门槛

### ISSUE THREAD

**Issue by sitxiaochen** [runhey/OnmyojiAutoScript#484]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

使用限制了初试分数不能低于1200，导致咸鱼玩家无法挂1600荣誉

我把相关的这个数值改成低于1000就可以正常使用

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
相关日志没有保留，之后我直接运行的.py文件。
```

### 截图

![B6ABAD7A57120B68C90373BB3D73ED2F](https://github.com/user-attachments/assets/9aaa9194-fb90-46f2-a725-6629866daf6f)

### 还有别的吗？

如果不是强制的参数希望能降低到1000分玩家也能咸鱼挂机刷1600荣誉。

**Comment by sitxiaochen** [comment]
OnmyojiAutoScript-easy-install\tasks\Duel\script_task.py

**Comment by runhey** [comment]
两段很难吗
