### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by ximenq123** [runhey/OnmyojiAutoScript#491]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

运行是不报错并且持续显示 
Page switch: page_main -> page_guild                  
INFO           | 21:42:49.076 | Page switch: page_main -> page_guild                  
INFO           | 21:42:53.485 | Page switch: page_main -> page_guild                  
INFO           | 21:42:57.868 | Page switch: page_main -> page_guild                  
![db13c26e-4ddc-4277-82e5-616d3d014d41](https://github.com/user-attachments/assets/6782e1a4-7e33-479f-aba0-70414715e001)

INFO           | 21:43:02.347 | Page switch: page_main -> page_guild     

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by ximenq123** [comment]
![4b30deb583378cfa8a6104841a3d1358](https://github.com/user-attachments/assets/9c951e6a-0f07-4604-a6ba-f9a3071a041d)
但是点击式神录就会自己返回主界面然后就不动了

**Comment by ximenq123** [comment]
![Uploading 4b30deb583378cfa8a6104841a3d1358.png…]()

**Comment by runhey** [comment]
把那个卷轴的改为默认的

**Comment by runhey** [comment]
![image](https://github.com/user-attachments/assets/576ff41a-3ba6-4d57-949b-6da40de8666f)

**Comment by ximenq123** [comment]
好的谢谢博主我2b了
