### ISSUE TITLE
悬赏封印优先打探索导致的问题，通关探索后概率出现的妖气封印及年兽有可能挡住左侧悬赏索引导致卡死

### ISSUE THREAD

**Issue by xh1572** [runhey/OnmyojiAutoScript#495]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

![image](https://github.com/user-attachments/assets/abd08e1a-5645-4224-afe7-dd6985e4eef3)
如图，不算高概率问题，这几天应该只出现了两次，并且因为妖气封印及年兽持续时间都不长，自动重启个两三次大概就会消失然后任务就又能继续了。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题
[2024-10-15_小号 - 副本.txt](https://github.com/user-attachments/files/17372135/2024-10-15_.-.txt)

### 预期行为

应该只需添加一下对这种情况的识别，然后滑动索引条即可？幸苦大佬了。
另外，对于不缺式神挑战券的玩家，如果能有优先使用式神挑战券的选项就好了，当然这个并不是很必要。再次感谢大佬的辛苦付出。

**Comment by runhey** [comment]
已经切回默认挑战券了
