### ISSUE TITLE
Please switch to a supported page before starting oas 

### ISSUE THREAD

**Issue by wanghekai** [runhey/OnmyojiAutoScript#496]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

INFO           | 11:57:24.750 | get_current_scene=True                                
INFO           | 11:57:25.273 | [DOKAN_SUCCEEDED 0.516s] []                           
INFO           | 11:57:25.278 | UI get current page                                   
INFO           | 11:57:25.320 | roi_front size changed to 66x75                       
INFO           | 11:57:25.437 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
INFO           | 11:57:25.457 | [Device Orientation] 1 (HOME key on the right)        
WARNING  | 11:57:35.491 | Unknown ui page                                       
INFO           | 11:57:35.493 | [EMULATOR__SCREENSHOT_METHOD]                         
         ScreenshotMethod.DROIDCAST_RAW                                         
INFO           | 11:57:35.495 | [EMULATOR__CONTROL_METHOD] ControlMethod.MINITOUCH    
WARNING  | 11:57:35.497 | Starting from current page is not supported           
WARNING  | 11:57:35.499 | Supported page: ['page_main', 'page_summon',          
         'page_exploration', 'page_town', 'page_awake_zones', 'page_soul_zones',
         'page_realm_raid', 'page_goryou_realm', 'page_delegation',             
         'page_secret_zones', 'page_area_boss', 'page_heian_kitan',             
         'page_six_gates', 'page_bondling_fairyland', 'page_kekkai_toppa',      
         'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel',   
         'page_hyakkisen', 'page_shikigami_records', 'page_onmyodo',            
         'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team',  
         'page_collection']                                                     
WARNING  | 11:57:35.502 | Supported page: Any page with a "HOME" button on the  
         upper-right                                                            
CRITICAL    | 11:57:35.505 | Please switch to a supported page before starting oas 
INFO           | 11:57:35.507 | Game server may be under maintenance or network may be
         broken, check server status now                                        
CRITICAL    | 11:57:35.509 | Game page unknown                                     
WARNING  | 11:57:35.513 | Saving error: ./log/error/1728964655513               
INFO           | 11:57:35.771 | Notifier: OAS1                                        
INFO           | 11:57:35.774 | Script oas1 process exit                              
ERROR        | 11:57:35.776 | Error: 1                                              

### 如何复现

完成所有配置，根据文档，然后点击 调度器 开关 启动。
开始可以工作，后来感觉mumu版本升级之后（不确定）出现的这个问题。
[log.txt](https://github.com/user-attachments/files/17372327/log.txt)

**Comment by ohspecial** [comment]
把报错截图放上来，按配置改成默认的主题没，还有人物不能挡住町中等等其他入口的位置。

**Comment by runhey** [comment]
看这个图
WARNING | 11:57:35.513 | Saving error: ./log/error/1728964655513

**Comment by ch-hang** [comment]
我也是这个问题 
![Uploading 2024-11-30_02-39-29-187158.png…]()
