### ISSUE TITLE
百鬼不出现识别框（截屏失效）

### ISSUE THREAD

**Issue by crazy-czy** [runhey/OnmyojiAutoScript#498]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

先附上日志
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 23:44:47.042 | Start scheduler loop: oas1                            
INFO           | 23:44:47.055 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 23:44:47.057 | [Task] Hyakkiyakou (Enable, 5, 2024-10-17 23:18:00)   
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 23:44:47.061 |   DEVICE                                              
INFO           | 23:44:47.062 | [AdbBinary]                                           
         C:/Users/Administrator/Desktop/OAS/OnmyojiAutoScript-easy-install/toolk
         it/Lib/site-packages/adbutils/binaries/adb.exe                         
INFO           | 23:44:47.063 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 23:44:47.065 | <<< DETECT DEVICE >>>                                 
INFO           | 23:44:47.066 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 23:44:47.068 | 127.0.0.1:16384                                       
INFO           | 23:44:47.073 | already connected to 127.0.0.1:16384                  
INFO           | 23:44:47.076 | [AdbDevice] AdbDevice(serial=127.0.0.1:16384 )        
INFO           | 23:44:47.078 | [PackageName] com.netease.onmyoji                     
INFO           | 23:44:47.080 | <<< HANDLE >>>                                        
INFO           | 23:44:47.081 | Handle is handle string. oas use it as root handle    
         title                                                                  
INFO           | 23:44:47.083 | The root handle title is mumu模拟器12 and num is      
         4393270                                                                
INFO           | 23:44:47.085 | Emulator handle structure:                            
INFO           | 23:44:47.086 | mumu模拟器12                                          
INFO           | 23:44:47.087 | └── MuMuPlayer                                        
INFO           | 23:44:47.089 |     └── nemudisplay                                   
INFO           | 23:44:47.090 |  4393270                                              
INFO           | 23:44:47.092 | └── 852874                                            
INFO           | 23:44:47.093 |     └── 1705994                                       
INFO           | 23:44:47.095 | Emulator family: EmulatorFamily.FAMILY_MUMU           
INFO           | 23:44:47.096 | Your window screen scale rate: 1.0                    
INFO           | 23:44:47.097 | The emulator is MuMu模拟器12                          
INFO           | 23:44:47.099 | Screenshot handle num: 852874                         
INFO           | 23:44:47.100 | Emulator screenshot size: (1280, 720)                 
INFO           | 23:44:47.101 | Screenshot interval set to 0.3s                       
INFO           | 23:44:47.103 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 23:44:47.639 | [Screen_size] 1280x720                                
INFO           | 23:44:47.642 | module_path:                                          
         C:\Users\Administrator\Desktop\OAS\OnmyojiAutoScript-easy-install\tasks
         \Hyakkiyakou\script_task.py, module_name: script_task                  
INFO           | 23:44:47.885 | UI get current page                                   
INFO           | 23:44:47.922 | roi_front size changed to 66x75                       
INFO           | 23:44:48.047 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
WARNING  | 23:44:48.049 | Game not running                                      
INFO           | 23:44:48.050 | Task call: restart                                    
INFO           | 23:44:48.064 | Scheduler: End task `Hyakkiyakou`                     
INFO           | 23:44:48.075 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 23:44:48.077 | [Task] Hyakkiyakou (Enable, 5, 2024-10-17 23:18:00)   
INFO           | 23:44:48.079 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 23:44:48.606 | module_path:                                          
         C:\Users\Administrator\Desktop\OAS\OnmyojiAutoScript-easy-install\tasks
         \Hyakkiyakou\script_task.py, module_name: script_task                  
INFO           | 23:44:48.610 | UI get current page                                   
INFO           | 23:44:48.627 | [UI] page_town                                        
INFO           | 23:44:48.629 | <<< UI GOTO PAGE_HYAKKIYAKOU >>>                      
INFO           | 23:44:48.668 | Page switch: page_town -> page_hyakkiyakou            
INFO           | 23:44:48.672 | Click ( 914,  178) @ PAGE_TOWN_GOTO_HYAKKIYAKOU       
INFO           | 23:44:49.835 | Page arrive: page_hyakkiyakou                         
WARNING  | 23:44:49.838 | Page Error                                            
──────────────────────────────── INVITE FRIEND ─────────────────────────────────
INFO           | 23:44:49.841 | INVITE FRIEND                                         
INFO           | 23:44:50.385 | Click ( 190,  578) @ HYA_HINVITE                      
INFO           | 23:44:51.785 | Click ( 551,  255) @ friend_1                         
INFO           | 23:44:52.287 | Click ( 887,  244) @ friend_2                         
INFO           | 23:44:52.885 | Invite friend done                                    
INFO           | 23:44:53.405 | Click (1084,  562) @ HYA_HACCESS                      
INFO           | 23:44:55.711 | Click (1185,  590) @ HYA_HSTART                       
INFO           | 23:44:56.239 | Click ( 985,  573) @ hselect_3                        
INFO           | 23:44:57.733 | Click (1206,  577) @ HYA_HSTART                       
INFO           | 23:44:59.258 | Add stuck record: BATTLE_STATUS_S                     
INFO           | 23:44:59.260 | <<< START HYAKKIYAKOU >>>                             
INFO           | 23:44:59.261 | Reset Debugger Thread Environment                     
INFO           | 23:44:59.263 | OAS Track Debugger show image start                
OAS无法自动追踪鬼王，没有移动模拟器位置，没有伸缩模拟器，设置如下

   

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/user-attachments/assets/d08e078d-7550-43bc-a2b5-4964670085fc)
![image](https://github.com/user-attachments/assets/ef676319-96a4-4656-84e9-1b49751e0401)
![image](https://github.com/user-attachments/assets/bd3a222c-c915-4dda-ba1b-8e70bc4b5f40)
![image](https://github.com/user-attachments/assets/755679fa-48ca-4632-9878-c56ca6aa881c)
![image](https://github.com/user-attachments/assets/1114a30b-0365-45af-86a7-71f100d2a956)
![image](https://github.com/user-attachments/assets/774e0f3e-aad5-4443-86d3-5bd7b990476c)
![image](https://github.com/user-attachments/assets/6d69b0cb-58e5-4764-9b29-946f42f399b7)

**Comment by crazy-czy** [comment]
![1](https://github.com/user-attachments/assets/d481031d-dbe8-4340-8d38-6dff18183331)
![2](https://github.com/user-attachments/assets/465a3105-127b-4fce-9631-d51f14a62d20)
![3](https://github.com/user-attachments/assets/23bd6041-db45-4505-9f22-f9d206cac68e)
![4](https://github.com/user-attachments/assets/5245c1d4-579b-4683-a49e-6385462ff13f)
上边图片貌似无法正常识别

**Comment by runhey** [comment]
甚至没有拉豆子

**Comment by runhey** [comment]
#305  好像跟这个有点像

**Comment by runhey** [comment]
你应当确认一下window_background截屏能否正确使用，具体的。
将 脚本>模拟器截屏方案 切换到window_background，然后跑一下其他任务

**Comment by crazy-czy** [comment]
> 你应当确认一下window_background截屏能否正确使用，具体的。 将 脚本>模拟器截屏方案 切换到window_background，然后跑一下其他任务

INFO           | 12:15:39.666 | [Task] Hyakkiyakou (Enable, 5, 2024-10-17 23:18:00)   
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 12:15:39.669 |   DEVICE                                              
INFO           | 12:15:39.671 | [AdbBinary]                                           
         C:/Users/Administrator/Desktop/OAS/OnmyojiAutoScript-easy-install/toolk
         it/Lib/site-packages/adbutils/binaries/adb.exe                         
INFO           | 12:15:39.673 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 12:15:39.675 | <<< DETECT DEVICE >>>                                 
INFO           | 12:15:39.677 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 12:15:39.679 | 127.0.0.1:16384                                       
INFO           | 12:15:39.680 | 127.0.0.1:7555                                        
INFO           | 12:15:39.684 | already connected to 127.0.0.1:16384                  
INFO           | 12:15:39.685 | [AdbDevice] AdbDevice(serial=127.0.0.1:16384 )        
INFO           | 12:15:39.686 | [PackageName] com.netease.onmyoji.wyzymnqsd_cps       
INFO           | 12:15:39.688 | <<< HANDLE >>>                                        
INFO           | 12:15:39.690 | Handle is handle num. oas use it as root handle num   
INFO           | 12:15:39.691 | Handle number 852274 is valid                         
INFO           | 12:15:39.693 | The root handle title is mumu模拟器12 and num is      
         852274                                                                 
INFO           | 12:15:39.694 | Emulator handle structure:                            
INFO           | 12:15:39.695 | mumu模拟器12                                          
INFO           | 12:15:39.697 | └── MuMuPlayer                                        
INFO           | 12:15:39.698 |     └── nemudisplay                                   
INFO           | 12:15:39.699 |   852274                                              
INFO           | 12:15:39.700 | └── 133210                                            
INFO           | 12:15:39.702 |     └── 788240                                        
INFO           | 12:15:39.703 | Emulator family: EmulatorFamily.FAMILY_MUMU           
INFO           | 12:15:39.705 | Your window screen scale rate: 1.0                    
INFO           | 12:15:39.707 | The emulator is MuMu模拟器12                          
INFO           | 12:15:39.708 | Screenshot handle num: 133210                         
INFO           | 12:15:39.709 | Emulator screenshot size: (1280, 720)                 
INFO           | 12:15:39.711 | Screenshot interval set to 0.3s                       
INFO           | 12:15:39.712 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 12:15:40.329 | [Screen_size] 1280x720                                
INFO           | 12:15:40.332 | module_path:                                          
         C:\Users\Administrator\Desktop\OAS\OnmyojiAutoScript-easy-install\tasks
         \Hyakkiyakou\script_task.py, module_name: script_task                  
INFO           | 12:15:40.549 | UI get current page                                   
INFO           | 12:15:40.555 | [UI] page_main                                        
INFO           | 12:15:40.559 | <<< UI GOTO PAGE_HYAKKIYAKOU >>>                      
INFO           | 12:15:40.567 | Page switch: page_main -> page_town                   
INFO           | 12:15:40.589 | Click ( 728,  297) @ PAGE_MAIN_GOTO_TOWN              
INFO           | 12:15:41.187 | roi_front size changed to 66x75                       
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 12:15:56.444 | Start scheduler loop: oas1                            
INFO           | 12:15:56.456 | Pending tasks: ['Hyakkiyakou']                        
INFO           | 12:15:56.459 | [Task] Hyakkiyakou (Enable, 5, 2024-10-17 23:18:00)   
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 12:15:56.462 |   DEVICE                                              
INFO           | 12:15:56.464 | [AdbBinary]                                           
         C:/Users/Administrator/Desktop/OAS/OnmyojiAutoScript-easy-install/toolk
         it/Lib/site-packages/adbutils/binaries/adb.exe                         
INFO           | 12:15:56.466 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 12:15:56.467 | <<< DETECT DEVICE >>>                                 
INFO           | 12:15:56.469 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 12:15:56.470 | 127.0.0.1:16384                                       
INFO           | 12:15:56.471 | 127.0.0.1:7555                                        
INFO           | 12:15:56.478 | already connected to 127.0.0.1:16384                  
INFO           | 12:15:56.481 | [AdbDevice] AdbDevice(serial=127.0.0.1:16384 )        
INFO           | 12:15:56.482 | [PackageName] com.netease.onmyoji.wyzymnqsd_cps       
INFO           | 12:15:56.484 | <<< HANDLE >>>                                        
INFO           | 12:15:56.485 | Handle is handle num. oas use it as root handle num   
INFO           | 12:15:56.487 | Handle number 852274 is valid                         
INFO           | 12:15:56.489 | The root handle title is mumu模拟器12 and num is      
         852274                                                                 
INFO           | 12:15:56.490 | Emulator handle structure:                            
INFO           | 12:15:56.492 | mumu模拟器12                                          
INFO           | 12:15:56.493 | └── MuMuPlayer                                        
INFO           | 12:15:56.494 |     └── nemudisplay                                   
INFO           | 12:15:56.495 |   852274                                              
INFO           | 12:15:56.496 | └── 133210                                            
INFO           | 12:15:56.498 |     └── 788240                                        
INFO           | 12:15:56.499 | Emulator family: EmulatorFamily.FAMILY_MUMU           
INFO           | 12:15:56.500 | Your window screen scale rate: 1.0                    
INFO           | 12:15:56.502 | The emulator is MuMu模拟器12                          
INFO           | 12:15:56.503 | Screenshot handle num: 133210                         
INFO           | 12:15:56.505 | Emulator screenshot size: (1280, 720)                 
INFO           | 12:15:56.507 | Screenshot interval set to 0.3s                       
INFO           | 12:15:56.509 | Scheduler: Start task `Hyakkiyakou`                   
════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 12:15:56.527 | [Screen_size] 1280x720                                
INFO           | 12:15:56.529 | module_path:                                          
         C:\Users\Administrator\Desktop\OAS\OnmyojiAutoScript-easy-install\tasks
         \Hyakkiyakou\script_task.py, module_name: script_task                  
INFO           | 12:15:56.762 | UI get current page                                   
INFO           | 12:15:56.797 | roi_front size changed to 66x75                       
INFO           | 12:15:56.876 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
INFO           | 12:15:56.901 | [Device Orientation] 1 (HOME key on the right)        
WARNING  | 12:16:06.853 | Unknown ui page                                       
INFO           | 12:16:06.855 | [EMULATOR__SCREENSHOT_METHOD]                         
         ScreenshotMethod.WINDOW_BACKGROUND                                     
INFO           | 12:16:06.856 | [EMULATOR__CONTROL_METHOD] ControlMethod.ADB          
WARNING  | 12:16:06.858 | Starting from current page is not supported           
WARNING  | 12:16:06.859 | Supported page: ['page_main', 'page_summon',          
         'page_exploration', 'page_town', 'page_awake_zones', 'page_soul_zones',
         'page_realm_raid', 'page_goryou_realm', 'page_delegation',             
         'page_secret_zones', 'page_area_boss', 'page_heian_kitan',             
         'page_six_gates', 'page_bondling_fairyland', 'page_kekkai_toppa',      
         'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel',   
         'page_hyakkisen', 'page_shikigami_records', 'page_onmyodo',            
         'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team',  
         'page_collection']                                                     
WARNING  | 12:16:06.862 | Supported page: Any page with a "HOME" button on the  
         upper-right                                                            
CRITICAL    | 12:16:06.863 | Please switch to a supported page before starting oas 
INFO           | 12:16:06.864 | Game server may be under maintenance or network may be
         broken, check server status now                                        
CRITICAL    | 12:16:06.866 | Game page unknown                                     
WARNING  | 12:16:06.869 | Saving error: ./log/error/1729224966869               
INFO           | 12:16:06.923 | Notifier: OAS1                                        
INFO           | 12:16:06.924 | Script oas1 process exit                              
ERROR        | 12:16:06.925 | Error: 1  
按照您的方法使用window_background时，百鬼夜行运行报错，附上日志

**Comment by crazy-czy** [comment]
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO           | 12:19:08.903 | Start scheduler loop: oas1                            
INFO           | 12:19:08.915 | No task pending                                       
INFO           | 12:19:08.917 | [Task] DailyTrifles (Enable, 5, 2024-10-19 12:18:12)  
INFO           | 12:19:08.919 | Wait until 2024-10-19 12:18:12 for task `DailyTrifles`
INFO           | 12:19:08.921 | Goto main page during wait                            
════════════════════════════════════ DEVICE ════════════════════════════════════
INFO           | 12:19:08.924 |   DEVICE                                              
INFO           | 12:19:08.925 | [AdbBinary]                                           
         C:/Users/Administrator/Desktop/OAS/OnmyojiAutoScript-easy-install/toolk
         it/Lib/site-packages/adbutils/binaries/adb.exe                         
INFO           | 12:19:08.927 | [AdbClient] AdbClient(127.0.0.1, 5037)                
INFO           | 12:19:08.928 | <<< DETECT DEVICE >>>                                 
INFO           | 12:19:08.930 | Here are the available devices, copy to               
         Alas.Emulator.Serial to use it or set Alas.Emulator.Serial="auto"      
INFO           | 12:19:08.932 | 127.0.0.1:16384                                       
INFO           | 12:19:08.934 | 127.0.0.1:7555                                        
INFO           | 12:19:08.937 | already connected to 127.0.0.1:16384                  
INFO           | 12:19:08.940 | [AdbDevice] AdbDevice(serial=127.0.0.1:16384 )        
INFO           | 12:19:08.941 | [PackageName] com.netease.onmyoji.wyzymnqsd_cps       
INFO           | 12:19:08.943 | <<< HANDLE >>>                                        
INFO           | 12:19:08.945 | Handle is handle num. oas use it as root handle num   
INFO           | 12:19:08.946 | Handle number 852274 is valid                         
INFO           | 12:19:08.947 | The root handle title is mumu模拟器12 and num is      
         852274                                                                 
INFO           | 12:19:08.949 | Emulator handle structure:                            
INFO           | 12:19:08.950 | mumu模拟器12                                          
INFO           | 12:19:08.951 | └── MuMuPlayer                                        
INFO           | 12:19:08.953 |     └── nemudisplay                                   
INFO           | 12:19:08.954 |   852274                                              
INFO           | 12:19:08.955 | └── 133210                                            
INFO           | 12:19:08.956 |     └── 788240                                        
INFO           | 12:19:08.958 | Emulator family: EmulatorFamily.FAMILY_MUMU           
INFO           | 12:19:08.959 | Your window screen scale rate: 1.0                    
INFO           | 12:19:08.961 | The emulator is MuMu模拟器12                          
INFO           | 12:19:08.962 | Screenshot handle num: 133210                         
INFO           | 12:19:08.963 | Emulator screenshot size: (1280, 720)                 
INFO           | 12:19:08.965 | Screenshot interval set to 0.3s                       
INFO           | 12:19:08.977 | [Screen_size] 1280x720                                
INFO           | 12:19:08.980 | module_path:                                          
         C:\Users\Administrator\Desktop\OAS\OnmyojiAutoScript-easy-install\tasks
         \GotoMain\script_task.py, module_name: script_task                     
INFO           | 12:19:09.165 | UI get current page                                   
INFO           | 12:19:09.198 | roi_front size changed to 66x75                       
INFO           | 12:19:09.253 | [Package_name] com.netease.onmyoji.wyzymnqsd_cps      
INFO           | 12:19:09.268 | [Device Orientation] 1 (HOME key on the right)        
WARNING  | 12:19:19.216 | Unknown ui page                                       
INFO           | 12:19:19.217 | [EMULATOR__SCREENSHOT_METHOD]                         
         ScreenshotMethod.WINDOW_BACKGROUND                                     
INFO           | 12:19:19.219 | [EMULATOR__CONTROL_METHOD] ControlMethod.ADB          
WARNING  | 12:19:19.220 | Starting from current page is not supported           
WARNING  | 12:19:19.222 | Supported page: ['page_main', 'page_summon',          
         'page_exploration', 'page_town', 'page_awake_zones', 'page_soul_zones',
         'page_realm_raid', 'page_goryou_realm', 'page_delegation',             
         'page_secret_zones', 'page_area_boss', 'page_heian_kitan',             
         'page_six_gates', 'page_bondling_fairyland', 'page_kekkai_toppa',      
         'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel',   
         'page_hyakkisen', 'page_shikigami_records', 'page_onmyodo',            
         'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team',  
         'page_collection']                                                     
WARNING  | 12:19:19.225 | Supported page: Any page with a "HOME" button on the  
         upper-right                                                            
CRITICAL    | 12:19:19.226 | Please switch to a supported page before starting oas 
INFO           | 12:19:19.227 | Game server may be under maintenance or network may be
         broken, check server status now                                        
CRITICAL    | 12:19:19.229 | Game page unknown                                     
WARNING  | 12:19:19.232 | Saving error: ./log/error/1729225159232               
INFO           | 12:19:19.283 | Notifier: OAS1                                        
INFO           | 12:19:19.285 | Script oas1 process exit                              
ERROR        | 12:19:19.286 | Error: 1                                              
每日琐事也报错，日志如上

**Comment by crazy-czy** [comment]
我均是在庭院开始的每日琐事，切换为其他方式每日锁事可以正常运行，然而window_background截屏方式下，每日琐事无法正常运行。

**Comment by runhey** [comment]
看一下图，这种路径有
WARNING | 12WARNING | 12:16:06.869 | Saving error: ./log/error/1729224966869

**Comment by crazy-czy** [comment]
这个路径下只有这张图片和日志════════════════════════════════════════════════════════════════════════════════
───────────────────────────────── HYAKKIYAKOU ──────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
2024-10-18 12:15:56.527 |            logger.py:0284 |     INFO | [Screen_size] 1280x720                                                                         
2024-10-18 12:15:56.529 |            script.py:0350 |     INFO | module_path:                                                                                   
C:\Users\Administrator\Desktop\OAS\OnmyojiAutoScript-easy-install\tasks\Hyakkiyakou\script_task.py, module_name: script_task                                    
2024-10-18 12:15:56.762 |           game_ui.py:0097 |     INFO | UI get current page                                                                            
2024-10-18 12:15:56.797 |             image.py:0077 |     INFO | roi_front size changed to 66x75                                                                
2024-10-18 12:15:56.876 |            logger.py:0284 |     INFO | [Package_name] com.netease.onmyoji.wyzymnqsd_cps                                               
2024-10-18 12:15:56.901 |            logger.py:0284 |     INFO | [Device Orientation] 1 (HOME key on the right)                                                 
2024-10-18 12:16:06.853 |           game_ui.py:0154 |  WARNING | Unknown ui page                                                                                
2024-10-18 12:16:06.855 |            logger.py:0284 |     INFO | [EMULATOR__SCREENSHOT_METHOD] ScreenshotMethod.WINDOW_BACKGROUND                               
2024-10-18 12:16:06.856 |            logger.py:0284 |     INFO | [EMULATOR__CONTROL_METHOD] ControlMethod.ADB                                                   
2024-10-18 12:16:06.858 |           game_ui.py:0157 |  WARNING | Starting from current page is not supported                                                    
2024-10-18 12:16:06.859 |           game_ui.py:0158 |  WARNING | Supported page: ['page_main', 'page_summon', 'page_exploration', 'page_town',                  
'page_awake_zones', 'page_soul_zones', 'page_realm_raid', 'page_goryou_realm', 'page_delegation', 'page_secret_zones', 'page_area_boss', 'page_heian_kitan',    
'page_six_gates', 'page_bondling_fairyland', 'page_kekkai_toppa', 'page_duel', 'page_demon_encounter', 'page_hunt', 'page_draft_duel', 'page_hyakkisen',        
'page_shikigami_records', 'page_onmyodo', 'page_friends', 'page_daily', 'page_mall', 'page_guild', 'page_team', 'page_collection']                              
2024-10-18 12:16:06.862 |           game_ui.py:0159 |  WARNING | Supported page: Any page with a "HOME" button on the upper-right                               
2024-10-18 12:16:06.863 |           game_ui.py:0160 | CRITICAL | Please switch to a supported page before starting oas                                          
2024-10-18 12:16:06.864 |            script.py:0377 |     INFO | Game server may be under maintenance or network may be broken, check server status now         
2024-10-18 12:16:06.866 |            script.py:0379 | CRITICAL | Game page unknown                                                                              
2024-10-18 12:16:06.869 |            script.py:0096 |  WARNING | Saving error: ./log/error/1729224966869                                                        

![2024-10-18_12-16-06-852067](https://github.com/user-attachments/assets/45a19dda-6b50-4459-845f-ab831579abcf)

**Comment by runhey** [comment]
截屏居然失效了，我看了一下这张黑图，不是纯黑色，rgb(28,33,39)。
我需要确认一下你的MuMu12版本信息和操作系统信息

**Comment by crazy-czy** [comment]
> 截屏居然失效了，我看了一下这张黑图，不是纯黑色，rgb(28,33,39)。 我需要确认一下你的MuMu12版本信息和操作系统信息
大佬晚上好，附上版本信息和操作系统信息（我使用另一台windows11设备尝试可以正常运行，不过运行的时候豆子不会自动拉到10）
![e19435c0268e481050d1391d3d04a80](https://github.com/user-attachments/assets/3da2e574-0a39-4107-804e-f3c4769b28df)

![b7d5f7166028d87bf4a779e3057c2b6](https://github.com/user-attachments/assets/92e9a689-a3f8-4ca2-9450-a952a13adf24)
![e09fe0efcbe9c2723bdd51c4730d8af](https://github.com/user-attachments/assets/d2a880f5-b889-479c-8af4-217e272b8700)
![a72504979557b7a0525dcc6cfe8ea28](https://github.com/user-attachments/assets/01f2a18d-dc49-42f6-8993-b5a223dc0185)
![e03b004f1de1d3202e1ac040bce6c29](https://github.com/user-attachments/assets/8aee93dd-8eed-4cd9-88ea-dd6fa9e8e701)

**Comment by runhey** [comment]
拉豆子，切换一下控制方式，或者拉日志出来

**Comment by runhey** [comment]
添加了切换百鬼里面的内部截屏方式，切到nemu_ipc就可以正常了
