### ISSUE TITLE
御魂副本双人在组队的时候，如果队长勾选了 “战斗结束后默认邀请队友”，会导致在接下来的挑战中停在结算页面

### ISSUE THREAD

**Issue by liuweiokay** [runhey/OnmyojiAutoScript#503]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

御魂副本双人在组队的时候，如果队长勾选了 “战斗结束后默认邀请队友”，会导致在接下来的挑战中停在结算页面

### 如何复现

1. 双人组队魂土
2. 队长账号勾选“战斗结束勾选默认邀请”
3. 运行四次左右，当战斗结束框被勾选之后，脚本无法运行

### 截图

![96cc9036621c2c2a2b912628038a1921](https://github.com/user-attachments/assets/0b1ecf6e-d880-4d52-89ac-2bc0a2ade749)
![d866285b687e5ac4c1632c0c16e88124](https://github.com/user-attachments/assets/6acea1ea-e54b-47e0-95c3-a1bd34746002)

**Comment by runhey** [comment]
![image](https://github.com/user-attachments/assets/4fa81b2e-ce94-46d7-bf5d-e1ed3e85f20e)

**Comment by runhey** [comment]
勾上试试
