### ISSUE TITLE
在模拟器登录oasx界面登录显示网络错误

### ISSUE THREAD

**Issue by xwq999sir** [runhey/OnmyojiAutoScript#506]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [ ] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

在模拟器登录oasx界面登录显示网络错误
错误代码: The connection errored: Connection refused This indicates an error which most likely cannot be solved by the library.
-1

### 如何复现

1. 前往 'mumu模拟器打开oasx'
2.输入'127.0.0.1:22288'
3.点击login
4. 出现问题

### 截图

![1](https://github.com/user-attachments/assets/5cd27a13-ec30-4d70-946a-51513deed084)

**Comment by xwq999sir** [comment]
![2](https://github.com/user-attachments/assets/fee1aa0c-8ec2-4284-a3b3-7e7ffa85000d)
![3](https://github.com/user-attachments/assets/98113b2b-888f-40d4-bf0f-376bdad409be)

**Comment by runhey** [comment]
用windows版本oasx
