### ISSUE TITLE
御魂组队 不能创建队伍 在组队界面停止

### ISSUE THREAD

**Issue by wd7719220** [runhey/OnmyojiAutoScript#508]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

不能在当队长模式下 组队邀请

### 如何复现

       scroll                                                                 
INFO           | 20:37:36.340 | Click ( 320,  465) @ Click                            
INFO           | 20:37:36.474 | Check lock: True                                      
INFO           | 20:37:36.717 | Create team                                           
INFO           | 20:37:36.967 | Click ( 954,  668) @ O_FORM_TEAM                      

### 预期行为

       scroll                                                                 
INFO           | 20:37:36.340 | Click ( 320,  465) @ Click                            
INFO           | 20:37:36.474 | Check lock: True                                      
INFO           | 20:37:36.717 | Create team                                           
INFO           | 20:37:36.967 | Click ( 954,  668) @ O_FORM_TEAM                      

### 相关 Logs

```Text
scroll                                                                 
INFO           | 20:37:36.340 | Click ( 320,  465) @ Click                            
INFO           | 20:37:36.474 | Check lock: True                                      
INFO           | 20:37:36.717 | Create team                                           
INFO           | 20:37:36.967 | Click ( 954,  668) @ O_FORM_TEAM
```

### 截图

       scroll                                                                 
INFO           | 20:37:36.340 | Click ( 320,  465) @ Click                            
INFO           | 20:37:36.474 | Check lock: True                                      
INFO           | 20:37:36.717 | Create team                                           
INFO           | 20:37:36.967 | Click ( 954,  668) @ O_FORM_TEAM                      

### 还有别的吗？

       scroll                                                                 
INFO           | 20:37:36.340 | Click ( 320,  465) @ Click                            
INFO           | 20:37:36.474 | Check lock: True                                      
INFO           | 20:37:36.717 | Create team                                           
INFO           | 20:37:36.967 | Click ( 954,  668) @ O_FORM_TEAM

**Comment by runhey** [comment]
你自己看看你写的这个是什么东西
![image](https://github.com/user-attachments/assets/a026be9f-7def-4f38-8c1a-c2cf5d3d5abc)

**Comment by wd7719220** [comment]
对不起  我没想到作者会回复  
![Snipaste_2024-10-28_20-39-43](https://github.com/user-attachments/assets/b984063f-2204-46d1-b41d-cbbce3e8e542)
在assets.py没有调用这个图 导致无法组队  
![Snipaste_2024-10-28_20-51-14](https://github.com/user-attachments/assets/bfb97cb9-92b9-431e-ad58-3f7e030320dd)
导致 最后停止在 
![Snipaste_2024-10-28_20-51-54](https://github.com/user-attachments/assets/d57249ab-2183-46c8-878f-7803bbfa45aa)

**Comment by runhey** [comment]
不是你这个意思。
https://github.com/runhey/OnmyojiAutoScript/issues/509 看这个
出错会给你报错这种日志，看到这一行没，类似的
```
Saving error: ./log/error/1730081760376
```
在你的安装目录下找，这个报错文件，传上来

**Comment by wd7719220** [comment]
[log.txt](https://github.com/user-attachments/files/17543327/log.txt)
老师  我的错误是卡在组队界面 无法创建队伍

**Comment by wd7719220** [comment]
![Snipaste_2024-10-28_21-51-38](https://github.com/user-attachments/assets/ee3d6385-2cbc-4ffe-a291-d9a0a6efcf4b)
la老师 这是 最新报错 截图  和我上传的 错误 是一致的 还有  已经停用
![Snipaste_2024-10-28_21-52-47](https://github.com/user-attachments/assets/7ba009ce-75b8-4160-b3c1-c6046c483caa)
我尝试 修改 DEV 但是  更新器还是 master 谢谢老师答复

**Comment by wd7719220** [comment]
![Snipaste_2024-10-28_21-57-04](https://github.com/user-attachments/assets/03b367de-6373-4edd-8973-63175c503d99)
oaSX  问题截图

**Comment by wd7719220** [comment]
![Snipaste_2024-10-28_21-59-28](https://github.com/user-attachments/assets/83082728-927d-4126-bdb4-ec4ea1fad16f)

**Comment by runhey** [comment]
你新号没有同心队？

**Comment by wd7719220** [comment]
没有建立 同心队伍

**Comment by runhey** [comment]
oas都使用门槛是六十级
