### ISSUE TITLE
dev分支在打个人突破的时候，会卡死，重启之后，打几把又会卡死

### ISSUE THREAD

**Issue by liupeng-2000** [runhey/OnmyojiAutoScript#510]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

dev分支在打个人突破的时候，会卡死，重启之后，打几把又会卡死

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/user-attachments/assets/57bd3343-c793-49e5-8c79-1497e74045a8)
![image](https://github.com/user-attachments/assets/c487a944-ae30-4fd0-89e3-0e815fb569f8)

**Comment by runhey** [comment]
你先看看别人是怎么提问的 https://github.com/runhey/OnmyojiAutoScript/issues/481
