### ISSUE TITLE
契灵绿标不生效

### ISSUE THREAD

**Issue by jojolionss** [runhey/OnmyojiAutoScript#512]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

契灵绿标不生效，单独开绿标功能（不开随机和开随机都试过），然后换位置都试过，确定没有绿标成功。测试过个人突破绿标是生效的。其中一张图片信息绿标生效的是个人突破我截图的。另外两张均是契灵。

### 如何复现

1. 前往 '契灵'
2. 战斗开始
3. 出现问题

### 预期行为

绿标

### 相关 Logs

```Text
请看图片
```

### 截图

![QQ图片20241031223030](https://github.com/user-attachments/assets/13d31e7e-2532-417d-b16b-63528d84e082)
![QQ图片20241031223044](https://github.com/user-attachments/assets/e13bc6c8-0b6f-4aef-812e-a6ba62d94273)
![QQ图片20241031223050](https://github.com/user-attachments/assets/dcc21af7-b5b4-4699-bfb5-2ab81fd7b9a0)

### 还有别的吗？

无

**Comment by runhey** [comment]
#90 

无反馈点击的意思就是，点一次不管有没有标上
