### ISSUE TITLE
Adb报错 AdbError: unknown host service

### ISSUE THREAD

**Issue by Flandre111** [runhey/OnmyojiAutoScript#522]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

各位大佬你们好，
我在今天在根据教程安装好软件，并配置好脚本，进行测试时报错

ERROR        | 17:31:27.527 | AdbError: unknown host service   

根据一篇来自csdn的帖子，我对adb被占用的端口进行了排查 https://blog.csdn.net/liguilicsdn/article/details/50902194
发现占用端口的就是adb本身。如下图：
![X5MO_J_B )84SFYFINBP5$E](https://github.com/user-attachments/assets/86e3a4b4-abb9-4983-8f06-a9aae85fc4f0)

并尝试了群友提供的方法，包括重启客户端，使用管理员模式启动，关闭防火墙，重启adb等方法后无效，特来求助，
在下方已附上问题截图，以及报错日志。 希望大佬伸出援手。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/user-attachments/assets/38ec8ab0-eb59-4f21-8355-9b9aa4ab3827)
![image](https://github.com/user-attachments/assets/85cb8a69-7c91-4c93-9915-0f5e0352c172)
![image](https://github.com/user-attachments/assets/77fd525e-7f3c-47bb-9eea-bdd5807e3bb6)
![image](https://github.com/user-attachments/assets/4210b88a-6658-447c-b7f6-9270702e8c57)

**Comment by Flandre111** [comment]
[2024-11-07_oas2.txt](https://github.com/user-attachments/files/17666825/2024-11-07_oas2.txt)

**Comment by runhey** [comment]
https://github.com/runhey/OnmyojiAutoScript/issues/435

![image](https://github.com/user-attachments/assets/207781d3-9784-4575-8d27-8449511d705d)
你看是谁家的adb
