### ISSUE TITLE
✨选择御魂副本的层数时，如果该层有过输入历史，其它选项也跟着变更为该层对应的值

### ISSUE THREAD

**Issue by loseLight** [runhey/OnmyojiAutoScript#534]
### 当前不足

选择御魂副本的层数时，如果该层有过输入历史，其它的选项也跟着变更为该层对应的值。

**Comment by runhey** [comment]
不知道唧唧歪歪什么

**Comment by loseLight** [comment]
就是一个历史记录的功能。

举个例子：
假设【御魂十层】以前设置过，队伍御魂预设填写的是[4,2]；【御魂十一层】以前也设置过，队伍御魂预设填写的是[4,1]。
当切换御魂层数 【御魂十一层】--->【御魂十层】，则御魂预设[4,1]也跟着自动变为[4,2]。反之亦然。

就好比一些财报表格，点击张三，应该显示张三的工资和年龄，点击李四就应该显示李四的工资和年龄，工资和年龄这些属性是绑定在人名上的。（ 同理，【队伍御魂预设】等设置项是绑定在【八岐大蛇层数】上的 ，它们是一个整体，【八岐大蛇层数】变更，【队伍御魂预设】等属性应该跟着变更过来 ）。而目前的状态就类似于    点击了李四，工资和年龄那一栏显示的依然是张三的工资和年龄，需要用户再自己改为李四的工资和年龄。而其实当用户选了李四，那么工资和年龄其实就跟着确定了，是不需要用户单独选择设置的。

个人感觉：
【八岐大蛇层数】就是一个class，而【队伍御魂预设】等这些设置项都是依附于【八岐大蛇层数】这个class而存在的一些属性，它们是一个整体，每个class实例都了有其单独的属性。所以当用户切换【八岐大蛇层数】，其属性应该跟着变更过来。而目前变更【八岐大蛇层数】，其属性没跟着改过来，需要用户自己改，给人的感觉上不是一个整体，是拆分开来的一些数据 的感觉。

一个建议，说的有点啰嗦了。大佬们辛苦。

有不足之处，望指出共同进步。

**Comment by ljxun** [comment]
不是有根据御魂选的层数换不同御魂么？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月16日(周六) 晚上7:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [runhey/OnmyojiAutoScript] ✨选择御魂副本的层数时，如果该层有过输入历史，其它选项也跟着变更为该层对应的值 (Issue #534)




 
就是一个历史记录的功能。
 
举个例子：
 假设【御魂十层】以前设置过，队伍御魂预设填写的是[4,2]；【御魂十一层】以前也设置过，队伍御魂预设填写的是[4,1]。
 当切换御魂层数 【御魂十一层】---&gt;【御魂十层】，则御魂预设[4,1]也跟着自动变为[4,2]。反之亦然。
 
就好比一些财报表格，点击张三，应该显示张三的工资和年龄，点击李四就应该显示李四的工资和年龄，工资和年龄这些属性是绑定在人名上的。（ 同理，【队伍御魂预设】等设置项是绑定在【八岐大蛇层数】上的 ，它们是一个整体，【八岐大蛇层数】变更，【队伍御魂预设】等属性应该跟着变更过来 ）。而目前的状态就类似于    点击了李四，工资和年龄那一栏显示的依然是张三的工资和年龄，需要用户再自己改为李四的工资和年龄。而其实当用户选了李四，那么工资和年龄其实就跟着确定了，是不需要用户单独选择设置的。
 
个人感觉：
 【八岐大蛇层数】就是一个class，而【队伍御魂预设】等这些设置项都是依附于【八岐大蛇层数】这个class而存在的一些属性，它们是一个整体，每个class实例都了有其单独的属性。所以当用户切换【八岐大蛇层数】，其属性应该跟着变更过来。而目前变更【八岐大蛇层数】，其属性没跟着改过来，需要用户自己改，给人的感觉上不是一个整体，是拆分开来的一些数据 的感觉。
 
一个建议，说的有点啰嗦了。大佬们辛苦。
 
有不足之处，望指出共同进步。

**Comment by loseLight** [comment]
> 不是有根据御魂选的层数换不同御魂么？
> […](#)
> ---原始邮件--- 发件人： ***@***.***> 发送时间: 2024年11月16日(周六) 晚上7:21 收件人： ***@***.***>; 抄送： ***@***.***>; 主题： Re： [runhey/OnmyojiAutoScript] ✨ 选择御魂副本的层数时，如果该层有过输入历史，其它选项也跟着变更为该层对应的值 （Issue #534） 就是一个历史记录的功能。 举个例子： 假设【御魂十层】以前设置过，队伍御魂预设填写的是[4,2]；【御魂十一层】以前也设置过，队伍御魂预设填写的是[4,1]。 当切换御魂层数 【御魂十一层】---&gt;【御魂十层】，则御魂预设[4,1]也跟着自动变为[4,2]。反之亦然。 就好比一些财报表格，点击张三，应该显示张三的工资和年龄，点击李四就应该显示李四的工资和年龄，工资和年龄这些属性是绑定在人名上的。（ 同理，【队伍御魂预设】等设置项是绑定在【八岐大蛇层数】上的 ，它们是一个整体，【八岐大蛇层数】变更，【队伍御魂预设】等属性应该跟着变更过来 ）。而目前的状态就类似于 点击了李四，工资和年龄那一栏显示的依然是张三的工资和年龄，需要用户再自己改为李四的工资和年龄。而其实当用户选了李四，那么工资和年龄其实就跟着确定了，是不需要用户单独选择设置的。 个人感觉： 【八岐大蛇层数】就是一个class，而【队伍御魂预设】等这些设置项都是依附于【八岐大蛇层数】这个class而存在的一些属性，它们是一个整体，每个class实例都了有其单独的属性。所以当用户切换【八岐大蛇层数】，其属性应该跟着变更过来。而目前变更【八岐大蛇层数】，其属性没跟着改过来，需要用户自己改，给人的感觉上不是一个整体，是拆分开来的一些数据 的感觉。 一个建议，说的有点啰嗦了。大佬们辛苦。 有不足之处，望指出共同进步。 — 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。 您收到此消息是因为您订阅了此线程。消息 ID：***@***.***>

在设置界面的末尾是已经有了御魂11、12层的单独的御魂配置的，我也有看。这只是一个改善性的建议罢了。（个人感觉那样子更棒！！！界面简洁了，而且自动变更，感觉逼格高了许多，而且游戏日后更新出了13、14层的话，维护也不用在后面单独加上13、14层的御魂配置。当然了，有无必要，大佬们根据时间精力和其它因素考虑，无伤大雅。）
