### ISSUE TITLE
发展规划（挖坑~不是）

### ISSUE THREAD

**Issue by runhey** [runhey/OnmyojiAutoScript#54]
## 日常任务
1. [✔ runhey]琐事一遍：每日一抽、寮祈愿、好友友情点、商店签到
2. [✔ runhey]悬赏封印
3. [✔ runhey]宠物：其乐融融、饕餮大餐、放置食材
4. [✔ runhey]金币妖怪
5. [❓ runhey]经验妖怪
6. [✔ runhey]年兽
7. ❓ 师徒守护
8. [✔ runhey]花合战
9. [✔ runhey]式神委派
10. [✔ runhey]地狱鬼王
11. [✔ runhey]封魔之时
12. [✔ runhey]御魂整理：（每天清一清不溢出）

## 每周相关
1. [✔ runhey]真蛇
2. [✔ runhey]秘闻竞速
3. [✔ runhey]神秘商店: （黑碎/蓝票/金币/）
4. [✔ runhey]搜刮商店：千御宝箱、勋章购买、荣誉购买、魅力值、寮商店、秘卷书童、契灵材料、神龛、寄售屋
5. [✔ runhey]琐事每周：图鉴分享、地鬼分享、清厕所票、秘闻分享
6. [✔ runhey]斗技
7. 协同斗技
8. 百鬼奕

## 阴阳寮
1. [✔ runhey]结界挂卡
2. [✔ runhey]结界蹭卡
3. [✔ runhey]结界突破
4. [✔ TripleEarth & endlesswxk]寮突破
5. [✔ runhey]狩猎战（麒麟/阴界之门）
9. 道馆
10. 妖怪退治
11. 寮宴会
12. 狭间暗域
13. [✔ runhey]集体任务（寮30）

## 御魂副本
1. [✔ runhey]八岐大蛇
2. [✔ runhey]业原火
3. [✔ TripleEarth]日轮之城
4. [✔ xbj110825] 永生之海 (单人)
5. 六道之门

## 肝帝专属
1. [✔ endlesswxk]探索： 现在只有单人的
2. [✔ runhey]契灵
3. [✔ runhey]御灵
4. [✔ runhey] 百鬼夜行
5. [✔ TripleEarth ]觉醒副本
6. [✔ runhey]石距

## 限时活动
1. [✔ runhey]每期式神
2. 金币大作战
3. 绘卷
4. 欢迎补充...🔨

## 协作系统
阴阳师相当多玩法是多人同时组队，无论市面上的脚本功能如何如何，但是都必须要求两个（多个）账号需要手动开启脚本，这导致传统的脚本并不是完全的长期挂机。我们期望实现这样的一个协作系统：
1. 自适应：每一个 oas 实例都可以自行管理多人任务的调度，不必须依赖其他的外部条件 
2. 好友组：建立一组可协作的好友列表，一对多而不是只可以一对一
3. 多角色：每个 oas 实例的角色不是固定的，在有的任务中可以是队员，也可以是队长
4. 组队频道：每个 oas 使用者不必持有多个账号，符合组队要求可接入该系统随机组队
但是这一设想目前还没有具体的思路，甚至也没有参考的样板，在正式确定方案之前我们欢迎一切建议

## 框架相关
1. 游戏服务器自适应：游戏服务停止更新时间并不是固定的周三九点，需检测游戏公司是否暂时关闭了服务
2. 重写 device

## 游戏装饰自定义
https://github.com/runhey/OnmyojiAutoScript/issues/180

出自某博主
![{DEBA149F-4F73-1A93-1D40-51581C1C4904}](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/716a6639-15b7-4b86-a87e-6c47b5deb6aa)

**Comment by TwilightKHQ** [comment]
肝帝专属 如果可以的话再加一个六道呗

**Comment by runhey** [comment]
六道在御魂里面

**Comment by TwilightKHQ** [comment]
建议可以把这些内容添加到readme，完成的也可以添加@ @runhey 后续有问题也方便找人

**Comment by runhey** [comment]
readme 不能评论，导个链接吧

**Comment by TwilightKHQ** [comment]
奥对 还有一个 周任务 挂机斗技 打满积分（且到达指定段位）停止

**Comment by runhey** [comment]
加了ok

**Comment by TwilightKHQ** [comment]
分享还有个秘闻分享

**Comment by yeyx-11** [comment]
如果可以，适配峡间暗域的时候，可以适配成每个怪都打一遍，先首领，再精英啥的。最好还是可以到了一定的时间就退出战斗打下一个。如果只是打一个，峡间的奖励会大大减少的

**Comment by huangyinhui520** [comment]
如果可以，希望开发到永生之海，像大蛇一样的功能  可以组队  永生之海加成是独立开启的    然后通用的组队功能其实也比较实用

**Comment by aichitutututututu** [comment]
每次重启之后设定的刷图次数不能接着算，都要从0开始能不能优化下？

**Comment by zhaodezhi22** [comment]
六道之门具体阵容是哪个博主的攻略呢？
![Uploading Screenshot_20231014_083341.jpg…]()

**Comment by nguyenthanhdan2000** [comment]
Can you develop more for the global version running on steam and nox, please

**Comment by Tardisvivi** [comment]
探索副本会在结算界面停止，有这个问题吗，日志显示等待res_bettle_start timeout

**Comment by abingaaa** [comment]
探索K28会在日志里显示Wait until appear RES_BATTLE_START timeout         应当如何处理呢

**Comment by lengling1** [comment]
探索要是可以只打红达摩就好了

**Comment by sunlight666** [comment]
感觉可以加个百鬼夜行，这个真的砸不动，票就全积攒在那里
