### ISSUE TITLE
✨自定义庭院图片提供 

### ISSUE THREAD

**Issue by jojolionss** [runhey/OnmyojiAutoScript#540]
### 当前不足

望月幽庭，我唯一的庭院皮肤挺好看的，希望大佬加上去~
![MuMu12-20241118-102913](https://github.com/user-attachments/assets/97b007f6-c1bf-4bd8-b6d5-60fb8e2679ab)
![MuMu12-20241118-102951](https://github.com/user-attachments/assets/4ae9d83b-066a-4cb6-8bbe-bcf6ca5f8d86)

**Comment by runhey** [comment]
加了
