### ISSUE TITLE
截图工具（老版OAS）无法检测到正在运行的OAS1

### ISSUE THREAD

**Issue by Gan1Ser** [runhey/OnmyojiAutoScript#541]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

想截图工具做一些图片工作，但是始终无法将模拟器界面投屏到截图规则中。
![1](https://github.com/user-attachments/assets/4657b3a7-ed99-45f5-a163-3ef0394572d2)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

无法完成该步
![2](https://github.com/user-attachments/assets/9d6c957e-5fe3-4d63-aa28-b55f2707341b)

### 相关 Logs

```Text
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
════════════════════════════════════════════════════════════════════════════════
──────────────────────────────────── START ─────────────────────────────────────
════════════════════════════════════════════════════════════════════════════════
INFO     2024-11-18 20:05:39.223 │ Update thread start                                                                  
INFO     2024-11-18 20:07:10.254 │ Script oas1 is not running                                                           
INFO     2024-11-18 20:07:10.257 │ Script oas1 is not running                                                           
ERROR    2024-11-18 20:07:12.148 │ image is null                                                                        
INFO     2024-11-18 20:07:13.135 │ Script oas1 is not running                                                           
INFO     2024-11-18 20:07:14.135 │ Script oas1 is not running                                                           
INFO     2024-11-18 20:07:15.189 │ Script oas1 is not running                                                           
INFO     2024-11-18 20:07:16.134 │ Script oas1 is not running
```

### 截图

![1](https://github.com/user-attachments/assets/4657b3a7-ed99-45f5-a163-3ef0394572d2)

### 还有别的吗？

[setting.json](https://github.com/user-attachments/files/17800194/setting.json)

**Comment by ohspecial** [comment]
配置设对了没

**Comment by Gan1Ser** [comment]
我想我的配置是正确的，因为我的OAS是正常运行的（它能正常操控模拟器），但也不确定是不是还需要配置一些其他的文件，可否告知要使用该功能具体需要配置哪些东西吗？

**Comment by ohspecial** [comment]
按开发文档操作就行啦，如果你oas可以运行，那你看看oas那边的oas1.json这个复制到旧版那边看看是不是这个文件配置错了

**Comment by Gan1Ser** [comment]
请问您说的“复制到旧版那边”是指是什么？我是这样操作的，我下载了旧版的OAS并将现有的oas1.json复制进config文件夹中，使用OASX可以识别oas1.json中的配置并控制模拟器，但是我启动gui.py仍提示oas1未启动。麻了😭
