### ISSUE TITLE
您好！  有没有考虑对任务添加一个立即执行的按钮呢？

### ISSUE THREAD

**Issue by ch-hang** [runhey/OnmyojiAutoScript#564]
### 当前不足

感觉现在的任务都是定时的。比如说我在爬塔，然后接收到了一个封印任务，我想停掉爬塔然后自己去做封印任务，做完任务后再继续通过爬塔任务的立即执行按钮   再次执行任务

**Comment by runhey** [comment]
没有抢占式设计。悬赏任务接收后会自己执行，我记得有选项
