### ISSUE TITLE
网络错误500

### ISSUE THREAD

**Issue by sanfeng666** [runhey/OnmyojiAutoScript#566]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

在完成前面的步骤之后进如oas在脚本配置的途中会出现网络错误500的情况，在之前使用雷神加速器很少有这种情况但有时也会有，自从换了mumu之后逐渐频发并不知道什么原因？求了解的人讲解一下，麻烦你了谢谢
![a6c90a956e06a268dc4a43469cf5bc5](https://github.com/user-attachments/assets/d5a52c71-5062-4761-b18f-345fc151bfb2)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![a6c90a956e06a268dc4a43469cf5bc5](https://github.com/user-attachments/assets/9edf8ef1-68f7-440d-aa6e-69df3394a409)

**Comment by sanfeng666** [comment]
现在好像解决了一点，这个问题好像是如果我点了突破这个任务他好像就直接出500的错误以至于整一页都不能用要重新增加一页，这是怎么回事有没有大佬知道的麻烦了，谢谢

**Comment by it-guo** [comment]
有类似案例嗷，自己去根目录（OnmyojiAutoScript-easy-install\config）把该错误任务删除，原因：你设置里的数量设置超值了

**Comment by sanfeng666** [comment]
> 有类似案例嗷，自己去根目录（OnmyojiAutoScript-easy-install\config）把该错误任务删除，原因：你设置里的数量设置超值了
好的，谢谢已经解决了，但正常运行之后又有了一个新问题在打困28打着打着会自动退回庭院不懂但是任务显示还在正常运行这个是什么回事？麻烦你了

**Comment by it-guo** [comment]
> > 有类似案例嗷，自己去根目录（OnmyojiAutoScript-easy-install\config）把该错误任务删除，原因：你设置里的数量设置超值了
> > 好的，谢谢已经解决了，但正常运行之后又有了一个新问题在打困28打着打着会自动退回庭院不懂但是任务显示还在正常运行这个是什么回事？麻烦你了

是因为有悬赏，有大佬已经改了，等等更新吧

**Comment by sanfeng666** [comment]
> > > 有类似案例嗷，自己去根目录（OnmyojiAutoScript-easy-install\config）把该错误任务删除，原因：你设置里的数量设置超值了
> > > 好的，谢谢已经解决了，但正常运行之后又有了一个新问题在打困28打着打着会自动退回庭院不懂但是任务显示还在正常运行这个是什么回事？麻烦你了
> 
> 是因为有悬赏，有大佬已经改了，等等更新吧

非常感谢，我这还有一个疑问就是困28里有像绘卷模式一样到多少突袭卷转突袭，那个挖土也可以嘛？是要在个人突袭里面设置吗？麻烦你了谢谢
