### ISSUE TITLE
突然出现网络未连接问题

### ISSUE THREAD

**Issue by wml8806** [runhey/OnmyojiAutoScript#579]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

昨天晚上运行的时候还是好好的，晚上未关机。
但是今天再次运行，服务端显示创建成功，oasx提示网络未连接，无法连接到oax服务。
所有设置均未改动，重新下载软件更换路径仍然解决不了

### 如何复现

问题突然出现，不知道是哪部出了问题

### 预期行为

请大佬帮忙解决无法连接的问题，或者告知原因

### 截图

![微信图片_20241210120500](https://github.com/user-attachments/assets/c4d0ca12-aded-4a46-bcb7-b5c83f9866ef)

### 还有别的吗？

服务启动日志是空白的

**Comment by runhey** [comment]
没有http
填127.0.0.1:22288
