### ISSUE TITLE
重启 进入游戏相关

### ISSUE THREAD

**Issue by Gregorio77777** [runhey/OnmyojiAutoScript#585]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

重新启动时，在“进入游戏”界面，有时会出现服务器列表还没加载（图一），OAS就点击了“进入游戏”，从而进入（图二）界面，导致不能识别而超时。正常点击已加载服务器列表的“进入游戏”界面为（图三），或许可以延迟点击“进入游戏”，确保服务器列表加载完成。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![MuMu12-20241215-205140](https://github.com/user-attachments/assets/435274c4-aef7-4dba-ba87-8249a7a2d2f7)
![MuMu12-20241215-205237](https://github.com/user-attachments/assets/b115dcc5-46c5-4a43-b8f7-feff2aece993)
![MuMu12-20241215-210100](https://github.com/user-attachments/assets/3da5e101-9fc6-433d-8c55-4aaf5a3cd181)

**Comment by runhey** [comment]
如何退出图二中的界面？

**Comment by Gregorio77777** [comment]
> 如何退出图二中的界面？

点击红框内的区域即可。辛苦大佬！
![MuMu12-20241215-210738](https://github.com/user-attachments/assets/4ddb1ce3-cb4c-454b-a5f3-a1f33c6f8b51)
