### ISSUE TITLE
斗技无法正常打开

### ISSUE THREAD

**Issue by qsrgcz** [runhey/OnmyojiAutoScript#586]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

每次运行斗技，只会到斗技界面而无法进行正常的开始斗技，同时回出现无法识别到模块的问题
![image](https://github.com/user-attachments/assets/37172484-9fef-49e8-9223-c441a6b09d08)
![image](https://github.com/user-attachments/assets/b6ddd158-24e3-4c8c-87a8-e56e7be1deae)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![image](https://github.com/user-attachments/assets/44423ed2-ccd1-4311-b30b-f5884ca36284)
![image](https://github.com/user-attachments/assets/5dabf42f-a06c-4c9e-9858-d78d1ddcce7d)

### 还有别的吗？

[2024-12-15_oas1.txt](https://github.com/user-attachments/files/18140547/2024-12-15_oas1.txt)

**Comment by qsrgcz** [comment]
通过调解截屏方案，控制方案还是没法解决
![image](https://github.com/user-attachments/assets/25911e37-868b-483c-90c4-c638c064d757)

**Comment by Gregorio77777** [comment]
先打上1200分 #584

**Comment by qsrgcz** [comment]
> 先打上1200分 #584

好

**Comment by qsrgcz** [comment]
我靠，打到1200就行了是什么个原理

**Comment by qsrgcz** [comment]
> 先打上1200分 #584

但是他只能自动一把
![image](https://github.com/user-attachments/assets/6f7c515e-ed12-4f1e-af61-8fb7bbd9bea4)
[2024-12-16_oas1.txt](https://github.com/user-attachments/files/18148654/2024-12-16_oas1.txt)

**Comment by runhey** [comment]
好像没有针对呱太进行处理，你多试试几次看看
