### ISSUE TITLE
部分image的匹配出现问题

### ISSUE THREAD

**Issue by zl827154659** [runhey/OnmyojiAutoScript#588]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

先说结论：能否用增设全局变量来替代所有的threshold值。
周末的使用中，git自动拉了最新的代码，然后很多按键的image都match不上了，具体表现为appear()的返回值是False导致一直在wait或者循环
目前手动调低了很多按键image的threshold能够正常运行，我check了使用的分辨率以及环境，确保是1280x720，且游戏内设置和文档一致。但还是不清楚是代码有更新还是模拟器（MUMU12）环境出现问题或者游戏资源有更新。具体原因还没来得及去细排查。

base_task下的appear函数在很多按键图标的image都match不上
![image](https://github.com/user-attachments/assets/2a0f0c26-c4b7-4767-9ddc-71d4b9ef97e6)
手动调低了一部分图标的threshold
![image](https://github.com/user-attachments/assets/c455d600-ba84-4ca7-8f11-907b4ad8e5ab)

模拟器环境，显卡渲染模式和几个性能设置都试过切换，还是没法match
![image](https://github.com/user-attachments/assets/9878413d-1fcc-47be-81a6-15ce98748db7)
![image](https://github.com/user-attachments/assets/697a4380-f2bb-4d7a-ac51-8173f180c2d9)
![image](https://github.com/user-attachments/assets/6081dfb6-3d79-4129-b47f-eb335017bab5)

![image](https://github.com/user-attachments/assets/1a5c6cf7-f38b-49be-a30b-8794d248334d)

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by runhey** [comment]
换一个雷电模拟器看看

**Comment by runhey** [comment]
第一次用吗

**Comment by zl827154659** [comment]
> 第一次用吗

不是第一次用，之前正常的，上周末用OSA拉个最新的代码之后就出现这种了。
我先重装一下mumu试试，如果代码没有变动的话，大概率是比对的工具库有更新或者模拟器有啥问题了

**Comment by zl827154659** [comment]
已确定是模拟器问题，重装后解决，closed
