### ISSUE TITLE
✨能否适配一下桌面端

### ISSUE THREAD

**Issue by redkamih** [runhey/OnmyojiAutoScript#59]
### 当前不足

我电脑比较老，模拟器负载太高了，桌面端比较友好

### 解决方案

如题

### 其他内容

无

**Comment by OnlyFreePeople** [comment]
+1 桌面端用户

**Comment by linuxAlpha** [comment]
+1

**Comment by TripleEarth** [comment]
> ### 当前不足
> 我电脑比较老，模拟器负载太高了，桌面端比较友好
> 
> ### 解决方案
> 如题
> 
> ### 其他内容
> 无

官方已经不支持桌面端了，而且桌面端每天的副本次数还有限，就没必要做了。电脑比较老的话建议换一个电脑。如果觉得实在需要使用桌面端，可以考虑自己把源码改一改支持一下桌面端

**Comment by redkamih** [comment]
> > ### 当前不足
> > 我电脑比较老，模拟器负载太高了，桌面端比较友好
> > ### 解决方案
> > 如题
> > ### 其他内容
> > 无
> 
> 官方已经不支持桌面端了，而且桌面端每天的副本次数还有限，就没必要做了。电脑比较老的话建议换一个电脑。如果觉得实在需要使用桌面端，可以考虑自己把源码改一改支持一下桌面端。因为就目前的情况来说，很多功能没有完善，支持桌面端的优先级是最低的

emmm修改哪些代码可以支持桌面端，麻烦指个方向我去学习学习
