### ISSUE TITLE
✨能不能添加服务器维护识别

### ISSUE THREAD

**Issue by SwrodKing** [runhey/OnmyojiAutoScript#594]
### 当前不足

服务器处于维护状态下，程序会被迫中止，任务没办法继续进行

### 解决方案

在重启过程中添加服务器维护识别，然后暂停所有任务运行，可以自定义重新运行时间，默认时间设定早上9点，这样就不会维护好了任务却不能正常运行

**Comment by runhey** [comment]
周三看看
