### ISSUE TITLE
window深色主题下,oasx主题都是亮色无法切换

### ISSUE THREAD

**Issue by ljxun** [runhey/OnmyojiAutoScript#599]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [X] 我使用 OAS 的 dev 分支

### 描述你的问题

window深色主题下,oasx主题都是亮色无法切换

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

window深色主题下,oasx主题都是亮色无法切换

### 相关 Logs

```Text
window深色主题下,oasx主题都是亮色无法切换
```

**Comment by runhey** [comment]
https://github.com/jonataslaw/getx/pull/2550
这个玩意getx居然没有修
