### ISSUE TITLE
可以更新一个设计文档嘛？或者一个quick start

### ISSUE THREAD

**Issue by blueshell2017** [runhey/OnmyojiAutoScript#6]
简单看了下像是尝试用ocr定位关键点，觉得挺有意思的，可以贡献一些代码，就是有点没有弄懂你的思路，有精力的话，可以考虑加一下hhh

**Comment by runhey** [comment]
❤❤❤❤感谢大佬。
项目挺大的，ocr倒是定位识别的一个部分。
后面更新一下设计的思路和上手

**Comment by runhey** [comment]
更新啦
