### ISSUE TITLE
无法跳转到指定界面

### ISSUE THREAD

**Issue by mengxinxiaohuozi** [runhey/OnmyojiAutoScript#607]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的
- [ ] 我使用 OAS 的 dev 分支

### 描述你的问题

在庭院页面无法执行结界挂卡，结界蹭卡，从庭院无法点击阴阳寮入口，需要手动点击阴阳寮后在阴阳寮界面才会自动点击结界后续任务才能正常执行。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

执行结界挂卡，结界蹭卡时应该按照设置的导航执行点击阴阳寮，再点击结界进行挂卡蹭卡操作

### 截图

![cea6679a-3c27-4b8b-8ce1-08bfa03961d7](https://github.com/user-attachments/assets/5103879b-0126-484d-b9c9-e5ca1da270b2)

![df3b6260-9d5f-457f-b072-3ad84bc8b299](https://github.com/user-attachments/assets/296fa0f5-a58c-4717-b552-bea78b51a3a3)

**Comment by ljxun** [comment]
换成默认主题

**Comment by mengxinxiaohuozi** [comment]
> 换成默认主题

是的，是下边试用了主题，换了默认就解决了
