### ISSUE TITLE
不错不错来支持一下，这是打算做阴阳师脚本吗

### ISSUE THREAD

**Issue by NakanoSanku** [runhey/OnmyojiAutoScript#7]
前段时间练手的时候刚好写过一个，继承uiautomator的devices类来实现截图和点击那些操作，找图找色那些我也基本封装了可以用用，不过详细文档还没写，目前好像就这个实现后台截图比较方便且全模拟器通用了，我也试过minicap+minitouch的方案,不过容易崩溃，可以看看fastcap和pyminitouch这两个库，希望能给到有用的建议
```
pip install gameauto
````

**Comment by runhey** [comment]
噢谢谢，我从alas copy 来的挺多的abd系的控制截图的方式，后面了解下
