### ISSUE TITLE
🐛个人突破和寮突破战斗失败后重复打同一目标

### ISSUE THREAD

**Issue by Xenes-cyber** [runhey/OnmyojiAutoScript#71]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的

### 描述你的问题

个人突破和寮突破战斗失败后重复打同一目标

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![1](https://github.com/runhey/OnmyojiAutoScript/assets/57897931/b232a2c0-a063-424b-a3f0-9fc3ec10e2a3)
![2](https://github.com/runhey/OnmyojiAutoScript/assets/57897931/1f29a758-84af-42e0-962e-85719c796c0a)

**Comment by Xenes-cyber** [comment]
[2023-08-05_test.txt](https://github.com/runhey/OnmyojiAutoScript/files/12269475/2023-08-05_test.txt)

**Comment by runhey** [comment]
### 个人突破
我不知道你选择的打法是什么的，一般人是选择打九退四保57，在这种模式下打57级的非常容易。注意这种打法必须要求练度足够，不容忍有任何的失败，否则导致降级巴拉巴拉，总之不允许失败，这无关什么脚本，是机制本身。

如果练度不够，你可以选择挑战失败时刷新，同时将挑战顺序切换为 0 > 1 > 2 > 3 > 4 > 5 。如果你还不放心，还可以勾选一个三胜利刷新。

这里当时留了一个小问题，无法处理挑战失败时 跳过这一个失败的继续打：在查找可挑战的时候简单粗暴的在一个大的范围内查找可以找到的勋章如
![res_medal_3](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/aec5442f-922e-4804-8c5f-4d35118a8ec0)
![res_medal_5_frog](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/fb0dd130-e3c5-4779-9610-55fd33ab303a)
，未挑战和失败时候是一样的。如果你有优化的建议欢迎提供

**Comment by runhey** [comment]
寮突也是同样的逻辑，不过寮突需要大改一下，欢迎提建议

**Comment by JJYYYE** [comment]
寮突是否可以      
  # 点击挑战
        self.wait_until_appear(RealmRaidAssets.I_FIRE)
        while 1:
            self.screenshot()
            if self.appear_then_click(RealmRaidAssets.I_FIRE, interval=2):
                continue
            if not self.appear(RealmRaidAssets.I_FIRE, threshold=0.8):
                break
        logger.info(f'Click {RealmRaidAssets.I_FIRE.name}')
在这里点击I_FIRE前，增加判断一个判断，判断该页面是否有失败的箭头，有就可以跳出

**Comment by yEs1do** [comment]
mark，突破可是资源一大块，有空研究下
