### ISSUE TITLE
🎈百鬼夜行

### ISSUE THREAD

**Issue by runhey** [runhey/OnmyojiAutoScript#73]
### 描述

这个模式下，目标检测无疑是最优解。我们需要一位大手来主导开发。

**Comment by 976913054** [comment]
要是用目标检测的话那应该要搞不少对应式神图片训练了，不知道好不好收集。

**Comment by runhey** [comment]
是的，需要非常多的数据集，不过可以发动广大的群友。

**Comment by 976913054** [comment]
算法直接用现成的yolo应该就够了，工作量最大的还是数据集，如果有需求的话感觉可以试试。

**Comment by runhey** [comment]
完全可以呀

**Comment by runhey** [comment]
https://github.com/runhey/OnmyojiAutoScript/pull/132。
这个任务最核心的部分，还要考虑到假设冰冻的话，怎么给泛化识别。包括说其他的减速、冰冻、快撒豆、这些。

**Comment by Strategic-Fooyou-Agency** [comment]
yolov8 head多了一些积分表示映射，建议用yolov5的head。
v8精度比v5高，而且A6000上能到60fps不知道够不够
如果有需要我可以试一试把预处理跟后处理用cuda做一下
