### ISSUE TITLE
🐛

### ISSUE THREAD

**Issue by KteLinna** [runhey/OnmyojiAutoScript#74]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的

### 描述你的问题

业原火功能重复点击某个层数。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by KteLinna** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/94830638/a031cc71-4493-4d39-901c-59d2a3e3c17d)
![image](https://github.com/runhey/OnmyojiAutoScript/assets/94830638/d46561c2-eecb-447f-b1f1-c91d3479d4d3)

**Comment by KteLinna** [comment]
我个人的解决方案包括：
方案一：图片替换，把我自己截的图片替换源文件的图片(大小与源文件相同，JSON格式也无更改）
结果：失败
方案二：更改截屏方案，原截屏方案为windows系，更换为ADB系
结果：失败
方案三：调整json文件内的threshold属性。
结果：失败

**Comment by KteLinna** [comment]
![image](https://github.com/runhey/OnmyojiAutoScript/assets/94830638/d25b19c4-3581-49da-bf3c-9beceb290892)
使用的一直是dev分支(应该是这样切换的吧)

**Comment by runhey** [comment]
对

**Comment by runhey** [comment]
有拉新最新代码的吗
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/69fa6438-e160-46a5-931a-3d16b56d12ad)
我替换新的图片，增加搜寻范围

**Comment by runhey** [comment]
如果可以你可以尝试下调图片的阈值

**Comment by KteLinna** [comment]
问题解决了！
关于图片阈值请问是不是在image.json这个文件夹里面调整
![image](https://github.com/runhey/OnmyojiAutoScript/assets/94830638/84ec1c90-3963-4a36-a2cd-6216e23a9053)

**Comment by KteLinna** [comment]
emmmm。我明白了！之前是我一直替换错源图片了。感谢感谢
