### ISSUE TITLE
🐛三人组队

### ISSUE THREAD

**Issue by runhey** [runhey/OnmyojiAutoScript#78]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的

### 描述你的问题

。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 截图

![08da3a1ecf49df023965d0dc2d00296f](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/565d180c-c683-4a67-a1aa-3ee6144a1987)

**Comment by paofanxx** [comment]
默认在判断是否进入房间时，是用邀请的十字来判断的，然后在默认接受邀请时，有时候队长会晚进，识别不到最右边那个邀请十字。就会一直死循环。

我增加了一个在左上角的协战房间的识别，就没有问题了。

![a0ea7b184718cea0fe6aaf4bb1c5f3ce](https://github.com/runhey/OnmyojiAutoScript/assets/84143671/08015e71-77d9-413b-b977-70921f2d7f12)
