### ISSUE TITLE
🐛OAS配置异常后无法直接修改

### ISSUE THREAD

**Issue by zhangyunjnj** [runhey/OnmyojiAutoScript#87]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我已经阅读了文档中的 常见问题(FAQ)
- [X] 这个问题出现了至少三次，不是偶发的

### 描述你的问题

作为刚使用oas的新手，配置时经常出现时间格式/个人结界数量设置错误

此时运行会报错且无法在总览使用restart

唯一的办法是删除配置重新再来一遍

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 预期行为

某个任务配置异常时重置该任务，使得可以正常修改

### 截图

![9f093b26e9ea0af12a363316efb34ae](https://github.com/runhey/OnmyojiAutoScript/assets/143109441/86b4fd20-112a-4fff-999e-dcc59420f22a)
![25a4306cc3778070ac1a32167975447](https://github.com/runhey/OnmyojiAutoScript/assets/143109441/8b658670-e4f7-42bb-9877-ae78ee1eb650)

**Comment by yuanshangyujingshierlou** [comment]
直接在config里修改就可以了
