### ISSUE TITLE
✨渠道服玩家苦扫码不能记住登录状态久已之不同渠道服需要安装不同apk

### ISSUE THREAD

**Issue by zhangyunjnj** [runhey/OnmyojiAutoScript#88]
### 当前不足

我的多个账号均为渠道服（小米/B站/魅族等等）

渠道服在官服app中扫码无法保存，已单独安装对应apk文件
但是模拟器（mumu12）中多个阴阳师APP会导致运行失败，将官服app删除后正常

但是若我需要再多开一个B站账号则需要安装第二个app，与运行冲突

求大佬们救救孩子

### 解决方案

安装不同版本阴阳师不影响正常使用且允许多开

**Comment by runhey** [comment]
打开模拟器的文件管理器 `本地/Android/data`
你可以理解为每个不同的客户端都有一份数据，发过来并且表明是哪一个渠道的
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/4755b1b0-cfb0-4950-a223-16a6fbcbcc44)

**Comment by runhey** [comment]
自己手动改客户端
![image](https://github.com/runhey/OnmyojiAutoScript/assets/74492025/35058401-099f-44cc-a5f2-5489735da47c)

**Comment by zhangyunjnj** [comment]
我明白了，等下好其他渠道服以后一起测试，感谢大佬
